/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55bbcb4c72a0
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { LapymeError } from "./lapyme-error.js";

export type ApiErrorEnvelopeData = {
  requestId: string;
  error: models.ErrorT;
};

export class ApiErrorEnvelope extends LapymeError {
  requestId: string;
  error: models.ErrorT;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorEnvelopeData;

  constructor(
    err: ApiErrorEnvelopeData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.requestId = err.requestId;
    this.error = err.error;

    this.name = "ApiErrorEnvelope";
  }
}

/** @internal */
export const ApiErrorEnvelope$inboundSchema: z.ZodMiniType<
  ApiErrorEnvelope,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    error: z.lazy(() => models.ErrorT$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "request_id": "requestId",
    });

    return new ApiErrorEnvelope(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
