/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { LapymeError } from "./lapyme-error.js";

/**
 * Recurso no encontrado
 */
export type CreateSaleNotFoundErrorData = {
  success: boolean;
  error: string;
  code?: string | undefined;
};

/**
 * Recurso no encontrado
 */
export class CreateSaleNotFoundError extends LapymeError {
  success: boolean;
  error: string;
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateSaleNotFoundErrorData;

  constructor(
    err: CreateSaleNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;
    if (err.code != null) this.code = err.code;

    this.name = "CreateSaleNotFoundError";
  }
}

/**
 * Error de validación o lógica de negocio
 */
export type CreateSaleBadRequestErrorData = {
  success: boolean;
  error: string;
  code?: string | undefined;
};

/**
 * Error de validación o lógica de negocio
 */
export class CreateSaleBadRequestError extends LapymeError {
  success: boolean;
  error: string;
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateSaleBadRequestErrorData;

  constructor(
    err: CreateSaleBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;
    if (err.code != null) this.code = err.code;

    this.name = "CreateSaleBadRequestError";
  }
}

/** @internal */
export const CreateSaleNotFoundError$inboundSchema: z.ZodMiniType<
  CreateSaleNotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.string(),
    code: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateSaleNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateSaleBadRequestError$inboundSchema: z.ZodMiniType<
  CreateSaleBadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.string(),
    code: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new CreateSaleBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
