/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { LapymeError } from "./lapyme-error.js";

/**
 * Venta no encontrada
 */
export type GetSaleByIdNotFoundErrorData = {
  success: boolean;
  error: string;
  code?: string | undefined;
};

/**
 * Venta no encontrada
 */
export class GetSaleByIdNotFoundError extends LapymeError {
  success: boolean;
  error: string;
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetSaleByIdNotFoundErrorData;

  constructor(
    err: GetSaleByIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;
    if (err.code != null) this.code = err.code;

    this.name = "GetSaleByIdNotFoundError";
  }
}

/** @internal */
export const GetSaleByIdNotFoundError$inboundSchema: z.ZodMiniType<
  GetSaleByIdNotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.string(),
    code: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSaleByIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
