/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { LapymeError } from "./lapyme-error.js";

/**
 * Límite de solicitudes excedido para la organización
 */
export type RateLimitedErrorData = {
  success: false;
  error: string;
  code: models.Code;
};

/**
 * Límite de solicitudes excedido para la organización
 */
export class RateLimitedError extends LapymeError {
  success: false;
  error: string;
  code: models.Code;

  /** The original data that was passed to this error instance. */
  data$: RateLimitedErrorData;

  constructor(
    err: RateLimitedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;
    this.code = err.code;

    this.name = "RateLimitedError";
  }
}

/** @internal */
export const RateLimitedError$inboundSchema: z.ZodMiniType<
  RateLimitedError,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(false),
    error: types.string(),
    code: models.Code$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new RateLimitedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
