/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceListsGetById } from "../funcs/price-lists-get-by-id.js";
import { priceListsGet } from "../funcs/price-lists-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PriceLists extends ClientSDK {
  /**
   * Obtener lista de listas de precios
   *
   * @remarks
   * Devuelve una lista paginada de listas de precios de la organización. Podés filtrar por nombre usando el parámetro de búsqueda.
   */
  async get(
    request?: operations.GetPriceListsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetPriceListsResponse> {
    return unwrapAsync(priceListsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Obtener lista de precios por ID
   *
   * @remarks
   * Devuelve los datos de una lista de precios específica usando su ID único.
   */
  async getById(
    request: operations.GetPriceListByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPriceListByIdResponse> {
    return unwrapAsync(priceListsGetById(
      this,
      request,
      options,
    ));
  }
}
