/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 47b84c903111
 */

import { purchaseOrdersClose } from "../funcs/purchase-orders-close.js";
import { purchaseOrdersConfirm } from "../funcs/purchase-orders-confirm.js";
import { purchaseOrdersCreatePurchaseOrder } from "../funcs/purchase-orders-create-purchase-order.js";
import { purchaseOrdersGetPurchaseOrderById } from "../funcs/purchase-orders-get-purchase-order-by-id.js";
import { purchaseOrdersListPurchaseOrders } from "../funcs/purchase-orders-list-purchase-orders.js";
import { purchaseOrdersReopen } from "../funcs/purchase-orders-reopen.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Receipts } from "./receipts.js";

export class PurchaseOrders extends ClientSDK {
  private _receipts?: Receipts;
  get receipts(): Receipts {
    return (this._receipts ??= new Receipts(this._options));
  }

  /**
   * Listar órdenes de compra
   *
   * @remarks
   * Lista las órdenes de compra de la organización. Soporta búsqueda por proveedor o número de orden y filtros por fecha y estado.
   */
  async listPurchaseOrders(
    request?: operations.ListApiPurchaseOrdersRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListApiPurchaseOrdersResponse> {
    return unwrapAsync(purchaseOrdersListPurchaseOrders(
      this,
      request,
      options,
    ));
  }

  /**
   * Crear orden de compra
   *
   * @remarks
   * Crea una orden de compra en borrador. Requiere Idempotency-Key.
   */
  async createPurchaseOrder(
    request: operations.CreateApiPurchaseOrderRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateApiPurchaseOrderResponse> {
    return unwrapAsync(purchaseOrdersCreatePurchaseOrder(
      this,
      request,
      options,
    ));
  }

  /**
   * Obtener orden de compra por ID
   *
   * @remarks
   * Devuelve el detalle de una orden de compra.
   */
  async getPurchaseOrderById(
    request: operations.GetApiPurchaseOrderByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiPurchaseOrderByIdResponse> {
    return unwrapAsync(purchaseOrdersGetPurchaseOrderById(
      this,
      request,
      options,
    ));
  }

  /**
   * Confirmar orden de compra
   *
   * @remarks
   * Confirma una orden de compra y devuelve el detalle persistido.
   */
  async confirm(
    request: operations.ConfirmApiPurchaseOrderRequest,
    options?: RequestOptions,
  ): Promise<operations.ConfirmApiPurchaseOrderResponse> {
    return unwrapAsync(purchaseOrdersConfirm(
      this,
      request,
      options,
    ));
  }

  /**
   * Cerrar orden de compra
   *
   * @remarks
   * Cierra una orden de compra y devuelve el detalle persistido.
   */
  async close(
    request: operations.CloseApiPurchaseOrderRequest,
    options?: RequestOptions,
  ): Promise<operations.CloseApiPurchaseOrderResponse> {
    return unwrapAsync(purchaseOrdersClose(
      this,
      request,
      options,
    ));
  }

  /**
   * Reabrir orden de compra
   *
   * @remarks
   * Reabre una orden de compra cerrada y devuelve el detalle persistido.
   */
  async reopen(
    request: operations.ReopenApiPurchaseOrderRequest,
    options?: RequestOptions,
  ): Promise<operations.ReopenApiPurchaseOrderResponse> {
    return unwrapAsync(purchaseOrdersReopen(
      this,
      request,
      options,
    ));
  }
}
