/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { stockPerWarehouseList } from "../funcs/stock-per-warehouse-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class StockPerWarehouse extends ClientSDK {
  /**
   * Obtener stock por ubicación
   *
   * @remarks
   * Devuelve una lista paginada del stock de productos por ubicación de la organización. Podés filtrar por producto específico o ubicación específica usando los parámetros correspondientes.
   */
  async list(
    request?: operations.GetStockPerWarehouseRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetStockPerWarehouseResponse> {
    return unwrapAsync(stockPerWarehouseList(
      this,
      request,
      options,
    ));
  }
}
