/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { suppliersList } from "../funcs/suppliers-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Suppliers extends ClientSDK {
  /**
   * Listar proveedores (v2)
   *
   * @remarks
   * Lista los proveedores de la organización. Soporta búsqueda por nombre, CUIT o email.
   */
  async list(
    request?: operations.ListV2SuppliersRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListV2SuppliersResponse> {
    return unwrapAsync(suppliersList(
      this,
      request,
      options,
    ));
  }
}
