/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the lapyme SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx healthCheck.example.ts
 */

import { Lapyme } from "lapyme";

const lapyme = new Lapyme();

async function main() {
  const result = await lapyme.healthCheck();

  console.log(result);
}

main().catch(console.error);
