/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dfed3168e770
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the lapyme SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx suppliersList.example.ts
 */

import { Lapyme } from "lapyme";

const lapyme = new Lapyme({
  bearerAuth: process.env["LAPYME_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await lapyme.suppliers.list({});

  console.log(result);
}

main().catch(console.error);
