workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    La Pyme API:
        inputs:
            - location: https://docs.lapyme.com.ar/api-reference/openapi-v1.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/lapyme/la-pyme/la-pyme-api
targets:
    lapyme:
        target: typescript
        source: La Pyme API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/lapyme/la-pyme/la-pyme-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
