/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 17e9dd4c5747
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChangeApiOrderFulfillmentLocationRequest = {
  /**
   * ID del pedido
   */
  orderId: string;
  body: models.ApiOrderChangeFulfillmentLocationRequest;
};

export type ChangeApiOrderFulfillmentLocationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiOrderWriteResponse;
};

/** @internal */
export type ChangeApiOrderFulfillmentLocationRequest$Outbound = {
  order_id: string;
  body: models.ApiOrderChangeFulfillmentLocationRequest$Outbound;
};

/** @internal */
export const ChangeApiOrderFulfillmentLocationRequest$outboundSchema:
  z.ZodMiniType<
    ChangeApiOrderFulfillmentLocationRequest$Outbound,
    ChangeApiOrderFulfillmentLocationRequest
  > = z.pipe(
    z.object({
      orderId: z.string(),
      body: models.ApiOrderChangeFulfillmentLocationRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        orderId: "order_id",
      });
    }),
  );

export function changeApiOrderFulfillmentLocationRequestToJSON(
  changeApiOrderFulfillmentLocationRequest:
    ChangeApiOrderFulfillmentLocationRequest,
): string {
  return JSON.stringify(
    ChangeApiOrderFulfillmentLocationRequest$outboundSchema.parse(
      changeApiOrderFulfillmentLocationRequest,
    ),
  );
}

/** @internal */
export const ChangeApiOrderFulfillmentLocationResponse$inboundSchema:
  z.ZodMiniType<ChangeApiOrderFulfillmentLocationResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: models.ApiOrderWriteResponse$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function changeApiOrderFulfillmentLocationResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ChangeApiOrderFulfillmentLocationResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChangeApiOrderFulfillmentLocationResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChangeApiOrderFulfillmentLocationResponse' from JSON`,
  );
}
