/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0703b7c0fb5f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CloseApiPurchaseOrderRequest = {
  /**
   * ID de la orden de compra
   */
  purchaseOrderId: string;
};

export type CloseApiPurchaseOrderResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiPurchaseOrderWriteResponse;
};

/** @internal */
export type CloseApiPurchaseOrderRequest$Outbound = {
  purchase_order_id: string;
};

/** @internal */
export const CloseApiPurchaseOrderRequest$outboundSchema: z.ZodMiniType<
  CloseApiPurchaseOrderRequest$Outbound,
  CloseApiPurchaseOrderRequest
> = z.pipe(
  z.object({
    purchaseOrderId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      purchaseOrderId: "purchase_order_id",
    });
  }),
);

export function closeApiPurchaseOrderRequestToJSON(
  closeApiPurchaseOrderRequest: CloseApiPurchaseOrderRequest,
): string {
  return JSON.stringify(
    CloseApiPurchaseOrderRequest$outboundSchema.parse(
      closeApiPurchaseOrderRequest,
    ),
  );
}

/** @internal */
export const CloseApiPurchaseOrderResponse$inboundSchema: z.ZodMiniType<
  CloseApiPurchaseOrderResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiPurchaseOrderWriteResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function closeApiPurchaseOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<CloseApiPurchaseOrderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CloseApiPurchaseOrderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CloseApiPurchaseOrderResponse' from JSON`,
  );
}
