/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6e0504ed35dc
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateApiProductBulkAdjustmentRequest = {
  /**
   * Clave única para evitar aplicar dos veces el mismo ajuste masivo.
   */
  idempotencyKey: string;
  /**
   * ID opcional de la solicitud para trazabilidad. Si se omite, el servidor genera uno.
   */
  xRequestId?: string | undefined;
  body: models.ApiProductBulkAdjustmentRequest;
};

export type CreateApiProductBulkAdjustmentResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiProductBulkAdjustmentResponse;
};

/** @internal */
export type CreateApiProductBulkAdjustmentRequest$Outbound = {
  "Idempotency-Key": string;
  "X-Request-Id"?: string | undefined;
  body: models.ApiProductBulkAdjustmentRequest$Outbound;
};

/** @internal */
export const CreateApiProductBulkAdjustmentRequest$outboundSchema:
  z.ZodMiniType<
    CreateApiProductBulkAdjustmentRequest$Outbound,
    CreateApiProductBulkAdjustmentRequest
  > = z.pipe(
    z.object({
      idempotencyKey: z.string(),
      xRequestId: z.optional(z.string()),
      body: models.ApiProductBulkAdjustmentRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        idempotencyKey: "Idempotency-Key",
        xRequestId: "X-Request-Id",
      });
    }),
  );

export function createApiProductBulkAdjustmentRequestToJSON(
  createApiProductBulkAdjustmentRequest: CreateApiProductBulkAdjustmentRequest,
): string {
  return JSON.stringify(
    CreateApiProductBulkAdjustmentRequest$outboundSchema.parse(
      createApiProductBulkAdjustmentRequest,
    ),
  );
}

/** @internal */
export const CreateApiProductBulkAdjustmentResponse$inboundSchema:
  z.ZodMiniType<CreateApiProductBulkAdjustmentResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: models.ApiProductBulkAdjustmentResponse$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function createApiProductBulkAdjustmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiProductBulkAdjustmentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateApiProductBulkAdjustmentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiProductBulkAdjustmentResponse' from JSON`,
  );
}
