/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c7b7a78abafd
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateApiFundsTransferRequest = {
  /**
   * Clave estable para deduplicar reintentos de la misma operación.
   */
  idempotencyKey: string;
  body: models.ApiFundsTransferCreateRequest;
};

export type CreateApiFundsTransferResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiFundsTransferDetailResponse;
};

/** @internal */
export type CreateApiFundsTransferRequest$Outbound = {
  "Idempotency-Key": string;
  body: models.ApiFundsTransferCreateRequest$Outbound;
};

/** @internal */
export const CreateApiFundsTransferRequest$outboundSchema: z.ZodMiniType<
  CreateApiFundsTransferRequest$Outbound,
  CreateApiFundsTransferRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    body: models.ApiFundsTransferCreateRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createApiFundsTransferRequestToJSON(
  createApiFundsTransferRequest: CreateApiFundsTransferRequest,
): string {
  return JSON.stringify(
    CreateApiFundsTransferRequest$outboundSchema.parse(
      createApiFundsTransferRequest,
    ),
  );
}

/** @internal */
export const CreateApiFundsTransferResponse$inboundSchema: z.ZodMiniType<
  CreateApiFundsTransferResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiFundsTransferDetailResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createApiFundsTransferResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiFundsTransferResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiFundsTransferResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiFundsTransferResponse' from JSON`,
  );
}
