/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f4336b95abd9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateApiPurchaseOrderRequest = {
  /**
   * Clave estable para deduplicar reintentos de la misma operación.
   */
  idempotencyKey: string;
  body: models.ApiPurchaseOrderRequest;
};

export type CreateApiPurchaseOrderResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiPurchaseOrderWriteResponse;
};

/** @internal */
export type CreateApiPurchaseOrderRequest$Outbound = {
  "Idempotency-Key": string;
  body: models.ApiPurchaseOrderRequest$Outbound;
};

/** @internal */
export const CreateApiPurchaseOrderRequest$outboundSchema: z.ZodMiniType<
  CreateApiPurchaseOrderRequest$Outbound,
  CreateApiPurchaseOrderRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    body: models.ApiPurchaseOrderRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createApiPurchaseOrderRequestToJSON(
  createApiPurchaseOrderRequest: CreateApiPurchaseOrderRequest,
): string {
  return JSON.stringify(
    CreateApiPurchaseOrderRequest$outboundSchema.parse(
      createApiPurchaseOrderRequest,
    ),
  );
}

/** @internal */
export const CreateApiPurchaseOrderResponse$inboundSchema: z.ZodMiniType<
  CreateApiPurchaseOrderResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiPurchaseOrderWriteResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createApiPurchaseOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiPurchaseOrderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiPurchaseOrderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiPurchaseOrderResponse' from JSON`,
  );
}
