/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9707eb0ede76
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateApiPaymentMethodRequest = {
  idempotencyKey: string;
  body: models.ApiPaymentMethodMutationRequest;
};

export type CreateApiPaymentMethodResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiPaymentMethodCreateResponse;
};

/** @internal */
export type CreateApiPaymentMethodRequest$Outbound = {
  "Idempotency-Key": string;
  body: models.ApiPaymentMethodMutationRequest$Outbound;
};

/** @internal */
export const CreateApiPaymentMethodRequest$outboundSchema: z.ZodMiniType<
  CreateApiPaymentMethodRequest$Outbound,
  CreateApiPaymentMethodRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    body: models.ApiPaymentMethodMutationRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createApiPaymentMethodRequestToJSON(
  createApiPaymentMethodRequest: CreateApiPaymentMethodRequest,
): string {
  return JSON.stringify(
    CreateApiPaymentMethodRequest$outboundSchema.parse(
      createApiPaymentMethodRequest,
    ),
  );
}

/** @internal */
export const CreateApiPaymentMethodResponse$inboundSchema: z.ZodMiniType<
  CreateApiPaymentMethodResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiPaymentMethodCreateResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createApiPaymentMethodResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiPaymentMethodResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiPaymentMethodResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiPaymentMethodResponse' from JSON`,
  );
}
