/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5cdeb02e73ed
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DisableApiWebhookEndpointRequest = {
  /**
   * ID del endpoint de webhook
   */
  webhookEndpointId: string;
  /**
   * Clave estable para deduplicar reintentos de la misma operación.
   */
  idempotencyKey: string;
};

export type DisableApiWebhookEndpointResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiWebhookEndpointResponse;
};

/** @internal */
export type DisableApiWebhookEndpointRequest$Outbound = {
  webhook_endpoint_id: string;
  "Idempotency-Key": string;
};

/** @internal */
export const DisableApiWebhookEndpointRequest$outboundSchema: z.ZodMiniType<
  DisableApiWebhookEndpointRequest$Outbound,
  DisableApiWebhookEndpointRequest
> = z.pipe(
  z.object({
    webhookEndpointId: z.string(),
    idempotencyKey: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      webhookEndpointId: "webhook_endpoint_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function disableApiWebhookEndpointRequestToJSON(
  disableApiWebhookEndpointRequest: DisableApiWebhookEndpointRequest,
): string {
  return JSON.stringify(
    DisableApiWebhookEndpointRequest$outboundSchema.parse(
      disableApiWebhookEndpointRequest,
    ),
  );
}

/** @internal */
export const DisableApiWebhookEndpointResponse$inboundSchema: z.ZodMiniType<
  DisableApiWebhookEndpointResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiWebhookEndpointResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function disableApiWebhookEndpointResponseFromJSON(
  jsonString: string,
): SafeParseResult<DisableApiWebhookEndpointResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisableApiWebhookEndpointResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisableApiWebhookEndpointResponse' from JSON`,
  );
}
