/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 349d07766fac
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetApiPaymentMethodRequest = {
  paymentMethodId: string;
};

export type GetApiPaymentMethodResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiPaymentMethodDetailResponse;
};

/** @internal */
export type GetApiPaymentMethodRequest$Outbound = {
  payment_method_id: string;
};

/** @internal */
export const GetApiPaymentMethodRequest$outboundSchema: z.ZodMiniType<
  GetApiPaymentMethodRequest$Outbound,
  GetApiPaymentMethodRequest
> = z.pipe(
  z.object({
    paymentMethodId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      paymentMethodId: "payment_method_id",
    });
  }),
);

export function getApiPaymentMethodRequestToJSON(
  getApiPaymentMethodRequest: GetApiPaymentMethodRequest,
): string {
  return JSON.stringify(
    GetApiPaymentMethodRequest$outboundSchema.parse(getApiPaymentMethodRequest),
  );
}

/** @internal */
export const GetApiPaymentMethodResponse$inboundSchema: z.ZodMiniType<
  GetApiPaymentMethodResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiPaymentMethodDetailResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getApiPaymentMethodResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiPaymentMethodResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiPaymentMethodResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiPaymentMethodResponse' from JSON`,
  );
}
