/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetSaleByIdRequest = {
  /**
   * ID único de la venta
   */
  id: string;
};

/**
 * Venta obtenida exitosamente
 */
export type GetSaleByIdResponseBody = {
  success: boolean;
  data: models.Sale;
};

export type GetSaleByIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetSaleByIdResponseBody;
};

/** @internal */
export type GetSaleByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSaleByIdRequest$outboundSchema: z.ZodMiniType<
  GetSaleByIdRequest$Outbound,
  GetSaleByIdRequest
> = z.object({
  id: z.string(),
});

export function getSaleByIdRequestToJSON(
  getSaleByIdRequest: GetSaleByIdRequest,
): string {
  return JSON.stringify(
    GetSaleByIdRequest$outboundSchema.parse(getSaleByIdRequest),
  );
}

/** @internal */
export const GetSaleByIdResponseBody$inboundSchema: z.ZodMiniType<
  GetSaleByIdResponseBody,
  unknown
> = z.object({
  success: types.boolean(),
  data: models.Sale$inboundSchema,
});

export function getSaleByIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetSaleByIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSaleByIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSaleByIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetSaleByIdResponse$inboundSchema: z.ZodMiniType<
  GetSaleByIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetSaleByIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getSaleByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSaleByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSaleByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSaleByIdResponse' from JSON`,
  );
}
