/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eb6c1711344d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV2PurchaseByIdRequest = {
  /**
   * ID de la compra
   */
  purchaseId: string;
};

export type GetV2PurchaseByIdResponse = {
  headers: { [k: string]: Array<string> };
  result: models.V2PurchaseDetailResponse;
};

/** @internal */
export type GetV2PurchaseByIdRequest$Outbound = {
  purchaseId: string;
};

/** @internal */
export const GetV2PurchaseByIdRequest$outboundSchema: z.ZodMiniType<
  GetV2PurchaseByIdRequest$Outbound,
  GetV2PurchaseByIdRequest
> = z.object({
  purchaseId: z.string(),
});

export function getV2PurchaseByIdRequestToJSON(
  getV2PurchaseByIdRequest: GetV2PurchaseByIdRequest,
): string {
  return JSON.stringify(
    GetV2PurchaseByIdRequest$outboundSchema.parse(getV2PurchaseByIdRequest),
  );
}

/** @internal */
export const GetV2PurchaseByIdResponse$inboundSchema: z.ZodMiniType<
  GetV2PurchaseByIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.V2PurchaseDetailResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV2PurchaseByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2PurchaseByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2PurchaseByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2PurchaseByIdResponse' from JSON`,
  );
}
