/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetCustomerByIdRequest = {
  /**
   * ID único del cliente
   */
  id: string;
};

/**
 * Cliente obtenido exitosamente
 */
export type GetCustomerByIdResponseBody = {
  success: boolean;
  data: models.Customer;
};

export type GetCustomerByIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetCustomerByIdResponseBody;
};

/** @internal */
export type GetCustomerByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomerByIdRequest$outboundSchema: z.ZodMiniType<
  GetCustomerByIdRequest$Outbound,
  GetCustomerByIdRequest
> = z.object({
  id: z.string(),
});

export function getCustomerByIdRequestToJSON(
  getCustomerByIdRequest: GetCustomerByIdRequest,
): string {
  return JSON.stringify(
    GetCustomerByIdRequest$outboundSchema.parse(getCustomerByIdRequest),
  );
}

/** @internal */
export const GetCustomerByIdResponseBody$inboundSchema: z.ZodMiniType<
  GetCustomerByIdResponseBody,
  unknown
> = z.object({
  success: types.boolean(),
  data: models.Customer$inboundSchema,
});

export function getCustomerByIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerByIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerByIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerByIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetCustomerByIdResponse$inboundSchema: z.ZodMiniType<
  GetCustomerByIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetCustomerByIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getCustomerByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerByIdResponse' from JSON`,
  );
}
