/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6b372c325548
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetApiStockTransferByIdRequest = {
  /**
   * ID de la transferencia
   */
  transferId: string;
};

export type GetApiStockTransferByIdResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiTransferDetailResponse;
};

/** @internal */
export type GetApiStockTransferByIdRequest$Outbound = {
  transfer_id: string;
};

/** @internal */
export const GetApiStockTransferByIdRequest$outboundSchema: z.ZodMiniType<
  GetApiStockTransferByIdRequest$Outbound,
  GetApiStockTransferByIdRequest
> = z.pipe(
  z.object({
    transferId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      transferId: "transfer_id",
    });
  }),
);

export function getApiStockTransferByIdRequestToJSON(
  getApiStockTransferByIdRequest: GetApiStockTransferByIdRequest,
): string {
  return JSON.stringify(
    GetApiStockTransferByIdRequest$outboundSchema.parse(
      getApiStockTransferByIdRequest,
    ),
  );
}

/** @internal */
export const GetApiStockTransferByIdResponse$inboundSchema: z.ZodMiniType<
  GetApiStockTransferByIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiTransferDetailResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getApiStockTransferByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiStockTransferByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiStockTransferByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiStockTransferByIdResponse' from JSON`,
  );
}
