/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 130ca84d3717
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Estado del pago
 */
export const ListApiSupplierPaymentsStatus = {
  Active: "active",
  Voided: "voided",
  All: "all",
} as const;
/**
 * Estado del pago
 */
export type ListApiSupplierPaymentsStatus = ClosedEnum<
  typeof ListApiSupplierPaymentsStatus
>;

export type ListApiSupplierPaymentsRequest = {
  /**
   * Valor de next_cursor recibido en la respuesta anterior
   */
  cursor?: string | undefined;
  /**
   * Cantidad máxima de resultados por respuesta
   */
  limit?: number | undefined;
  /**
   * Texto de búsqueda por proveedor, número de pago o método de pago
   */
  query?: string | undefined;
  /**
   * Estado del pago
   */
  status?: ListApiSupplierPaymentsStatus | undefined;
  /**
   * Fecha inicial en formato YYYY-MM-DD
   */
  dateFrom?: Date | undefined;
  /**
   * Fecha final en formato YYYY-MM-DD
   */
  dateTo?: Date | undefined;
};

export type ListApiSupplierPaymentsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiSupplierPaymentListResponse;
};

/** @internal */
export const ListApiSupplierPaymentsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListApiSupplierPaymentsStatus
> = z.enum(ListApiSupplierPaymentsStatus);

/** @internal */
export type ListApiSupplierPaymentsRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
  query?: string | undefined;
  status: string;
  date_from?: string | undefined;
  date_to?: string | undefined;
};

/** @internal */
export const ListApiSupplierPaymentsRequest$outboundSchema: z.ZodMiniType<
  ListApiSupplierPaymentsRequest$Outbound,
  ListApiSupplierPaymentsRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
    query: z.optional(z.string()),
    status: z._default(ListApiSupplierPaymentsStatus$outboundSchema, "active"),
    dateFrom: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
    dateTo: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
  }),
  z.transform((v) => {
    return remap$(v, {
      dateFrom: "date_from",
      dateTo: "date_to",
    });
  }),
);

export function listApiSupplierPaymentsRequestToJSON(
  listApiSupplierPaymentsRequest: ListApiSupplierPaymentsRequest,
): string {
  return JSON.stringify(
    ListApiSupplierPaymentsRequest$outboundSchema.parse(
      listApiSupplierPaymentsRequest,
    ),
  );
}

/** @internal */
export const ListApiSupplierPaymentsResponse$inboundSchema: z.ZodMiniType<
  ListApiSupplierPaymentsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiSupplierPaymentListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listApiSupplierPaymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiSupplierPaymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiSupplierPaymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiSupplierPaymentsResponse' from JSON`,
  );
}
