/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 72dbdad0cad0
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListApiAccountingAccountsRequest = {
  includeInactive?: boolean | undefined;
  isActive?: boolean | undefined;
  isPostable?: boolean | undefined;
  type?: models.ApiSharedEnum5433445ffc | undefined;
  parentId?: string | undefined;
  systemRole?: models.ApiSharedEnum87e38e3147 | undefined;
  isInflationAdjustable?: boolean | undefined;
};

/**
 * Cuentas listadas exitosamente
 */
export type ListApiAccountingAccountsResponseBody = {
  requestId?: string | undefined;
  object?: models.ApiSharedEnume0cf0306aa | undefined;
  data?: Array<models.ApiAccountingAccount> | undefined;
  hasMore?: boolean | undefined;
  nextCursor?: string | null | undefined;
};

export type ListApiAccountingAccountsResponse = {
  headers: { [k: string]: Array<string> };
  result: ListApiAccountingAccountsResponseBody;
};

/** @internal */
export type ListApiAccountingAccountsRequest$Outbound = {
  include_inactive: boolean;
  is_active?: boolean | undefined;
  is_postable?: boolean | undefined;
  type?: string | undefined;
  parent_id?: string | undefined;
  system_role?: string | undefined;
  is_inflation_adjustable?: boolean | undefined;
};

/** @internal */
export const ListApiAccountingAccountsRequest$outboundSchema: z.ZodMiniType<
  ListApiAccountingAccountsRequest$Outbound,
  ListApiAccountingAccountsRequest
> = z.pipe(
  z.object({
    includeInactive: z._default(z.boolean(), false),
    isActive: z.optional(z.boolean()),
    isPostable: z.optional(z.boolean()),
    type: z.optional(models.ApiSharedEnum5433445ffc$outboundSchema),
    parentId: z.optional(z.string()),
    systemRole: z.optional(models.ApiSharedEnum87e38e3147$outboundSchema),
    isInflationAdjustable: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      includeInactive: "include_inactive",
      isActive: "is_active",
      isPostable: "is_postable",
      parentId: "parent_id",
      systemRole: "system_role",
      isInflationAdjustable: "is_inflation_adjustable",
    });
  }),
);

export function listApiAccountingAccountsRequestToJSON(
  listApiAccountingAccountsRequest: ListApiAccountingAccountsRequest,
): string {
  return JSON.stringify(
    ListApiAccountingAccountsRequest$outboundSchema.parse(
      listApiAccountingAccountsRequest,
    ),
  );
}

/** @internal */
export const ListApiAccountingAccountsResponseBody$inboundSchema: z.ZodMiniType<
  ListApiAccountingAccountsResponseBody,
  unknown
> = z.pipe(
  z.object({
    request_id: types.optional(types.string()),
    object: types.optional(models.ApiSharedEnume0cf0306aa$inboundSchema),
    data: types.optional(z.array(models.ApiAccountingAccount$inboundSchema)),
    has_more: types.optional(types.boolean()),
    next_cursor: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function listApiAccountingAccountsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListApiAccountingAccountsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListApiAccountingAccountsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiAccountingAccountsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListApiAccountingAccountsResponse$inboundSchema: z.ZodMiniType<
  ListApiAccountingAccountsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => ListApiAccountingAccountsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listApiAccountingAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiAccountingAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiAccountingAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiAccountingAccountsResponse' from JSON`,
  );
}
