/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 45ba44f21ceb
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Filtra por tipo de producto
 */
export const ListV2ProductsProductType = {
  Product: "product",
  Service: "service",
  Combo: "combo",
} as const;
/**
 * Filtra por tipo de producto
 */
export type ListV2ProductsProductType = ClosedEnum<
  typeof ListV2ProductsProductType
>;

export type ListV2ProductsRequest = {
  /**
   * Número de página
   */
  page?: number | undefined;
  /**
   * Cantidad de resultados por página
   */
  limit?: number | undefined;
  /**
   * Texto de búsqueda por nombre, SKU, barcode u opciones
   */
  query?: string | undefined;
  /**
   * Alias de query
   */
  search?: string | undefined;
  /**
   * Filtra por categoría
   */
  categoryId?: string | undefined;
  /**
   * Filtra por estado activo
   */
  isActive?: boolean | undefined;
  /**
   * Filtra por tipo de producto
   */
  productType?: ListV2ProductsProductType | undefined;
};

export type ListV2ProductsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.V2ProductListResponse;
};

/** @internal */
export const ListV2ProductsProductType$outboundSchema: z.ZodMiniEnum<
  typeof ListV2ProductsProductType
> = z.enum(ListV2ProductsProductType);

/** @internal */
export type ListV2ProductsRequest$Outbound = {
  page: number;
  limit: number;
  query?: string | undefined;
  search?: string | undefined;
  categoryId?: string | undefined;
  isActive?: boolean | undefined;
  productType?: string | undefined;
};

/** @internal */
export const ListV2ProductsRequest$outboundSchema: z.ZodMiniType<
  ListV2ProductsRequest$Outbound,
  ListV2ProductsRequest
> = z.object({
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 50),
  query: z.optional(z.string()),
  search: z.optional(z.string()),
  categoryId: z.optional(z.string()),
  isActive: z.optional(z.boolean()),
  productType: z.optional(ListV2ProductsProductType$outboundSchema),
});

export function listV2ProductsRequestToJSON(
  listV2ProductsRequest: ListV2ProductsRequest,
): string {
  return JSON.stringify(
    ListV2ProductsRequest$outboundSchema.parse(listV2ProductsRequest),
  );
}

/** @internal */
export const ListV2ProductsResponse$inboundSchema: z.ZodMiniType<
  ListV2ProductsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.V2ProductListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listV2ProductsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListV2ProductsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListV2ProductsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListV2ProductsResponse' from JSON`,
  );
}
