/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4d4816cb927
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListApiSuppliersRequest = {
  /**
   * Valor de next_cursor recibido en la respuesta anterior
   */
  cursor?: string | undefined;
  /**
   * Cantidad máxima de resultados por respuesta
   */
  limit?: number | undefined;
  /**
   * Texto de búsqueda por nombre, CUIT o email
   */
  query?: string | undefined;
  /**
   * Filtra por estado activo
   */
  isActive?: boolean | undefined;
  /**
   * Estados exactos a incluir. Enviá ambos para incluir proveedores activos e inactivos.
   */
  status?: Array<models.ApiSharedEnumd952d5ce8e> | undefined;
};

export type ListApiSuppliersResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiSupplierListResponse;
};

/** @internal */
export type ListApiSuppliersRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
  query?: string | undefined;
  is_active?: boolean | undefined;
  status?: Array<string> | undefined;
};

/** @internal */
export const ListApiSuppliersRequest$outboundSchema: z.ZodMiniType<
  ListApiSuppliersRequest$Outbound,
  ListApiSuppliersRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
    query: z.optional(z.string()),
    isActive: z.optional(z.boolean()),
    status: z.optional(z.array(models.ApiSharedEnumd952d5ce8e$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      isActive: "is_active",
    });
  }),
);

export function listApiSuppliersRequestToJSON(
  listApiSuppliersRequest: ListApiSuppliersRequest,
): string {
  return JSON.stringify(
    ListApiSuppliersRequest$outboundSchema.parse(listApiSuppliersRequest),
  );
}

/** @internal */
export const ListApiSuppliersResponse$inboundSchema: z.ZodMiniType<
  ListApiSuppliersResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiSupplierListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listApiSuppliersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiSuppliersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiSuppliersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiSuppliersResponse' from JSON`,
  );
}
