/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ddf041e6d2f0
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListApiProductMetafieldDefinitionsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiProductMetafieldDefinitionsResponse;
};

/** @internal */
export const ListApiProductMetafieldDefinitionsResponse$inboundSchema:
  z.ZodMiniType<ListApiProductMetafieldDefinitionsResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: models.ApiProductMetafieldDefinitionsResponse$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listApiProductMetafieldDefinitionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListApiProductMetafieldDefinitionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListApiProductMetafieldDefinitionsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListApiProductMetafieldDefinitionsResponse' from JSON`,
  );
}
