/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5a2e718e8122
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Campo de fecha a usar para el filtro
 */
export const DateAttribute = {
  InvoiceDate: "invoiceDate",
  DueDate: "dueDate",
} as const;
/**
 * Campo de fecha a usar para el filtro
 */
export type DateAttribute = ClosedEnum<typeof DateAttribute>;

/**
 * Campo monetario a usar para min/max
 */
export const AmountAttribute = {
  Balance: "balance",
  Total: "total",
} as const;
/**
 * Campo monetario a usar para min/max
 */
export type AmountAttribute = ClosedEnum<typeof AmountAttribute>;

export type ListV2PurchasesRequest = {
  /**
   * Número de página
   */
  page?: number | undefined;
  /**
   * Cantidad de resultados por página
   */
  limit?: number | undefined;
  /**
   * Texto de búsqueda por proveedor, CUIT o número de factura del proveedor
   */
  query?: string | undefined;
  /**
   * Alias de query
   */
  search?: string | undefined;
  /**
   * Fecha inicial para el filtro
   */
  dateFrom?: Date | undefined;
  /**
   * Fecha final para el filtro
   */
  dateTo?: Date | undefined;
  /**
   * Campo de fecha a usar para el filtro
   */
  dateAttribute?: DateAttribute | undefined;
  /**
   * Campo monetario a usar para min/max
   */
  amountAttribute?: AmountAttribute | undefined;
  /**
   * Monto mínimo para el filtro
   */
  minBalance?: number | undefined;
  /**
   * Monto máximo para el filtro
   */
  maxBalance?: number | undefined;
};

export type ListV2PurchasesResponse = {
  headers: { [k: string]: Array<string> };
  result: models.V2PurchaseListResponse;
};

/** @internal */
export const DateAttribute$outboundSchema: z.ZodMiniEnum<typeof DateAttribute> =
  z.enum(DateAttribute);

/** @internal */
export const AmountAttribute$outboundSchema: z.ZodMiniEnum<
  typeof AmountAttribute
> = z.enum(AmountAttribute);

/** @internal */
export type ListV2PurchasesRequest$Outbound = {
  page: number;
  limit: number;
  query?: string | undefined;
  search?: string | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  dateAttribute: string;
  amountAttribute: string;
  minBalance?: number | undefined;
  maxBalance?: number | undefined;
};

/** @internal */
export const ListV2PurchasesRequest$outboundSchema: z.ZodMiniType<
  ListV2PurchasesRequest$Outbound,
  ListV2PurchasesRequest
> = z.object({
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 50),
  query: z.optional(z.string()),
  search: z.optional(z.string()),
  dateFrom: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  dateTo: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  dateAttribute: z._default(DateAttribute$outboundSchema, "invoiceDate"),
  amountAttribute: z._default(AmountAttribute$outboundSchema, "balance"),
  minBalance: z.optional(z.int()),
  maxBalance: z.optional(z.int()),
});

export function listV2PurchasesRequestToJSON(
  listV2PurchasesRequest: ListV2PurchasesRequest,
): string {
  return JSON.stringify(
    ListV2PurchasesRequest$outboundSchema.parse(listV2PurchasesRequest),
  );
}

/** @internal */
export const ListV2PurchasesResponse$inboundSchema: z.ZodMiniType<
  ListV2PurchasesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.V2PurchaseListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listV2PurchasesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListV2PurchasesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListV2PurchasesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListV2PurchasesResponse' from JSON`,
  );
}
