/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c5ef7f9b0581
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListApiWebhookEndpointsRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  status?: models.ApiSharedEnum1c9cda998e | undefined;
  ownerType?: models.ApiSharedEnum4b017f6476 | undefined;
  eventType?: models.ApiSharedEnum09382f5041 | undefined;
};

export type ListApiWebhookEndpointsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiWebhookEndpointListResponse;
};

/** @internal */
export type ListApiWebhookEndpointsRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
  status?: string | undefined;
  owner_type?: string | undefined;
  event_type?: string | undefined;
};

/** @internal */
export const ListApiWebhookEndpointsRequest$outboundSchema: z.ZodMiniType<
  ListApiWebhookEndpointsRequest$Outbound,
  ListApiWebhookEndpointsRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 25),
    status: z.optional(models.ApiSharedEnum1c9cda998e$outboundSchema),
    ownerType: z.optional(models.ApiSharedEnum4b017f6476$outboundSchema),
    eventType: z.optional(models.ApiSharedEnum09382f5041$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      ownerType: "owner_type",
      eventType: "event_type",
    });
  }),
);

export function listApiWebhookEndpointsRequestToJSON(
  listApiWebhookEndpointsRequest: ListApiWebhookEndpointsRequest,
): string {
  return JSON.stringify(
    ListApiWebhookEndpointsRequest$outboundSchema.parse(
      listApiWebhookEndpointsRequest,
    ),
  );
}

/** @internal */
export const ListApiWebhookEndpointsResponse$inboundSchema: z.ZodMiniType<
  ListApiWebhookEndpointsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiWebhookEndpointListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listApiWebhookEndpointsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiWebhookEndpointsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiWebhookEndpointsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiWebhookEndpointsResponse' from JSON`,
  );
}
