/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5ba226d44e19
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const SortOrder = {
  Newest: "newest",
  Oldest: "oldest",
} as const;
export type SortOrder = ClosedEnum<typeof SortOrder>;

export type ListApiSummarizedJournalRequest = {
  /**
   * Fecha inicial del período. Obligatoria junto con date_to si no se envía period_preset.
   */
  dateFrom?: Date | undefined;
  /**
   * Fecha final inclusiva del período. Obligatoria junto con date_from si no se envía period_preset.
   */
  dateTo?: Date | undefined;
  /**
   * Atajo de período resuelto por la API a date_from/date_to en horario de Argentina. No enviarlo junto con date_from/date_to.
   */
  periodPreset?: models.ApiSharedEnumab9ba78640 | undefined;
  cursor?: string | undefined;
  limit?: number | undefined;
  sourceTypes?: Array<string> | undefined;
  sortOrder?: SortOrder | undefined;
};

export type ListApiSummarizedJournalResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiJournalEntriesListResponse;
};

/** @internal */
export const SortOrder$outboundSchema: z.ZodMiniEnum<typeof SortOrder> = z.enum(
  SortOrder,
);

/** @internal */
export type ListApiSummarizedJournalRequest$Outbound = {
  date_from?: string | undefined;
  date_to?: string | undefined;
  period_preset?: string | undefined;
  cursor?: string | undefined;
  limit: number;
  source_types?: Array<string> | undefined;
  sort_order: string;
};

/** @internal */
export const ListApiSummarizedJournalRequest$outboundSchema: z.ZodMiniType<
  ListApiSummarizedJournalRequest$Outbound,
  ListApiSummarizedJournalRequest
> = z.pipe(
  z.object({
    dateFrom: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
    dateTo: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
    periodPreset: z.optional(models.ApiSharedEnumab9ba78640$outboundSchema),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
    sourceTypes: z.optional(z.array(z.string())),
    sortOrder: z._default(SortOrder$outboundSchema, "oldest"),
  }),
  z.transform((v) => {
    return remap$(v, {
      dateFrom: "date_from",
      dateTo: "date_to",
      periodPreset: "period_preset",
      sourceTypes: "source_types",
      sortOrder: "sort_order",
    });
  }),
);

export function listApiSummarizedJournalRequestToJSON(
  listApiSummarizedJournalRequest: ListApiSummarizedJournalRequest,
): string {
  return JSON.stringify(
    ListApiSummarizedJournalRequest$outboundSchema.parse(
      listApiSummarizedJournalRequest,
    ),
  );
}

/** @internal */
export const ListApiSummarizedJournalResponse$inboundSchema: z.ZodMiniType<
  ListApiSummarizedJournalResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiJournalEntriesListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listApiSummarizedJournalResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiSummarizedJournalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiSummarizedJournalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiSummarizedJournalResponse' from JSON`,
  );
}
