/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1ca2ad59de90
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const Kind = {
  Account: "account",
  Category: "category",
  CostCenter: "cost_center",
  Customer: "customer",
  InventoryCategory: "inventory_category",
  InventoryProductVariant: "inventory_product_variant",
  InventoryProductVariantGroup: "inventory_product_variant_group",
  InventoryWarehouse: "inventory_warehouse",
  PaymentMethod: "payment_method",
  PointOfSale: "point_of_sale",
  PriceList: "price_list",
  ProductVariant: "product_variant",
  ProductVariantGroup: "product_variant_group",
  Register: "register",
  Safe: "safe",
  Seller: "seller",
  Supplier: "supplier",
  Tag: "tag",
  TagCustomer: "tag_customer",
  TagSupplier: "tag_supplier",
  TagProduct: "tag_product",
  TagSale: "tag_sale",
  TagPurchase: "tag_purchase",
  TagPurchaseOrder: "tag_purchase_order",
  TagTransfer: "tag_transfer",
  Warehouse: "warehouse",
} as const;
export type Kind = ClosedEnum<typeof Kind>;

export type ListApiReferenceCandidatesRequest = {
  kind: Kind;
  query: string;
};

/** @internal */
export const Kind$outboundSchema: z.ZodMiniEnum<typeof Kind> = z.enum(Kind);

/** @internal */
export type ListApiReferenceCandidatesRequest$Outbound = {
  kind: string;
  query: string;
};

/** @internal */
export const ListApiReferenceCandidatesRequest$outboundSchema: z.ZodMiniType<
  ListApiReferenceCandidatesRequest$Outbound,
  ListApiReferenceCandidatesRequest
> = z.object({
  kind: Kind$outboundSchema,
  query: z.string(),
});

export function listApiReferenceCandidatesRequestToJSON(
  listApiReferenceCandidatesRequest: ListApiReferenceCandidatesRequest,
): string {
  return JSON.stringify(
    ListApiReferenceCandidatesRequest$outboundSchema.parse(
      listApiReferenceCandidatesRequest,
    ),
  );
}
