/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ea2e3a996ad4
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const ListApiStockTransfersStatus = {
  Draft: "draft",
  InTransit: "in_transit",
  Completed: "completed",
  Cancelled: "cancelled",
} as const;
export type ListApiStockTransfersStatus = ClosedEnum<
  typeof ListApiStockTransfersStatus
>;

export type ListApiStockTransfersRequest = {
  /**
   * Valor de next_cursor recibido en la respuesta anterior
   */
  cursor?: string | undefined;
  /**
   * Cantidad máxima de resultados por respuesta
   */
  limit?: number | undefined;
  /**
   * Texto de búsqueda por nota, producto, SKU o variante
   */
  query?: string | undefined;
  /**
   * Alias de query
   */
  search?: string | undefined;
  /**
   * Fecha inicial
   */
  dateFrom?: Date | undefined;
  /**
   * Fecha final
   */
  dateTo?: Date | undefined;
  /**
   * Estados de la transferencia. Puede repetirse o enviarse separada por comas.
   */
  statuses?: Array<ListApiStockTransfersStatus> | undefined;
  /**
   * Depósito de origen
   */
  sourceWarehouseId?: string | undefined;
  /**
   * Depósito de destino
   */
  targetWarehouseId?: string | undefined;
};

export type ListApiStockTransfersResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiTransferListResponse;
};

/** @internal */
export const ListApiStockTransfersStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListApiStockTransfersStatus
> = z.enum(ListApiStockTransfersStatus);

/** @internal */
export type ListApiStockTransfersRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
  query?: string | undefined;
  search?: string | undefined;
  date_from?: string | undefined;
  date_to?: string | undefined;
  statuses?: Array<string> | undefined;
  source_warehouse_id?: string | undefined;
  target_warehouse_id?: string | undefined;
};

/** @internal */
export const ListApiStockTransfersRequest$outboundSchema: z.ZodMiniType<
  ListApiStockTransfersRequest$Outbound,
  ListApiStockTransfersRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
    query: z.optional(z.string()),
    search: z.optional(z.string()),
    dateFrom: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
    dateTo: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
    statuses: z.optional(z.array(ListApiStockTransfersStatus$outboundSchema)),
    sourceWarehouseId: z.optional(z.string()),
    targetWarehouseId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      dateFrom: "date_from",
      dateTo: "date_to",
      sourceWarehouseId: "source_warehouse_id",
      targetWarehouseId: "target_warehouse_id",
    });
  }),
);

export function listApiStockTransfersRequestToJSON(
  listApiStockTransfersRequest: ListApiStockTransfersRequest,
): string {
  return JSON.stringify(
    ListApiStockTransfersRequest$outboundSchema.parse(
      listApiStockTransfersRequest,
    ),
  );
}

/** @internal */
export const ListApiStockTransfersResponse$inboundSchema: z.ZodMiniType<
  ListApiStockTransfersResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiTransferListResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listApiStockTransfersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiStockTransfersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiStockTransfersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiStockTransfersResponse' from JSON`,
  );
}
