/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8f109bcce896
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type QueryApiReportResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ReportQueryResponse;
};

/** @internal */
export const QueryApiReportResponse$inboundSchema: z.ZodMiniType<
  QueryApiReportResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ReportQueryResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function queryApiReportResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryApiReportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryApiReportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryApiReportResponse' from JSON`,
  );
}
