/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a55d14c86e9d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RotateSecretApiWebhookEndpointRequest = {
  /**
   * ID del endpoint de webhook
   */
  webhookEndpointId: string;
  /**
   * Clave estable para deduplicar reintentos de la misma operación.
   */
  idempotencyKey: string;
};

export type RotateSecretApiWebhookEndpointResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiWebhookEndpointSecretResponse;
};

/** @internal */
export type RotateSecretApiWebhookEndpointRequest$Outbound = {
  webhook_endpoint_id: string;
  "Idempotency-Key": string;
};

/** @internal */
export const RotateSecretApiWebhookEndpointRequest$outboundSchema:
  z.ZodMiniType<
    RotateSecretApiWebhookEndpointRequest$Outbound,
    RotateSecretApiWebhookEndpointRequest
  > = z.pipe(
    z.object({
      webhookEndpointId: z.string(),
      idempotencyKey: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        webhookEndpointId: "webhook_endpoint_id",
        idempotencyKey: "Idempotency-Key",
      });
    }),
  );

export function rotateSecretApiWebhookEndpointRequestToJSON(
  rotateSecretApiWebhookEndpointRequest: RotateSecretApiWebhookEndpointRequest,
): string {
  return JSON.stringify(
    RotateSecretApiWebhookEndpointRequest$outboundSchema.parse(
      rotateSecretApiWebhookEndpointRequest,
    ),
  );
}

/** @internal */
export const RotateSecretApiWebhookEndpointResponse$inboundSchema:
  z.ZodMiniType<RotateSecretApiWebhookEndpointResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: models.ApiWebhookEndpointSecretResponse$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function rotateSecretApiWebhookEndpointResponseFromJSON(
  jsonString: string,
): SafeParseResult<RotateSecretApiWebhookEndpointResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RotateSecretApiWebhookEndpointResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RotateSecretApiWebhookEndpointResponse' from JSON`,
  );
}
