/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateWarehouseByIdRequest = {
  /**
   * ID único de la ubicación
   */
  id: string;
  body: models.CreateWarehouseRequest;
};

export type UpdateWarehouseByIdResponse = {
  headers: { [k: string]: Array<string> };
  result: models.WarehouseResponse;
};

/** @internal */
export type UpdateWarehouseByIdRequest$Outbound = {
  id: string;
  body: models.CreateWarehouseRequest$Outbound;
};

/** @internal */
export const UpdateWarehouseByIdRequest$outboundSchema: z.ZodMiniType<
  UpdateWarehouseByIdRequest$Outbound,
  UpdateWarehouseByIdRequest
> = z.object({
  id: z.string(),
  body: models.CreateWarehouseRequest$outboundSchema,
});

export function updateWarehouseByIdRequestToJSON(
  updateWarehouseByIdRequest: UpdateWarehouseByIdRequest,
): string {
  return JSON.stringify(
    UpdateWarehouseByIdRequest$outboundSchema.parse(updateWarehouseByIdRequest),
  );
}

/** @internal */
export const UpdateWarehouseByIdResponse$inboundSchema: z.ZodMiniType<
  UpdateWarehouseByIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.WarehouseResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateWarehouseByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWarehouseByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWarehouseByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWarehouseByIdResponse' from JSON`,
  );
}
