/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dabfdef96faf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateApiCategoryRequest = {
  categoryId: string;
  idempotencyKey: string;
  body: models.ApiCategoryMutationRequest;
};

export type UpdateApiCategoryResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiCategoryUpdateResponse;
};

/** @internal */
export type UpdateApiCategoryRequest$Outbound = {
  category_id: string;
  "Idempotency-Key": string;
  body: models.ApiCategoryMutationRequest$Outbound;
};

/** @internal */
export const UpdateApiCategoryRequest$outboundSchema: z.ZodMiniType<
  UpdateApiCategoryRequest$Outbound,
  UpdateApiCategoryRequest
> = z.pipe(
  z.object({
    categoryId: z.string(),
    idempotencyKey: z.string(),
    body: models.ApiCategoryMutationRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      categoryId: "category_id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateApiCategoryRequestToJSON(
  updateApiCategoryRequest: UpdateApiCategoryRequest,
): string {
  return JSON.stringify(
    UpdateApiCategoryRequest$outboundSchema.parse(updateApiCategoryRequest),
  );
}

/** @internal */
export const UpdateApiCategoryResponse$inboundSchema: z.ZodMiniType<
  UpdateApiCategoryResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiCategoryUpdateResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateApiCategoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiCategoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiCategoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiCategoryResponse' from JSON`,
  );
}
