/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 89d976cb2020
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateApiWarehouseRequest = {
  /**
   * ID del depósito
   */
  warehouseId: string;
  /**
   * ID opcional de la solicitud para trazabilidad. Si se omite, el servidor genera uno.
   */
  xRequestId?: string | undefined;
  body: models.ApiWarehouseUpdateRequest;
};

export type UpdateApiWarehouseResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiWarehouseUpdateResponse;
};

/** @internal */
export type UpdateApiWarehouseRequest$Outbound = {
  warehouse_id: string;
  "X-Request-Id"?: string | undefined;
  body: models.ApiWarehouseUpdateRequest$Outbound;
};

/** @internal */
export const UpdateApiWarehouseRequest$outboundSchema: z.ZodMiniType<
  UpdateApiWarehouseRequest$Outbound,
  UpdateApiWarehouseRequest
> = z.pipe(
  z.object({
    warehouseId: z.string(),
    xRequestId: z.optional(z.string()),
    body: models.ApiWarehouseUpdateRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      warehouseId: "warehouse_id",
      xRequestId: "X-Request-Id",
    });
  }),
);

export function updateApiWarehouseRequestToJSON(
  updateApiWarehouseRequest: UpdateApiWarehouseRequest,
): string {
  return JSON.stringify(
    UpdateApiWarehouseRequest$outboundSchema.parse(updateApiWarehouseRequest),
  );
}

/** @internal */
export const UpdateApiWarehouseResponse$inboundSchema: z.ZodMiniType<
  UpdateApiWarehouseResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiWarehouseUpdateResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateApiWarehouseResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiWarehouseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiWarehouseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiWarehouseResponse' from JSON`,
  );
}
