/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a76d518efefb
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateApiProductRequest = {
  /**
   * ID del producto
   */
  productId: string;
  /**
   * ID opcional de la solicitud para trazabilidad. Si se omite, el servidor genera uno.
   */
  xRequestId?: string | undefined;
  /**
   * Clave estable obligatoria cuando product_type es combo. Reutilizala solo para reintentar exactamente la misma actualización.
   */
  idempotencyKey?: string | undefined;
  body: models.ApiProductUpdateRequestUnion;
};

export type UpdateApiProductResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ApiProductUpdateResponse;
};

/** @internal */
export type UpdateApiProductRequest$Outbound = {
  product_id: string;
  "X-Request-Id"?: string | undefined;
  "Idempotency-Key"?: string | undefined;
  body: models.ApiProductUpdateRequestUnion$Outbound;
};

/** @internal */
export const UpdateApiProductRequest$outboundSchema: z.ZodMiniType<
  UpdateApiProductRequest$Outbound,
  UpdateApiProductRequest
> = z.pipe(
  z.object({
    productId: z.string(),
    xRequestId: z.optional(z.string()),
    idempotencyKey: z.optional(z.string()),
    body: models.ApiProductUpdateRequestUnion$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      productId: "product_id",
      xRequestId: "X-Request-Id",
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateApiProductRequestToJSON(
  updateApiProductRequest: UpdateApiProductRequest,
): string {
  return JSON.stringify(
    UpdateApiProductRequest$outboundSchema.parse(updateApiProductRequest),
  );
}

/** @internal */
export const UpdateApiProductResponse$inboundSchema: z.ZodMiniType<
  UpdateApiProductResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ApiProductUpdateResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateApiProductResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiProductResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiProductResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiProductResponse' from JSON`,
  );
}
