/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5eb28598d547
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateProductByIdRequest = {
  /**
   * ID único del producto
   */
  id: string;
  body: models.CreateProductRequest;
};

export type UpdateProductByIdResponse = {
  headers: { [k: string]: Array<string> };
  result: models.UpdateProductResponse;
};

/** @internal */
export type UpdateProductByIdRequest$Outbound = {
  id: string;
  body: models.CreateProductRequest$Outbound;
};

/** @internal */
export const UpdateProductByIdRequest$outboundSchema: z.ZodMiniType<
  UpdateProductByIdRequest$Outbound,
  UpdateProductByIdRequest
> = z.object({
  id: z.string(),
  body: models.CreateProductRequest$outboundSchema,
});

export function updateProductByIdRequestToJSON(
  updateProductByIdRequest: UpdateProductByIdRequest,
): string {
  return JSON.stringify(
    UpdateProductByIdRequest$outboundSchema.parse(updateProductByIdRequest),
  );
}

/** @internal */
export const UpdateProductByIdResponse$inboundSchema: z.ZodMiniType<
  UpdateProductByIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.UpdateProductResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function updateProductByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProductByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProductByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProductByIdResponse' from JSON`,
  );
}
