/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 65a61192be89
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ApiOrderListResponseCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiOrderListResponseCurrency = OpenEnum<
  typeof ApiOrderListResponseCurrency
>;

export const ApiOrderListResponseOrderStatus = {
  Open: "open",
  Completed: "completed",
  Cancelled: "cancelled",
} as const;
export type ApiOrderListResponseOrderStatus = OpenEnum<
  typeof ApiOrderListResponseOrderStatus
>;

export const ApiOrderListResponseFulfillmentStatus = {
  Unfulfilled: "unfulfilled",
  InProgress: "in_progress",
  PartiallyFulfilled: "partially_fulfilled",
  Fulfilled: "fulfilled",
  Cancelled: "cancelled",
} as const;
export type ApiOrderListResponseFulfillmentStatus = OpenEnum<
  typeof ApiOrderListResponseFulfillmentStatus
>;

export const ApiOrderListResponseInvoicingStatus = {
  Pending: "pending",
  PartiallyInvoiced: "partially_invoiced",
  Invoiced: "invoiced",
} as const;
export type ApiOrderListResponseInvoicingStatus = OpenEnum<
  typeof ApiOrderListResponseInvoicingStatus
>;

export type ApiOrderListResponseData = {
  object: "order";
  id: string;
  orderNumber: string;
  rawOrderNumber: number;
  orderDate: Date;
  customerId: string;
  customerName: string;
  customerTaxId: string | null;
  itemsCount: number;
  totalUnits: number;
  discountAmount: number;
  subtotal: number;
  taxAmount: number;
  total: number;
  currency: ApiOrderListResponseCurrency;
  orderStatus: ApiOrderListResponseOrderStatus;
  fulfillmentStatus: ApiOrderListResponseFulfillmentStatus;
  invoicingStatus: ApiOrderListResponseInvoicingStatus;
  notes: string | null;
  createdAt: Date;
  createdByName: string;
};

/**
 * List-envelope discriminator.
 */
export const ApiOrderListResponseObject = {
  List: "list",
} as const;
/**
 * List-envelope discriminator.
 */
export type ApiOrderListResponseObject = ClosedEnum<
  typeof ApiOrderListResponseObject
>;

export type ApiOrderListResponse = {
  requestId: string;
  data: Array<ApiOrderListResponseData>;
  hasMore: boolean;
  nextCursor: string | null;
  /**
   * List-envelope discriminator.
   */
  object: ApiOrderListResponseObject;
  /**
   * Requested list path.
   */
  url: string;
};

/** @internal */
export const ApiOrderListResponseCurrency$inboundSchema: z.ZodMiniType<
  ApiOrderListResponseCurrency,
  unknown
> = openEnums.inboundSchema(ApiOrderListResponseCurrency);

/** @internal */
export const ApiOrderListResponseOrderStatus$inboundSchema: z.ZodMiniType<
  ApiOrderListResponseOrderStatus,
  unknown
> = openEnums.inboundSchema(ApiOrderListResponseOrderStatus);

/** @internal */
export const ApiOrderListResponseFulfillmentStatus$inboundSchema: z.ZodMiniType<
  ApiOrderListResponseFulfillmentStatus,
  unknown
> = openEnums.inboundSchema(ApiOrderListResponseFulfillmentStatus);

/** @internal */
export const ApiOrderListResponseInvoicingStatus$inboundSchema: z.ZodMiniType<
  ApiOrderListResponseInvoicingStatus,
  unknown
> = openEnums.inboundSchema(ApiOrderListResponseInvoicingStatus);

/** @internal */
export const ApiOrderListResponseData$inboundSchema: z.ZodMiniType<
  ApiOrderListResponseData,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("order"),
    id: types.string(),
    order_number: types.string(),
    raw_order_number: types.number(),
    order_date: types.date(),
    customer_id: types.string(),
    customer_name: types.string(),
    customer_tax_id: types.nullable(types.string()),
    items_count: types.number(),
    total_units: types.number(),
    discount_amount: types.number(),
    subtotal: types.number(),
    tax_amount: types.number(),
    total: types.number(),
    currency: ApiOrderListResponseCurrency$inboundSchema,
    order_status: ApiOrderListResponseOrderStatus$inboundSchema,
    fulfillment_status: ApiOrderListResponseFulfillmentStatus$inboundSchema,
    invoicing_status: ApiOrderListResponseInvoicingStatus$inboundSchema,
    notes: types.nullable(types.string()),
    created_at: types.date(),
    created_by_name: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_number": "orderNumber",
      "raw_order_number": "rawOrderNumber",
      "order_date": "orderDate",
      "customer_id": "customerId",
      "customer_name": "customerName",
      "customer_tax_id": "customerTaxId",
      "items_count": "itemsCount",
      "total_units": "totalUnits",
      "discount_amount": "discountAmount",
      "tax_amount": "taxAmount",
      "order_status": "orderStatus",
      "fulfillment_status": "fulfillmentStatus",
      "invoicing_status": "invoicingStatus",
      "created_at": "createdAt",
      "created_by_name": "createdByName",
    });
  }),
);

export function apiOrderListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiOrderListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiOrderListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiOrderListResponseData' from JSON`,
  );
}

/** @internal */
export const ApiOrderListResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof ApiOrderListResponseObject
> = z.enum(ApiOrderListResponseObject);

/** @internal */
export const ApiOrderListResponse$inboundSchema: z.ZodMiniType<
  ApiOrderListResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.array(z.lazy(() => ApiOrderListResponseData$inboundSchema)),
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    object: ApiOrderListResponseObject$inboundSchema,
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function apiOrderListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiOrderListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiOrderListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiOrderListResponse' from JSON`,
  );
}
