/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1c76c3967ab3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ApiCustomerPaymentDetailResponseStatus = {
  Active: "active",
  Voided: "voided",
} as const;
export type ApiCustomerPaymentDetailResponseStatus = OpenEnum<
  typeof ApiCustomerPaymentDetailResponseStatus
>;

export const ApiCustomerPaymentDetailResponseCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiCustomerPaymentDetailResponseCurrency = OpenEnum<
  typeof ApiCustomerPaymentDetailResponseCurrency
>;

export const ApiCustomerPaymentDetailResponseSettlementCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiCustomerPaymentDetailResponseSettlementCurrency = OpenEnum<
  typeof ApiCustomerPaymentDetailResponseSettlementCurrency
>;

export type ApiCustomerPaymentDetailResponseExchangeRate = string | number;

export type ApiCustomerPaymentDetailResponseSplit = {
  id?: string | undefined;
  paymentMethodId: string;
  paymentMethodName?: string | undefined;
  amount: number;
  reference?: string | null | undefined;
  cardBrand?: string | null | undefined;
  cardBatchNumber?: string | null | undefined;
  cardCouponNumber?: string | null | undefined;
  cardInstallmentPlanCode?: string | null | undefined;
  notes?: string | null | undefined;
  feeAmount?: number | null | undefined;
  feePercentageApplied?: string | null | undefined;
  feeFixedApplied?: number | null | undefined;
  netAmount?: number | null | undefined;
  checkId?: string | null | undefined;
  registerId?: string | null | undefined;
  safeId?: string | null | undefined;
};

export type ApiCustomerPaymentDetailResponseApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiCustomerPaymentDetailResponseCreditApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiCustomerPaymentDetailResponseJournalLineApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiCustomerPaymentDetailResponseAdvanceApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export const ApiCustomerPaymentDetailResponseType = {
  Ganancias: "ganancias",
  Iibb: "iibb",
  Iva: "iva",
  Suss: "suss",
  SegHig: "seg_hig",
} as const;
export type ApiCustomerPaymentDetailResponseType = OpenEnum<
  typeof ApiCustomerPaymentDetailResponseType
>;

export type ApiCustomerPaymentDetailResponseWithholding = {
  id?: string | undefined;
  type: ApiCustomerPaymentDetailResponseType;
  provinceId?: string | null | undefined;
  regimen?: string | null | undefined;
  amount: number;
  rate?: number | null | undefined;
  calculationBase?: number | null | undefined;
  certificateNumber: string;
};

export type ApiCustomerPaymentDetailResponseCustomerPayment = {
  id: string;
  type: "customer";
  status: ApiCustomerPaymentDetailResponseStatus;
  contactId: string | null;
  contactName: string | null;
  paymentNumber: number | null;
  formattedPaymentNumber: string | null;
  paymentDate: string;
  currency: ApiCustomerPaymentDetailResponseCurrency;
  settlementCurrency?:
    | ApiCustomerPaymentDetailResponseSettlementCurrency
    | null
    | undefined;
  settlementTotalAmount?: number | null | undefined;
  exchangeRate?: string | number | null | undefined;
  totalAmount: number;
  balance: number;
  notes?: string | null | undefined;
  createdAt: Date;
  createdByName: string | null;
  splits?: Array<ApiCustomerPaymentDetailResponseSplit> | undefined;
  applications?: Array<ApiCustomerPaymentDetailResponseApplication> | undefined;
  creditApplications?:
    | Array<ApiCustomerPaymentDetailResponseCreditApplication>
    | undefined;
  journalLineApplications?:
    | Array<ApiCustomerPaymentDetailResponseJournalLineApplication>
    | undefined;
  advanceApplications?:
    | Array<ApiCustomerPaymentDetailResponseAdvanceApplication>
    | undefined;
  withholdings?: Array<ApiCustomerPaymentDetailResponseWithholding> | undefined;
};

export type ApiCustomerPaymentDetailResponseData = {
  customerPayment: ApiCustomerPaymentDetailResponseCustomerPayment;
};

export type ApiCustomerPaymentDetailResponse = {
  requestId: string;
  data: ApiCustomerPaymentDetailResponseData;
};

/** @internal */
export const ApiCustomerPaymentDetailResponseStatus$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseStatus, unknown> = openEnums
    .inboundSchema(ApiCustomerPaymentDetailResponseStatus);

/** @internal */
export const ApiCustomerPaymentDetailResponseCurrency$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseCurrency, unknown> = openEnums
    .inboundSchema(ApiCustomerPaymentDetailResponseCurrency);

/** @internal */
export const ApiCustomerPaymentDetailResponseSettlementCurrency$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseSettlementCurrency, unknown> =
    openEnums.inboundSchema(ApiCustomerPaymentDetailResponseSettlementCurrency);

/** @internal */
export const ApiCustomerPaymentDetailResponseExchangeRate$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseExchangeRate, unknown> =
    smartUnion([types.string(), types.number()]);

export function apiCustomerPaymentDetailResponseExchangeRateFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentDetailResponseExchangeRate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseExchangeRate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentDetailResponseExchangeRate' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseSplit$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentDetailResponseSplit,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    payment_method_id: types.string(),
    payment_method_name: types.optional(types.string()),
    amount: types.number(),
    reference: z.optional(z.nullable(types.string())),
    card_brand: z.optional(z.nullable(types.string())),
    card_batch_number: z.optional(z.nullable(types.string())),
    card_coupon_number: z.optional(z.nullable(types.string())),
    card_installment_plan_code: z.optional(z.nullable(types.string())),
    notes: z.optional(z.nullable(types.string())),
    fee_amount: z.optional(z.nullable(types.number())),
    fee_percentage_applied: z.optional(z.nullable(types.string())),
    fee_fixed_applied: z.optional(z.nullable(types.number())),
    net_amount: z.optional(z.nullable(types.number())),
    check_id: z.optional(z.nullable(types.string())),
    register_id: z.optional(z.nullable(types.string())),
    safe_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_method_id": "paymentMethodId",
      "payment_method_name": "paymentMethodName",
      "card_brand": "cardBrand",
      "card_batch_number": "cardBatchNumber",
      "card_coupon_number": "cardCouponNumber",
      "card_installment_plan_code": "cardInstallmentPlanCode",
      "fee_amount": "feeAmount",
      "fee_percentage_applied": "feePercentageApplied",
      "fee_fixed_applied": "feeFixedApplied",
      "net_amount": "netAmount",
      "check_id": "checkId",
      "register_id": "registerId",
      "safe_id": "safeId",
    });
  }),
);

export function apiCustomerPaymentDetailResponseSplitFromJSON(
  jsonString: string,
): SafeParseResult<ApiCustomerPaymentDetailResponseSplit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseSplit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentDetailResponseSplit' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseApplication$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseApplication, unknown> = z.pipe(
    z.object({
      id: types.optional(types.string()),
      sale_id: types.optional(types.string()),
      invoice_sale_id: z.optional(z.nullable(types.string())),
      credit_sale_id: z.optional(z.nullable(types.string())),
      advance_payment_id: types.optional(types.string()),
      journal_line_id: types.optional(types.string()),
      applied_amount: types.number(),
      formatted_invoice_number: z.optional(z.nullable(types.string())),
      credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
      advance_formatted_payment_number: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "sale_id": "saleId",
        "invoice_sale_id": "invoiceSaleId",
        "credit_sale_id": "creditSaleId",
        "advance_payment_id": "advancePaymentId",
        "journal_line_id": "journalLineId",
        "applied_amount": "appliedAmount",
        "formatted_invoice_number": "formattedInvoiceNumber",
        "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
        "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
      });
    }),
  );

export function apiCustomerPaymentDetailResponseApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentDetailResponseApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentDetailResponseApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseCreditApplication$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseCreditApplication, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        sale_id: types.optional(types.string()),
        invoice_sale_id: z.optional(z.nullable(types.string())),
        credit_sale_id: z.optional(z.nullable(types.string())),
        advance_payment_id: types.optional(types.string()),
        journal_line_id: types.optional(types.string()),
        applied_amount: types.number(),
        formatted_invoice_number: z.optional(z.nullable(types.string())),
        credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
        advance_formatted_payment_number: z.optional(
          z.nullable(types.string()),
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "sale_id": "saleId",
          "invoice_sale_id": "invoiceSaleId",
          "credit_sale_id": "creditSaleId",
          "advance_payment_id": "advancePaymentId",
          "journal_line_id": "journalLineId",
          "applied_amount": "appliedAmount",
          "formatted_invoice_number": "formattedInvoiceNumber",
          "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
          "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
        });
      }),
    );

export function apiCustomerPaymentDetailResponseCreditApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentDetailResponseCreditApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseCreditApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentDetailResponseCreditApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseJournalLineApplication$inboundSchema:
  z.ZodMiniType<
    ApiCustomerPaymentDetailResponseJournalLineApplication,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      sale_id: types.optional(types.string()),
      invoice_sale_id: z.optional(z.nullable(types.string())),
      credit_sale_id: z.optional(z.nullable(types.string())),
      advance_payment_id: types.optional(types.string()),
      journal_line_id: types.optional(types.string()),
      applied_amount: types.number(),
      formatted_invoice_number: z.optional(z.nullable(types.string())),
      credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
      advance_formatted_payment_number: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "sale_id": "saleId",
        "invoice_sale_id": "invoiceSaleId",
        "credit_sale_id": "creditSaleId",
        "advance_payment_id": "advancePaymentId",
        "journal_line_id": "journalLineId",
        "applied_amount": "appliedAmount",
        "formatted_invoice_number": "formattedInvoiceNumber",
        "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
        "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
      });
    }),
  );

export function apiCustomerPaymentDetailResponseJournalLineApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentDetailResponseJournalLineApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseJournalLineApplication$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentDetailResponseJournalLineApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseAdvanceApplication$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseAdvanceApplication, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        sale_id: types.optional(types.string()),
        invoice_sale_id: z.optional(z.nullable(types.string())),
        credit_sale_id: z.optional(z.nullable(types.string())),
        advance_payment_id: types.optional(types.string()),
        journal_line_id: types.optional(types.string()),
        applied_amount: types.number(),
        formatted_invoice_number: z.optional(z.nullable(types.string())),
        credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
        advance_formatted_payment_number: z.optional(
          z.nullable(types.string()),
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "sale_id": "saleId",
          "invoice_sale_id": "invoiceSaleId",
          "credit_sale_id": "creditSaleId",
          "advance_payment_id": "advancePaymentId",
          "journal_line_id": "journalLineId",
          "applied_amount": "appliedAmount",
          "formatted_invoice_number": "formattedInvoiceNumber",
          "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
          "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
        });
      }),
    );

export function apiCustomerPaymentDetailResponseAdvanceApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentDetailResponseAdvanceApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseAdvanceApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentDetailResponseAdvanceApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseType$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentDetailResponseType,
  unknown
> = openEnums.inboundSchema(ApiCustomerPaymentDetailResponseType);

/** @internal */
export const ApiCustomerPaymentDetailResponseWithholding$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseWithholding, unknown> = z.pipe(
    z.object({
      id: types.optional(types.string()),
      type: ApiCustomerPaymentDetailResponseType$inboundSchema,
      province_id: z.optional(z.nullable(types.string())),
      regimen: z.optional(z.nullable(types.string())),
      amount: types.number(),
      rate: z.optional(z.nullable(types.number())),
      calculation_base: z.optional(z.nullable(types.number())),
      certificate_number: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "province_id": "provinceId",
        "calculation_base": "calculationBase",
        "certificate_number": "certificateNumber",
      });
    }),
  );

export function apiCustomerPaymentDetailResponseWithholdingFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentDetailResponseWithholding,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseWithholding$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentDetailResponseWithholding' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseCustomerPayment$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentDetailResponseCustomerPayment, unknown> = z
    .pipe(
      z.object({
        id: types.string(),
        type: types.literal("customer"),
        status: ApiCustomerPaymentDetailResponseStatus$inboundSchema,
        contact_id: types.nullable(types.string()),
        contact_name: types.nullable(types.string()),
        payment_number: types.nullable(types.number()),
        formatted_payment_number: types.nullable(types.string()),
        payment_date: types.string(),
        currency: ApiCustomerPaymentDetailResponseCurrency$inboundSchema,
        settlement_currency: z.optional(
          z.nullable(
            ApiCustomerPaymentDetailResponseSettlementCurrency$inboundSchema,
          ),
        ),
        settlement_total_amount: z.optional(z.nullable(types.number())),
        exchange_rate: z.optional(
          z.nullable(smartUnion([types.string(), types.number()])),
        ),
        total_amount: types.number(),
        balance: types.number(),
        notes: z.optional(z.nullable(types.string())),
        created_at: types.date(),
        created_by_name: types.nullable(types.string()),
        splits: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentDetailResponseSplit$inboundSchema
        ))),
        applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentDetailResponseApplication$inboundSchema
        ))),
        credit_applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentDetailResponseCreditApplication$inboundSchema
        ))),
        journal_line_applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentDetailResponseJournalLineApplication$inboundSchema
        ))),
        advance_applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentDetailResponseAdvanceApplication$inboundSchema
        ))),
        withholdings: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentDetailResponseWithholding$inboundSchema
        ))),
      }),
      z.transform((v) => {
        return remap$(v, {
          "contact_id": "contactId",
          "contact_name": "contactName",
          "payment_number": "paymentNumber",
          "formatted_payment_number": "formattedPaymentNumber",
          "payment_date": "paymentDate",
          "settlement_currency": "settlementCurrency",
          "settlement_total_amount": "settlementTotalAmount",
          "exchange_rate": "exchangeRate",
          "total_amount": "totalAmount",
          "created_at": "createdAt",
          "created_by_name": "createdByName",
          "credit_applications": "creditApplications",
          "journal_line_applications": "journalLineApplications",
          "advance_applications": "advanceApplications",
        });
      }),
    );

export function apiCustomerPaymentDetailResponseCustomerPaymentFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentDetailResponseCustomerPayment,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseCustomerPayment$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentDetailResponseCustomerPayment' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponseData$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentDetailResponseData,
  unknown
> = z.pipe(
  z.object({
    customer_payment: z.lazy(() =>
      ApiCustomerPaymentDetailResponseCustomerPayment$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "customer_payment": "customerPayment",
    });
  }),
);

export function apiCustomerPaymentDetailResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiCustomerPaymentDetailResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentDetailResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentDetailResponseData' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentDetailResponse$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiCustomerPaymentDetailResponseData$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiCustomerPaymentDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiCustomerPaymentDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCustomerPaymentDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentDetailResponse' from JSON`,
  );
}
