/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e8c908ab221
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ApiSupplierPaymentDetailResponseStatus = {
  Active: "active",
  Voided: "voided",
} as const;
export type ApiSupplierPaymentDetailResponseStatus = OpenEnum<
  typeof ApiSupplierPaymentDetailResponseStatus
>;

export const ApiSupplierPaymentDetailResponseCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiSupplierPaymentDetailResponseCurrency = OpenEnum<
  typeof ApiSupplierPaymentDetailResponseCurrency
>;

export const ApiSupplierPaymentDetailResponseSettlementCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiSupplierPaymentDetailResponseSettlementCurrency = OpenEnum<
  typeof ApiSupplierPaymentDetailResponseSettlementCurrency
>;

export type ApiSupplierPaymentDetailResponseExchangeRate = string | number;

export type ApiSupplierPaymentDetailResponseSplit = {
  id?: string | undefined;
  paymentMethodId: string;
  paymentMethodName?: string | undefined;
  amount: number;
  reference?: string | null | undefined;
  cardBrand?: string | null | undefined;
  cardBatchNumber?: string | null | undefined;
  cardCouponNumber?: string | null | undefined;
  cardInstallmentPlanCode?: string | null | undefined;
  notes?: string | null | undefined;
  feeAmount?: number | null | undefined;
  feePercentageApplied?: string | null | undefined;
  feeFixedApplied?: number | null | undefined;
  netAmount?: number | null | undefined;
  checkId?: string | null | undefined;
  registerId?: string | null | undefined;
  safeId?: string | null | undefined;
};

export type ApiSupplierPaymentDetailResponseApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiSupplierPaymentDetailResponseCreditApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiSupplierPaymentDetailResponseJournalLineApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiSupplierPaymentDetailResponseAdvanceApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export const ApiSupplierPaymentDetailResponseType = {
  Ganancias: "ganancias",
  Iibb: "iibb",
  Iva: "iva",
  Suss: "suss",
  SegHig: "seg_hig",
} as const;
export type ApiSupplierPaymentDetailResponseType = OpenEnum<
  typeof ApiSupplierPaymentDetailResponseType
>;

export type ApiSupplierPaymentDetailResponseWithholding = {
  id?: string | undefined;
  type: ApiSupplierPaymentDetailResponseType;
  provinceId?: string | null | undefined;
  regimen?: string | null | undefined;
  amount: number;
  rate?: number | null | undefined;
  calculationBase?: number | null | undefined;
  certificateNumber: string;
};

export type ApiSupplierPaymentDetailResponseSupplierPayment = {
  id: string;
  type: "supplier";
  status: ApiSupplierPaymentDetailResponseStatus;
  contactId: string | null;
  contactName: string | null;
  paymentNumber: number | null;
  formattedPaymentNumber: string | null;
  paymentDate: string;
  currency: ApiSupplierPaymentDetailResponseCurrency;
  settlementCurrency?:
    | ApiSupplierPaymentDetailResponseSettlementCurrency
    | null
    | undefined;
  settlementTotalAmount?: number | null | undefined;
  exchangeRate?: string | number | null | undefined;
  totalAmount: number;
  balance: number;
  notes?: string | null | undefined;
  createdAt: Date;
  createdByName: string | null;
  splits?: Array<ApiSupplierPaymentDetailResponseSplit> | undefined;
  applications?: Array<ApiSupplierPaymentDetailResponseApplication> | undefined;
  creditApplications?:
    | Array<ApiSupplierPaymentDetailResponseCreditApplication>
    | undefined;
  journalLineApplications?:
    | Array<ApiSupplierPaymentDetailResponseJournalLineApplication>
    | undefined;
  advanceApplications?:
    | Array<ApiSupplierPaymentDetailResponseAdvanceApplication>
    | undefined;
  withholdings?: Array<ApiSupplierPaymentDetailResponseWithholding> | undefined;
};

export type ApiSupplierPaymentDetailResponseData = {
  supplierPayment: ApiSupplierPaymentDetailResponseSupplierPayment;
};

export type ApiSupplierPaymentDetailResponse = {
  requestId: string;
  data: ApiSupplierPaymentDetailResponseData;
};

/** @internal */
export const ApiSupplierPaymentDetailResponseStatus$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseStatus, unknown> = openEnums
    .inboundSchema(ApiSupplierPaymentDetailResponseStatus);

/** @internal */
export const ApiSupplierPaymentDetailResponseCurrency$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseCurrency, unknown> = openEnums
    .inboundSchema(ApiSupplierPaymentDetailResponseCurrency);

/** @internal */
export const ApiSupplierPaymentDetailResponseSettlementCurrency$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseSettlementCurrency, unknown> =
    openEnums.inboundSchema(ApiSupplierPaymentDetailResponseSettlementCurrency);

/** @internal */
export const ApiSupplierPaymentDetailResponseExchangeRate$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseExchangeRate, unknown> =
    smartUnion([types.string(), types.number()]);

export function apiSupplierPaymentDetailResponseExchangeRateFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentDetailResponseExchangeRate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseExchangeRate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentDetailResponseExchangeRate' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseSplit$inboundSchema: z.ZodMiniType<
  ApiSupplierPaymentDetailResponseSplit,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    payment_method_id: types.string(),
    payment_method_name: types.optional(types.string()),
    amount: types.number(),
    reference: z.optional(z.nullable(types.string())),
    card_brand: z.optional(z.nullable(types.string())),
    card_batch_number: z.optional(z.nullable(types.string())),
    card_coupon_number: z.optional(z.nullable(types.string())),
    card_installment_plan_code: z.optional(z.nullable(types.string())),
    notes: z.optional(z.nullable(types.string())),
    fee_amount: z.optional(z.nullable(types.number())),
    fee_percentage_applied: z.optional(z.nullable(types.string())),
    fee_fixed_applied: z.optional(z.nullable(types.number())),
    net_amount: z.optional(z.nullable(types.number())),
    check_id: z.optional(z.nullable(types.string())),
    register_id: z.optional(z.nullable(types.string())),
    safe_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_method_id": "paymentMethodId",
      "payment_method_name": "paymentMethodName",
      "card_brand": "cardBrand",
      "card_batch_number": "cardBatchNumber",
      "card_coupon_number": "cardCouponNumber",
      "card_installment_plan_code": "cardInstallmentPlanCode",
      "fee_amount": "feeAmount",
      "fee_percentage_applied": "feePercentageApplied",
      "fee_fixed_applied": "feeFixedApplied",
      "net_amount": "netAmount",
      "check_id": "checkId",
      "register_id": "registerId",
      "safe_id": "safeId",
    });
  }),
);

export function apiSupplierPaymentDetailResponseSplitFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierPaymentDetailResponseSplit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseSplit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierPaymentDetailResponseSplit' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseApplication$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseApplication, unknown> = z.pipe(
    z.object({
      id: types.optional(types.string()),
      sale_id: types.optional(types.string()),
      invoice_sale_id: z.optional(z.nullable(types.string())),
      credit_sale_id: z.optional(z.nullable(types.string())),
      advance_payment_id: types.optional(types.string()),
      journal_line_id: types.optional(types.string()),
      applied_amount: types.number(),
      formatted_invoice_number: z.optional(z.nullable(types.string())),
      credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
      advance_formatted_payment_number: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "sale_id": "saleId",
        "invoice_sale_id": "invoiceSaleId",
        "credit_sale_id": "creditSaleId",
        "advance_payment_id": "advancePaymentId",
        "journal_line_id": "journalLineId",
        "applied_amount": "appliedAmount",
        "formatted_invoice_number": "formattedInvoiceNumber",
        "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
        "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
      });
    }),
  );

export function apiSupplierPaymentDetailResponseApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentDetailResponseApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentDetailResponseApplication' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseCreditApplication$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseCreditApplication, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        sale_id: types.optional(types.string()),
        invoice_sale_id: z.optional(z.nullable(types.string())),
        credit_sale_id: z.optional(z.nullable(types.string())),
        advance_payment_id: types.optional(types.string()),
        journal_line_id: types.optional(types.string()),
        applied_amount: types.number(),
        formatted_invoice_number: z.optional(z.nullable(types.string())),
        credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
        advance_formatted_payment_number: z.optional(
          z.nullable(types.string()),
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "sale_id": "saleId",
          "invoice_sale_id": "invoiceSaleId",
          "credit_sale_id": "creditSaleId",
          "advance_payment_id": "advancePaymentId",
          "journal_line_id": "journalLineId",
          "applied_amount": "appliedAmount",
          "formatted_invoice_number": "formattedInvoiceNumber",
          "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
          "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
        });
      }),
    );

export function apiSupplierPaymentDetailResponseCreditApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentDetailResponseCreditApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseCreditApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentDetailResponseCreditApplication' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseJournalLineApplication$inboundSchema:
  z.ZodMiniType<
    ApiSupplierPaymentDetailResponseJournalLineApplication,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      sale_id: types.optional(types.string()),
      invoice_sale_id: z.optional(z.nullable(types.string())),
      credit_sale_id: z.optional(z.nullable(types.string())),
      advance_payment_id: types.optional(types.string()),
      journal_line_id: types.optional(types.string()),
      applied_amount: types.number(),
      formatted_invoice_number: z.optional(z.nullable(types.string())),
      credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
      advance_formatted_payment_number: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "sale_id": "saleId",
        "invoice_sale_id": "invoiceSaleId",
        "credit_sale_id": "creditSaleId",
        "advance_payment_id": "advancePaymentId",
        "journal_line_id": "journalLineId",
        "applied_amount": "appliedAmount",
        "formatted_invoice_number": "formattedInvoiceNumber",
        "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
        "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
      });
    }),
  );

export function apiSupplierPaymentDetailResponseJournalLineApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentDetailResponseJournalLineApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseJournalLineApplication$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierPaymentDetailResponseJournalLineApplication' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseAdvanceApplication$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseAdvanceApplication, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        sale_id: types.optional(types.string()),
        invoice_sale_id: z.optional(z.nullable(types.string())),
        credit_sale_id: z.optional(z.nullable(types.string())),
        advance_payment_id: types.optional(types.string()),
        journal_line_id: types.optional(types.string()),
        applied_amount: types.number(),
        formatted_invoice_number: z.optional(z.nullable(types.string())),
        credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
        advance_formatted_payment_number: z.optional(
          z.nullable(types.string()),
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "sale_id": "saleId",
          "invoice_sale_id": "invoiceSaleId",
          "credit_sale_id": "creditSaleId",
          "advance_payment_id": "advancePaymentId",
          "journal_line_id": "journalLineId",
          "applied_amount": "appliedAmount",
          "formatted_invoice_number": "formattedInvoiceNumber",
          "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
          "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
        });
      }),
    );

export function apiSupplierPaymentDetailResponseAdvanceApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentDetailResponseAdvanceApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseAdvanceApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentDetailResponseAdvanceApplication' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseType$inboundSchema: z.ZodMiniType<
  ApiSupplierPaymentDetailResponseType,
  unknown
> = openEnums.inboundSchema(ApiSupplierPaymentDetailResponseType);

/** @internal */
export const ApiSupplierPaymentDetailResponseWithholding$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseWithholding, unknown> = z.pipe(
    z.object({
      id: types.optional(types.string()),
      type: ApiSupplierPaymentDetailResponseType$inboundSchema,
      province_id: z.optional(z.nullable(types.string())),
      regimen: z.optional(z.nullable(types.string())),
      amount: types.number(),
      rate: z.optional(z.nullable(types.number())),
      calculation_base: z.optional(z.nullable(types.number())),
      certificate_number: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "province_id": "provinceId",
        "calculation_base": "calculationBase",
        "certificate_number": "certificateNumber",
      });
    }),
  );

export function apiSupplierPaymentDetailResponseWithholdingFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentDetailResponseWithholding,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseWithholding$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentDetailResponseWithholding' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseSupplierPayment$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentDetailResponseSupplierPayment, unknown> = z
    .pipe(
      z.object({
        id: types.string(),
        type: types.literal("supplier"),
        status: ApiSupplierPaymentDetailResponseStatus$inboundSchema,
        contact_id: types.nullable(types.string()),
        contact_name: types.nullable(types.string()),
        payment_number: types.nullable(types.number()),
        formatted_payment_number: types.nullable(types.string()),
        payment_date: types.string(),
        currency: ApiSupplierPaymentDetailResponseCurrency$inboundSchema,
        settlement_currency: z.optional(
          z.nullable(
            ApiSupplierPaymentDetailResponseSettlementCurrency$inboundSchema,
          ),
        ),
        settlement_total_amount: z.optional(z.nullable(types.number())),
        exchange_rate: z.optional(
          z.nullable(smartUnion([types.string(), types.number()])),
        ),
        total_amount: types.number(),
        balance: types.number(),
        notes: z.optional(z.nullable(types.string())),
        created_at: types.date(),
        created_by_name: types.nullable(types.string()),
        splits: types.optional(z.array(z.lazy(() =>
          ApiSupplierPaymentDetailResponseSplit$inboundSchema
        ))),
        applications: types.optional(z.array(z.lazy(() =>
          ApiSupplierPaymentDetailResponseApplication$inboundSchema
        ))),
        credit_applications: types.optional(z.array(z.lazy(() =>
          ApiSupplierPaymentDetailResponseCreditApplication$inboundSchema
        ))),
        journal_line_applications: types.optional(z.array(z.lazy(() =>
          ApiSupplierPaymentDetailResponseJournalLineApplication$inboundSchema
        ))),
        advance_applications: types.optional(z.array(z.lazy(() =>
          ApiSupplierPaymentDetailResponseAdvanceApplication$inboundSchema
        ))),
        withholdings: types.optional(z.array(z.lazy(() =>
          ApiSupplierPaymentDetailResponseWithholding$inboundSchema
        ))),
      }),
      z.transform((v) => {
        return remap$(v, {
          "contact_id": "contactId",
          "contact_name": "contactName",
          "payment_number": "paymentNumber",
          "formatted_payment_number": "formattedPaymentNumber",
          "payment_date": "paymentDate",
          "settlement_currency": "settlementCurrency",
          "settlement_total_amount": "settlementTotalAmount",
          "exchange_rate": "exchangeRate",
          "total_amount": "totalAmount",
          "created_at": "createdAt",
          "created_by_name": "createdByName",
          "credit_applications": "creditApplications",
          "journal_line_applications": "journalLineApplications",
          "advance_applications": "advanceApplications",
        });
      }),
    );

export function apiSupplierPaymentDetailResponseSupplierPaymentFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentDetailResponseSupplierPayment,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseSupplierPayment$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentDetailResponseSupplierPayment' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponseData$inboundSchema: z.ZodMiniType<
  ApiSupplierPaymentDetailResponseData,
  unknown
> = z.pipe(
  z.object({
    supplier_payment: z.lazy(() =>
      ApiSupplierPaymentDetailResponseSupplierPayment$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "supplier_payment": "supplierPayment",
    });
  }),
);

export function apiSupplierPaymentDetailResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierPaymentDetailResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentDetailResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierPaymentDetailResponseData' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentDetailResponse$inboundSchema: z.ZodMiniType<
  ApiSupplierPaymentDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiSupplierPaymentDetailResponseData$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiSupplierPaymentDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierPaymentDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSupplierPaymentDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierPaymentDetailResponse' from JSON`,
  );
}
