/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 568e188b28cf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiCategoryCreateResponseCategory = {
  object: "category";
  id: string;
  name: string;
  parentId: string | null;
  defaultEconomicActivity: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type ApiCategoryCreateResponseData = {
  category: ApiCategoryCreateResponseCategory;
  idempotentReplay: boolean;
};

export type ApiCategoryCreateResponse = {
  requestId: string;
  data: ApiCategoryCreateResponseData;
  warnings: Array<any>;
};

/** @internal */
export const ApiCategoryCreateResponseCategory$inboundSchema: z.ZodMiniType<
  ApiCategoryCreateResponseCategory,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("category"),
    id: types.string(),
    name: types.string(),
    parent_id: types.nullable(types.string()),
    default_economic_activity: types.nullable(types.string()),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "parent_id": "parentId",
      "default_economic_activity": "defaultEconomicActivity",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function apiCategoryCreateResponseCategoryFromJSON(
  jsonString: string,
): SafeParseResult<ApiCategoryCreateResponseCategory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCategoryCreateResponseCategory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCategoryCreateResponseCategory' from JSON`,
  );
}

/** @internal */
export const ApiCategoryCreateResponseData$inboundSchema: z.ZodMiniType<
  ApiCategoryCreateResponseData,
  unknown
> = z.pipe(
  z.object({
    category: z.lazy(() => ApiCategoryCreateResponseCategory$inboundSchema),
    idempotent_replay: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "idempotent_replay": "idempotentReplay",
    });
  }),
);

export function apiCategoryCreateResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiCategoryCreateResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCategoryCreateResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCategoryCreateResponseData' from JSON`,
  );
}

/** @internal */
export const ApiCategoryCreateResponse$inboundSchema: z.ZodMiniType<
  ApiCategoryCreateResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiCategoryCreateResponseData$inboundSchema),
    warnings: z.array(z.any()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiCategoryCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiCategoryCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCategoryCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCategoryCreateResponse' from JSON`,
  );
}
