/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 541cad18514a
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnuma6084829bf = {
  Revenue: "revenue",
  Cogs: "cogs",
  OperatingExpense: "operating_expense",
  DepreciationAmortization: "depreciation_amortization",
  OtherOperatingIncome: "other_operating_income",
  OtherOperatingExpense: "other_operating_expense",
  FinancialIncome: "financial_income",
  FinancialExpense: "financial_expense",
  IncomeTax: "income_tax",
} as const;
export type ApiSharedEnuma6084829bf = OpenEnum<typeof ApiSharedEnuma6084829bf>;

/** @internal */
export const ApiSharedEnuma6084829bf$inboundSchema: z.ZodMiniType<
  ApiSharedEnuma6084829bf,
  unknown
> = openEnums.inboundSchema(ApiSharedEnuma6084829bf);
/** @internal */
export const ApiSharedEnuma6084829bf$outboundSchema: z.ZodMiniType<
  string,
  ApiSharedEnuma6084829bf
> = openEnums.outboundSchema(ApiSharedEnuma6084829bf);
