/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e5c082dfb610
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject0a16670526,
  ApiSharedObject0a16670526$inboundSchema,
} from "./api-shared-object0a16670526.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject912052d04a = {
  id: string;
  saleItemId: string | null;
  quantity: number;
  name: string | null;
  isCustom: boolean;
  warehouseId: string | null;
  product: ApiSharedObject0a16670526 | null;
};

/** @internal */
export const ApiSharedObject912052d04a$inboundSchema: z.ZodMiniType<
  ApiSharedObject912052d04a,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    sale_item_id: types.nullable(types.string()),
    quantity: types.number(),
    name: types.nullable(types.string()),
    is_custom: types.boolean(),
    warehouse_id: types.nullable(types.string()),
    product: types.nullable(ApiSharedObject0a16670526$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "sale_item_id": "saleItemId",
      "is_custom": "isCustom",
      "warehouse_id": "warehouseId",
    });
  }),
);

export function apiSharedObject912052d04aFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject912052d04a, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject912052d04a$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject912052d04a' from JSON`,
  );
}
