/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3748d52cdc7e
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjecta3133edce3 = {
  id: number;
  value: number;
};

/** @internal */
export const ApiSharedObjecta3133edce3$inboundSchema: z.ZodMiniType<
  ApiSharedObjecta3133edce3,
  unknown
> = z.object({
  id: types.number(),
  value: types.number(),
});

export function apiSharedObjecta3133edce3FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjecta3133edce3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjecta3133edce3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjecta3133edce3' from JSON`,
  );
}
