/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 44f230582b84
 */

import * as z from "zod/v4-mini";

export type ApiOrderOptionalReasonRequest = {
  reason?: string | undefined;
};

/** @internal */
export type ApiOrderOptionalReasonRequest$Outbound = {
  reason?: string | undefined;
};

/** @internal */
export const ApiOrderOptionalReasonRequest$outboundSchema: z.ZodMiniType<
  ApiOrderOptionalReasonRequest$Outbound,
  ApiOrderOptionalReasonRequest
> = z.object({
  reason: z.optional(z.string()),
});

export function apiOrderOptionalReasonRequestToJSON(
  apiOrderOptionalReasonRequest: ApiOrderOptionalReasonRequest,
): string {
  return JSON.stringify(
    ApiOrderOptionalReasonRequest$outboundSchema.parse(
      apiOrderOptionalReasonRequest,
    ),
  );
}
