/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bf973155efb2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum8d46e1ec20,
  ApiSharedEnum8d46e1ec20$inboundSchema,
} from "./api-shared-enum8d46e1ec20.js";
import {
  ApiSharedObject799d3e3f37,
  ApiSharedObject799d3e3f37$inboundSchema,
} from "./api-shared-object799d3e3f37.js";
import {
  ApiSharedObject8a94344083,
  ApiSharedObject8a94344083$inboundSchema,
} from "./api-shared-object8a94344083.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSaleListResponseData = {
  object?: "sale" | undefined;
  id?: string | undefined;
  invoicePdf?: string | null | undefined;
  accounting?: ApiSharedObject799d3e3f37 | undefined;
  document?: { [k: string]: any } | undefined;
  customer?: { [k: string]: any } | null | undefined;
  amounts?: { [k: string]: any } | undefined;
  items?: Array<{ [k: string]: any }> | undefined;
  payments?: { [k: string]: any } | undefined;
  applications?: { [k: string]: any } | undefined;
  fiscal?: { [k: string]: any } | undefined;
  integration?: { [k: string]: any } | undefined;
  reversesVoucher?: { [k: string]: any } | null | undefined;
  audit?: { [k: string]: any } | undefined;
  tags?: Array<ApiSharedObject8a94344083> | undefined;
  [additionalProperties: string]: unknown;
};

export type ApiSaleListResponse = {
  requestId: string;
  data: Array<ApiSaleListResponseData>;
  hasMore: boolean;
  nextCursor: string | null;
  /**
   * List-envelope discriminator.
   */
  object: ApiSharedEnum8d46e1ec20;
  /**
   * Requested list path.
   */
  url: string;
};

/** @internal */
export const ApiSaleListResponseData$inboundSchema: z.ZodMiniType<
  ApiSaleListResponseData,
  unknown
> = z.pipe(
  z.catchall(
    z.object({
      object: types.optional(types.literal("sale")),
      id: types.optional(types.string()),
      invoice_pdf: z.optional(z.nullable(types.string())),
      accounting: types.optional(ApiSharedObject799d3e3f37$inboundSchema),
      document: types.optional(z.record(z.string(), z.any())),
      customer: z.optional(z.nullable(z.record(z.string(), z.any()))),
      amounts: types.optional(z.record(z.string(), z.any())),
      items: types.optional(z.array(z.record(z.string(), z.any()))),
      payments: types.optional(z.record(z.string(), z.any())),
      applications: types.optional(z.record(z.string(), z.any())),
      fiscal: types.optional(z.record(z.string(), z.any())),
      integration: types.optional(z.record(z.string(), z.any())),
      reverses_voucher: z.optional(z.nullable(z.record(z.string(), z.any()))),
      audit: types.optional(z.record(z.string(), z.any())),
      tags: types.optional(z.array(ApiSharedObject8a94344083$inboundSchema)),
    }),
    z.any(),
  ),
  z.transform((v) => {
    return remap$(v, {
      "invoice_pdf": "invoicePdf",
      "reverses_voucher": "reversesVoucher",
    });
  }),
);

export function apiSaleListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiSaleListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSaleListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSaleListResponseData' from JSON`,
  );
}

/** @internal */
export const ApiSaleListResponse$inboundSchema: z.ZodMiniType<
  ApiSaleListResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.array(z.lazy(() => ApiSaleListResponseData$inboundSchema)),
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    object: ApiSharedEnum8d46e1ec20$inboundSchema,
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function apiSaleListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiSaleListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSaleListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSaleListResponse' from JSON`,
  );
}
