/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f3c907c2e4f6
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnumde48b709b2 = {
  None: "none",
  Receive: "receive",
  ReturnToSupplier: "return_to_supplier",
} as const;
export type ApiSharedEnumde48b709b2 = OpenEnum<typeof ApiSharedEnumde48b709b2>;

/** @internal */
export const ApiSharedEnumde48b709b2$inboundSchema: z.ZodMiniType<
  ApiSharedEnumde48b709b2,
  unknown
> = openEnums.inboundSchema(ApiSharedEnumde48b709b2);
