/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a33cd50cf677
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ApiCustomerPaymentCreateResponseStatus = {
  Active: "active",
  Voided: "voided",
} as const;
export type ApiCustomerPaymentCreateResponseStatus = OpenEnum<
  typeof ApiCustomerPaymentCreateResponseStatus
>;

export const ApiCustomerPaymentCreateResponseCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiCustomerPaymentCreateResponseCurrency = OpenEnum<
  typeof ApiCustomerPaymentCreateResponseCurrency
>;

export const ApiCustomerPaymentCreateResponseSettlementCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiCustomerPaymentCreateResponseSettlementCurrency = OpenEnum<
  typeof ApiCustomerPaymentCreateResponseSettlementCurrency
>;

export type ApiCustomerPaymentCreateResponseExchangeRate = string | number;

export type ApiCustomerPaymentCreateResponseSplit = {
  id?: string | undefined;
  paymentMethodId: string;
  paymentMethodName?: string | undefined;
  amount: number;
  reference?: string | null | undefined;
  cardBrand?: string | null | undefined;
  cardBatchNumber?: string | null | undefined;
  cardCouponNumber?: string | null | undefined;
  cardInstallmentPlanCode?: string | null | undefined;
  notes?: string | null | undefined;
  feeAmount?: number | null | undefined;
  feePercentageApplied?: string | null | undefined;
  feeFixedApplied?: number | null | undefined;
  netAmount?: number | null | undefined;
  checkId?: string | null | undefined;
  registerId?: string | null | undefined;
  safeId?: string | null | undefined;
};

export type ApiCustomerPaymentCreateResponseApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiCustomerPaymentCreateResponseCreditApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiCustomerPaymentCreateResponseJournalLineApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export type ApiCustomerPaymentCreateResponseAdvanceApplication = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

export const ApiCustomerPaymentCreateResponseType = {
  Ganancias: "ganancias",
  Iibb: "iibb",
  Iva: "iva",
  Suss: "suss",
  SegHig: "seg_hig",
} as const;
export type ApiCustomerPaymentCreateResponseType = OpenEnum<
  typeof ApiCustomerPaymentCreateResponseType
>;

export type ApiCustomerPaymentCreateResponseWithholding = {
  id?: string | undefined;
  type: ApiCustomerPaymentCreateResponseType;
  provinceId?: string | null | undefined;
  regimen?: string | null | undefined;
  amount: number;
  rate?: number | null | undefined;
  calculationBase?: number | null | undefined;
  certificateNumber: string;
};

export type ApiCustomerPaymentCreateResponseCustomerPayment = {
  id: string;
  type: "customer";
  status: ApiCustomerPaymentCreateResponseStatus;
  contactId: string | null;
  contactName: string | null;
  paymentNumber: number | null;
  formattedPaymentNumber: string | null;
  paymentDate: string;
  currency: ApiCustomerPaymentCreateResponseCurrency;
  settlementCurrency?:
    | ApiCustomerPaymentCreateResponseSettlementCurrency
    | null
    | undefined;
  settlementTotalAmount?: number | null | undefined;
  exchangeRate?: string | number | null | undefined;
  totalAmount: number;
  balance: number;
  notes?: string | null | undefined;
  createdAt: Date;
  createdByName: string | null;
  splits?: Array<ApiCustomerPaymentCreateResponseSplit> | undefined;
  applications?: Array<ApiCustomerPaymentCreateResponseApplication> | undefined;
  creditApplications?:
    | Array<ApiCustomerPaymentCreateResponseCreditApplication>
    | undefined;
  journalLineApplications?:
    | Array<ApiCustomerPaymentCreateResponseJournalLineApplication>
    | undefined;
  advanceApplications?:
    | Array<ApiCustomerPaymentCreateResponseAdvanceApplication>
    | undefined;
  withholdings?: Array<ApiCustomerPaymentCreateResponseWithholding> | undefined;
};

export type ApiCustomerPaymentCreateResponseData = {
  customerPayment: ApiCustomerPaymentCreateResponseCustomerPayment;
  idempotentReplay: boolean;
};

export type ApiCustomerPaymentCreateResponse = {
  requestId: string;
  data: ApiCustomerPaymentCreateResponseData;
  warnings: Array<any>;
};

/** @internal */
export const ApiCustomerPaymentCreateResponseStatus$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseStatus, unknown> = openEnums
    .inboundSchema(ApiCustomerPaymentCreateResponseStatus);

/** @internal */
export const ApiCustomerPaymentCreateResponseCurrency$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseCurrency, unknown> = openEnums
    .inboundSchema(ApiCustomerPaymentCreateResponseCurrency);

/** @internal */
export const ApiCustomerPaymentCreateResponseSettlementCurrency$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseSettlementCurrency, unknown> =
    openEnums.inboundSchema(ApiCustomerPaymentCreateResponseSettlementCurrency);

/** @internal */
export const ApiCustomerPaymentCreateResponseExchangeRate$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseExchangeRate, unknown> =
    smartUnion([types.string(), types.number()]);

export function apiCustomerPaymentCreateResponseExchangeRateFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentCreateResponseExchangeRate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseExchangeRate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentCreateResponseExchangeRate' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseSplit$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentCreateResponseSplit,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    payment_method_id: types.string(),
    payment_method_name: types.optional(types.string()),
    amount: types.number(),
    reference: z.optional(z.nullable(types.string())),
    card_brand: z.optional(z.nullable(types.string())),
    card_batch_number: z.optional(z.nullable(types.string())),
    card_coupon_number: z.optional(z.nullable(types.string())),
    card_installment_plan_code: z.optional(z.nullable(types.string())),
    notes: z.optional(z.nullable(types.string())),
    fee_amount: z.optional(z.nullable(types.number())),
    fee_percentage_applied: z.optional(z.nullable(types.string())),
    fee_fixed_applied: z.optional(z.nullable(types.number())),
    net_amount: z.optional(z.nullable(types.number())),
    check_id: z.optional(z.nullable(types.string())),
    register_id: z.optional(z.nullable(types.string())),
    safe_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_method_id": "paymentMethodId",
      "payment_method_name": "paymentMethodName",
      "card_brand": "cardBrand",
      "card_batch_number": "cardBatchNumber",
      "card_coupon_number": "cardCouponNumber",
      "card_installment_plan_code": "cardInstallmentPlanCode",
      "fee_amount": "feeAmount",
      "fee_percentage_applied": "feePercentageApplied",
      "fee_fixed_applied": "feeFixedApplied",
      "net_amount": "netAmount",
      "check_id": "checkId",
      "register_id": "registerId",
      "safe_id": "safeId",
    });
  }),
);

export function apiCustomerPaymentCreateResponseSplitFromJSON(
  jsonString: string,
): SafeParseResult<ApiCustomerPaymentCreateResponseSplit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseSplit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentCreateResponseSplit' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseApplication$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseApplication, unknown> = z.pipe(
    z.object({
      id: types.optional(types.string()),
      sale_id: types.optional(types.string()),
      invoice_sale_id: z.optional(z.nullable(types.string())),
      credit_sale_id: z.optional(z.nullable(types.string())),
      advance_payment_id: types.optional(types.string()),
      journal_line_id: types.optional(types.string()),
      applied_amount: types.number(),
      formatted_invoice_number: z.optional(z.nullable(types.string())),
      credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
      advance_formatted_payment_number: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "sale_id": "saleId",
        "invoice_sale_id": "invoiceSaleId",
        "credit_sale_id": "creditSaleId",
        "advance_payment_id": "advancePaymentId",
        "journal_line_id": "journalLineId",
        "applied_amount": "appliedAmount",
        "formatted_invoice_number": "formattedInvoiceNumber",
        "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
        "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
      });
    }),
  );

export function apiCustomerPaymentCreateResponseApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentCreateResponseApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentCreateResponseApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseCreditApplication$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseCreditApplication, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        sale_id: types.optional(types.string()),
        invoice_sale_id: z.optional(z.nullable(types.string())),
        credit_sale_id: z.optional(z.nullable(types.string())),
        advance_payment_id: types.optional(types.string()),
        journal_line_id: types.optional(types.string()),
        applied_amount: types.number(),
        formatted_invoice_number: z.optional(z.nullable(types.string())),
        credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
        advance_formatted_payment_number: z.optional(
          z.nullable(types.string()),
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "sale_id": "saleId",
          "invoice_sale_id": "invoiceSaleId",
          "credit_sale_id": "creditSaleId",
          "advance_payment_id": "advancePaymentId",
          "journal_line_id": "journalLineId",
          "applied_amount": "appliedAmount",
          "formatted_invoice_number": "formattedInvoiceNumber",
          "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
          "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
        });
      }),
    );

export function apiCustomerPaymentCreateResponseCreditApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentCreateResponseCreditApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseCreditApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentCreateResponseCreditApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseJournalLineApplication$inboundSchema:
  z.ZodMiniType<
    ApiCustomerPaymentCreateResponseJournalLineApplication,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      sale_id: types.optional(types.string()),
      invoice_sale_id: z.optional(z.nullable(types.string())),
      credit_sale_id: z.optional(z.nullable(types.string())),
      advance_payment_id: types.optional(types.string()),
      journal_line_id: types.optional(types.string()),
      applied_amount: types.number(),
      formatted_invoice_number: z.optional(z.nullable(types.string())),
      credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
      advance_formatted_payment_number: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "sale_id": "saleId",
        "invoice_sale_id": "invoiceSaleId",
        "credit_sale_id": "creditSaleId",
        "advance_payment_id": "advancePaymentId",
        "journal_line_id": "journalLineId",
        "applied_amount": "appliedAmount",
        "formatted_invoice_number": "formattedInvoiceNumber",
        "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
        "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
      });
    }),
  );

export function apiCustomerPaymentCreateResponseJournalLineApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentCreateResponseJournalLineApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseJournalLineApplication$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentCreateResponseJournalLineApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseAdvanceApplication$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseAdvanceApplication, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        sale_id: types.optional(types.string()),
        invoice_sale_id: z.optional(z.nullable(types.string())),
        credit_sale_id: z.optional(z.nullable(types.string())),
        advance_payment_id: types.optional(types.string()),
        journal_line_id: types.optional(types.string()),
        applied_amount: types.number(),
        formatted_invoice_number: z.optional(z.nullable(types.string())),
        credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
        advance_formatted_payment_number: z.optional(
          z.nullable(types.string()),
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "sale_id": "saleId",
          "invoice_sale_id": "invoiceSaleId",
          "credit_sale_id": "creditSaleId",
          "advance_payment_id": "advancePaymentId",
          "journal_line_id": "journalLineId",
          "applied_amount": "appliedAmount",
          "formatted_invoice_number": "formattedInvoiceNumber",
          "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
          "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
        });
      }),
    );

export function apiCustomerPaymentCreateResponseAdvanceApplicationFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentCreateResponseAdvanceApplication,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseAdvanceApplication$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentCreateResponseAdvanceApplication' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseType$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentCreateResponseType,
  unknown
> = openEnums.inboundSchema(ApiCustomerPaymentCreateResponseType);

/** @internal */
export const ApiCustomerPaymentCreateResponseWithholding$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseWithholding, unknown> = z.pipe(
    z.object({
      id: types.optional(types.string()),
      type: ApiCustomerPaymentCreateResponseType$inboundSchema,
      province_id: z.optional(z.nullable(types.string())),
      regimen: z.optional(z.nullable(types.string())),
      amount: types.number(),
      rate: z.optional(z.nullable(types.number())),
      calculation_base: z.optional(z.nullable(types.number())),
      certificate_number: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "province_id": "provinceId",
        "calculation_base": "calculationBase",
        "certificate_number": "certificateNumber",
      });
    }),
  );

export function apiCustomerPaymentCreateResponseWithholdingFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentCreateResponseWithholding,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseWithholding$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentCreateResponseWithholding' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseCustomerPayment$inboundSchema:
  z.ZodMiniType<ApiCustomerPaymentCreateResponseCustomerPayment, unknown> = z
    .pipe(
      z.object({
        id: types.string(),
        type: types.literal("customer"),
        status: ApiCustomerPaymentCreateResponseStatus$inboundSchema,
        contact_id: types.nullable(types.string()),
        contact_name: types.nullable(types.string()),
        payment_number: types.nullable(types.number()),
        formatted_payment_number: types.nullable(types.string()),
        payment_date: types.string(),
        currency: ApiCustomerPaymentCreateResponseCurrency$inboundSchema,
        settlement_currency: z.optional(
          z.nullable(
            ApiCustomerPaymentCreateResponseSettlementCurrency$inboundSchema,
          ),
        ),
        settlement_total_amount: z.optional(z.nullable(types.number())),
        exchange_rate: z.optional(
          z.nullable(smartUnion([types.string(), types.number()])),
        ),
        total_amount: types.number(),
        balance: types.number(),
        notes: z.optional(z.nullable(types.string())),
        created_at: types.date(),
        created_by_name: types.nullable(types.string()),
        splits: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentCreateResponseSplit$inboundSchema
        ))),
        applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentCreateResponseApplication$inboundSchema
        ))),
        credit_applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentCreateResponseCreditApplication$inboundSchema
        ))),
        journal_line_applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentCreateResponseJournalLineApplication$inboundSchema
        ))),
        advance_applications: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentCreateResponseAdvanceApplication$inboundSchema
        ))),
        withholdings: types.optional(z.array(z.lazy(() =>
          ApiCustomerPaymentCreateResponseWithholding$inboundSchema
        ))),
      }),
      z.transform((v) => {
        return remap$(v, {
          "contact_id": "contactId",
          "contact_name": "contactName",
          "payment_number": "paymentNumber",
          "formatted_payment_number": "formattedPaymentNumber",
          "payment_date": "paymentDate",
          "settlement_currency": "settlementCurrency",
          "settlement_total_amount": "settlementTotalAmount",
          "exchange_rate": "exchangeRate",
          "total_amount": "totalAmount",
          "created_at": "createdAt",
          "created_by_name": "createdByName",
          "credit_applications": "creditApplications",
          "journal_line_applications": "journalLineApplications",
          "advance_applications": "advanceApplications",
        });
      }),
    );

export function apiCustomerPaymentCreateResponseCustomerPaymentFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiCustomerPaymentCreateResponseCustomerPayment,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseCustomerPayment$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiCustomerPaymentCreateResponseCustomerPayment' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponseData$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentCreateResponseData,
  unknown
> = z.pipe(
  z.object({
    customer_payment: z.lazy(() =>
      ApiCustomerPaymentCreateResponseCustomerPayment$inboundSchema
    ),
    idempotent_replay: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "customer_payment": "customerPayment",
      "idempotent_replay": "idempotentReplay",
    });
  }),
);

export function apiCustomerPaymentCreateResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiCustomerPaymentCreateResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiCustomerPaymentCreateResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentCreateResponseData' from JSON`,
  );
}

/** @internal */
export const ApiCustomerPaymentCreateResponse$inboundSchema: z.ZodMiniType<
  ApiCustomerPaymentCreateResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiCustomerPaymentCreateResponseData$inboundSchema),
    warnings: z.array(z.any()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiCustomerPaymentCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiCustomerPaymentCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCustomerPaymentCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCustomerPaymentCreateResponse' from JSON`,
  );
}
