/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ff3d1104aa51
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnum9ac70a3316 = {
  NotRequired: "not_required",
  Pending: "pending",
  Issued: "issued",
} as const;
export type ApiSharedEnum9ac70a3316 = OpenEnum<typeof ApiSharedEnum9ac70a3316>;

/** @internal */
export const ApiSharedEnum9ac70a3316$inboundSchema: z.ZodMiniType<
  ApiSharedEnum9ac70a3316,
  unknown
> = openEnums.inboundSchema(ApiSharedEnum9ac70a3316);
/** @internal */
export const ApiSharedEnum9ac70a3316$outboundSchema: z.ZodMiniType<
  string,
  ApiSharedEnum9ac70a3316
> = openEnums.outboundSchema(ApiSharedEnum9ac70a3316);
