/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 61ebb25b6152
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject05f64e43bb,
  ApiSharedObject05f64e43bb$inboundSchema,
} from "./api-shared-object05f64e43bb.js";
import {
  ApiSharedObject5a978938b1,
  ApiSharedObject5a978938b1$inboundSchema,
} from "./api-shared-object5a978938b1.js";
import {
  ApiSharedObject738aa6c207,
  ApiSharedObject738aa6c207$inboundSchema,
} from "./api-shared-object738aa6c207.js";
import {
  ApiSharedObject8e3feaa104,
  ApiSharedObject8e3feaa104$inboundSchema,
} from "./api-shared-object8e3feaa104.js";
import {
  ApiSharedObjectb4d57efe6e,
  ApiSharedObjectb4d57efe6e$inboundSchema,
} from "./api-shared-objectb4d57efe6e.js";
import {
  ApiSharedObjectc15d6ab2fa,
  ApiSharedObjectc15d6ab2fa$inboundSchema,
} from "./api-shared-objectc15d6ab2fa.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiDeliveryNoteDetailResponseOrigin =
  | ApiSharedObjectc15d6ab2fa
  | ApiSharedObject5a978938b1
  | ApiSharedObject05f64e43bb
  | discriminatedUnionTypes.Unknown<"type">;

export type ApiDeliveryNoteDetailResponseData = {
  object: "delivery_note";
  id: string;
  number: string | null;
  date: Date;
  customer: ApiSharedObject738aa6c207 | null;
  origin:
    | ApiSharedObjectc15d6ab2fa
    | ApiSharedObject5a978938b1
    | ApiSharedObject05f64e43bb
    | discriminatedUnionTypes.Unknown<"type">;
  createdAt: Date;
  deliveryNoteNumber: number;
  pointOfSale: ApiSharedObjectb4d57efe6e | null;
  carrier: string | null;
  deliveryAddress: string | null;
  scheduledDate: Date | null;
  deliveredAt: Date | null;
  recipientName: string | null;
  recipientDocument: string | null;
  driverId: string | null;
  notes: string | null;
  items: Array<ApiSharedObject8e3feaa104>;
  updatedAt: Date;
};

export type ApiDeliveryNoteDetailResponse = {
  requestId: string;
  data: ApiDeliveryNoteDetailResponseData;
};

/** @internal */
export const ApiDeliveryNoteDetailResponseOrigin$inboundSchema: z.ZodMiniType<
  ApiDeliveryNoteDetailResponseOrigin,
  unknown
> = discriminatedUnion("type", {
  sale: ApiSharedObjectc15d6ab2fa$inboundSchema,
  fulfillment: ApiSharedObject5a978938b1$inboundSchema,
  custom: ApiSharedObject05f64e43bb$inboundSchema,
});

export function apiDeliveryNoteDetailResponseOriginFromJSON(
  jsonString: string,
): SafeParseResult<ApiDeliveryNoteDetailResponseOrigin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiDeliveryNoteDetailResponseOrigin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiDeliveryNoteDetailResponseOrigin' from JSON`,
  );
}

/** @internal */
export const ApiDeliveryNoteDetailResponseData$inboundSchema: z.ZodMiniType<
  ApiDeliveryNoteDetailResponseData,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("delivery_note"),
    id: types.string(),
    number: types.nullable(types.string()),
    date: types.date(),
    customer: types.nullable(ApiSharedObject738aa6c207$inboundSchema),
    origin: discriminatedUnion("type", {
      sale: ApiSharedObjectc15d6ab2fa$inboundSchema,
      fulfillment: ApiSharedObject5a978938b1$inboundSchema,
      custom: ApiSharedObject05f64e43bb$inboundSchema,
    }),
    created_at: types.date(),
    delivery_note_number: types.number(),
    point_of_sale: types.nullable(ApiSharedObjectb4d57efe6e$inboundSchema),
    carrier: types.nullable(types.string()),
    delivery_address: types.nullable(types.string()),
    scheduled_date: types.nullable(types.date()),
    delivered_at: types.nullable(types.date()),
    recipient_name: types.nullable(types.string()),
    recipient_document: types.nullable(types.string()),
    driver_id: types.nullable(types.string()),
    notes: types.nullable(types.string()),
    items: z.array(ApiSharedObject8e3feaa104$inboundSchema),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "delivery_note_number": "deliveryNoteNumber",
      "point_of_sale": "pointOfSale",
      "delivery_address": "deliveryAddress",
      "scheduled_date": "scheduledDate",
      "delivered_at": "deliveredAt",
      "recipient_name": "recipientName",
      "recipient_document": "recipientDocument",
      "driver_id": "driverId",
      "updated_at": "updatedAt",
    });
  }),
);

export function apiDeliveryNoteDetailResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiDeliveryNoteDetailResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiDeliveryNoteDetailResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiDeliveryNoteDetailResponseData' from JSON`,
  );
}

/** @internal */
export const ApiDeliveryNoteDetailResponse$inboundSchema: z.ZodMiniType<
  ApiDeliveryNoteDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiDeliveryNoteDetailResponseData$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiDeliveryNoteDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiDeliveryNoteDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiDeliveryNoteDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiDeliveryNoteDetailResponse' from JSON`,
  );
}
