/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a5c1aee2a8ae
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ApiSharedObject1dbe66a4f8 = {
  orderLineId: string;
  quantity: number;
};

/** @internal */
export type ApiSharedObject1dbe66a4f8$Outbound = {
  order_line_id: string;
  quantity: number;
};

/** @internal */
export const ApiSharedObject1dbe66a4f8$outboundSchema: z.ZodMiniType<
  ApiSharedObject1dbe66a4f8$Outbound,
  ApiSharedObject1dbe66a4f8
> = z.pipe(
  z.object({
    orderLineId: z.string(),
    quantity: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      orderLineId: "order_line_id",
    });
  }),
);

export function apiSharedObject1dbe66a4f8ToJSON(
  apiSharedObject1dbe66a4f8: ApiSharedObject1dbe66a4f8,
): string {
  return JSON.stringify(
    ApiSharedObject1dbe66a4f8$outboundSchema.parse(apiSharedObject1dbe66a4f8),
  );
}
