/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9ff7ab8c52e9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectaa12edb924 = {
  id: string;
  name: string;
  description: string | null;
  email: string | null;
  phone: string | null;
  taxIdType: string | null;
  taxId: string | null;
  taxCategory: string | null;
  paymentTermId: string | null;
  paymentTermDays: number | null;
  address: string | null;
  apartment: string | null;
  city: string | null;
  province: string | null;
  postalCode: string | null;
};

/** @internal */
export const ApiSharedObjectaa12edb924$inboundSchema: z.ZodMiniType<
  ApiSharedObjectaa12edb924,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    email: types.nullable(types.string()),
    phone: types.nullable(types.string()),
    tax_id_type: types.nullable(types.string()),
    tax_id: types.nullable(types.string()),
    tax_category: types.nullable(types.string()),
    payment_term_id: types.nullable(types.string()),
    payment_term_days: types.nullable(types.number()),
    address: types.nullable(types.string()),
    apartment: types.nullable(types.string()),
    city: types.nullable(types.string()),
    province: types.nullable(types.string()),
    postal_code: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tax_id_type": "taxIdType",
      "tax_id": "taxId",
      "tax_category": "taxCategory",
      "payment_term_id": "paymentTermId",
      "payment_term_days": "paymentTermDays",
      "postal_code": "postalCode",
    });
  }),
);

export function apiSharedObjectaa12edb924FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectaa12edb924, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectaa12edb924$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectaa12edb924' from JSON`,
  );
}
