/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 49a19713168c
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnum9e7af09974 = {
  CommercialInvoice: "commercial_invoice",
  CustomsDispatch: "customs_dispatch",
  CustomsDispatchReversal: "customs_dispatch_reversal",
} as const;
export type ApiSharedEnum9e7af09974 = OpenEnum<typeof ApiSharedEnum9e7af09974>;

/** @internal */
export const ApiSharedEnum9e7af09974$inboundSchema: z.ZodMiniType<
  ApiSharedEnum9e7af09974,
  unknown
> = openEnums.inboundSchema(ApiSharedEnum9e7af09974);
/** @internal */
export const ApiSharedEnum9e7af09974$outboundSchema: z.ZodMiniType<
  string,
  ApiSharedEnum9e7af09974
> = openEnums.outboundSchema(ApiSharedEnum9e7af09974);
