/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: efe207c4e633
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SkippedByReason = {
  compositePricing?: number | undefined;
  zeroBaseForPercentage?: number | undefined;
  negativeResult?: number | undefined;
  unchanged?: number | undefined;
};

export type ProductBulkAdjustment = {
  object: "product_bulk_adjustment";
  updated: number;
  skipped: number;
  skippedByReason: SkippedByReason;
};

export type ApiProductBulkAdjustmentResponseData = {
  productBulkAdjustment: ProductBulkAdjustment;
};

export type ApiProductBulkAdjustmentResponse = {
  requestId: string;
  data: ApiProductBulkAdjustmentResponseData;
  warnings: Array<any>;
};

/** @internal */
export const SkippedByReason$inboundSchema: z.ZodMiniType<
  SkippedByReason,
  unknown
> = z.pipe(
  z.object({
    composite_pricing: types.optional(types.number()),
    zero_base_for_percentage: types.optional(types.number()),
    negative_result: types.optional(types.number()),
    unchanged: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "composite_pricing": "compositePricing",
      "zero_base_for_percentage": "zeroBaseForPercentage",
      "negative_result": "negativeResult",
    });
  }),
);

export function skippedByReasonFromJSON(
  jsonString: string,
): SafeParseResult<SkippedByReason, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkippedByReason$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkippedByReason' from JSON`,
  );
}

/** @internal */
export const ProductBulkAdjustment$inboundSchema: z.ZodMiniType<
  ProductBulkAdjustment,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("product_bulk_adjustment"),
    updated: types.number(),
    skipped: types.number(),
    skipped_by_reason: z.lazy(() => SkippedByReason$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "skipped_by_reason": "skippedByReason",
    });
  }),
);

export function productBulkAdjustmentFromJSON(
  jsonString: string,
): SafeParseResult<ProductBulkAdjustment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductBulkAdjustment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductBulkAdjustment' from JSON`,
  );
}

/** @internal */
export const ApiProductBulkAdjustmentResponseData$inboundSchema: z.ZodMiniType<
  ApiProductBulkAdjustmentResponseData,
  unknown
> = z.pipe(
  z.object({
    product_bulk_adjustment: z.lazy(() => ProductBulkAdjustment$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "product_bulk_adjustment": "productBulkAdjustment",
    });
  }),
);

export function apiProductBulkAdjustmentResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiProductBulkAdjustmentResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiProductBulkAdjustmentResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiProductBulkAdjustmentResponseData' from JSON`,
  );
}

/** @internal */
export const ApiProductBulkAdjustmentResponse$inboundSchema: z.ZodMiniType<
  ApiProductBulkAdjustmentResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiProductBulkAdjustmentResponseData$inboundSchema),
    warnings: z.array(z.any()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiProductBulkAdjustmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiProductBulkAdjustmentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiProductBulkAdjustmentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiProductBulkAdjustmentResponse' from JSON`,
  );
}
