/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8028c84d3fae
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum53162db3eb,
  ApiSharedEnum53162db3eb$inboundSchema,
} from "./api-shared-enum53162db3eb.js";
import {
  ApiSharedEnum8d46e1ec20,
  ApiSharedEnum8d46e1ec20$inboundSchema,
} from "./api-shared-enum8d46e1ec20.js";
import {
  ApiSharedEnumd440d6785b,
  ApiSharedEnumd440d6785b$inboundSchema,
} from "./api-shared-enumd440d6785b.js";
import {
  ApiSharedEnumd952d5ce8e,
  ApiSharedEnumd952d5ce8e$inboundSchema,
} from "./api-shared-enumd952d5ce8e.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiTreasuryBalanceListResponseData = {
  object: "treasury_balance";
  id: string;
  balanceType: ApiSharedEnum53162db3eb;
  name: string;
  description: string | null;
  currency: "PES";
  amount: number;
  asOf: Date;
  calculatedAt: Date;
  visibilityScope: ApiSharedEnumd440d6785b;
  status: ApiSharedEnumd952d5ce8e;
  createdAt: Date;
  updatedAt: Date;
};

export type ApiTreasuryBalanceListResponse = {
  requestId: string;
  data: Array<ApiTreasuryBalanceListResponseData>;
  hasMore: boolean;
  nextCursor: string | null;
  /**
   * List-envelope discriminator.
   */
  object: ApiSharedEnum8d46e1ec20;
  /**
   * Requested list path.
   */
  url: string;
};

/** @internal */
export const ApiTreasuryBalanceListResponseData$inboundSchema: z.ZodMiniType<
  ApiTreasuryBalanceListResponseData,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("treasury_balance"),
    id: types.string(),
    balance_type: ApiSharedEnum53162db3eb$inboundSchema,
    name: types.string(),
    description: types.nullable(types.string()),
    currency: types.literal("PES"),
    amount: types.number(),
    as_of: types.date(),
    calculated_at: types.date(),
    visibility_scope: ApiSharedEnumd440d6785b$inboundSchema,
    status: ApiSharedEnumd952d5ce8e$inboundSchema,
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "balance_type": "balanceType",
      "as_of": "asOf",
      "calculated_at": "calculatedAt",
      "visibility_scope": "visibilityScope",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function apiTreasuryBalanceListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiTreasuryBalanceListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiTreasuryBalanceListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiTreasuryBalanceListResponseData' from JSON`,
  );
}

/** @internal */
export const ApiTreasuryBalanceListResponse$inboundSchema: z.ZodMiniType<
  ApiTreasuryBalanceListResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.array(
      z.lazy(() => ApiTreasuryBalanceListResponseData$inboundSchema),
    ),
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    object: ApiSharedEnum8d46e1ec20$inboundSchema,
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function apiTreasuryBalanceListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiTreasuryBalanceListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiTreasuryBalanceListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiTreasuryBalanceListResponse' from JSON`,
  );
}
