/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a1f0a643486
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ApiSharedObject890679c3fd,
  ApiSharedObject890679c3fd$inboundSchema,
} from "./api-shared-object890679c3fd.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject44d94dc68b = {
  /**
   * Document availability. The URL requires bearer authentication and never contains a storage path or signed query string.
   */
  file: ApiSharedObject890679c3fd;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ApiSharedObject44d94dc68b$inboundSchema: z.ZodMiniType<
  ApiSharedObject44d94dc68b,
  unknown
> = z.catchall(
  z.object({
    file: ApiSharedObject890679c3fd$inboundSchema,
  }),
  z.any(),
);

export function apiSharedObject44d94dc68bFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject44d94dc68b, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject44d94dc68b$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject44d94dc68b' from JSON`,
  );
}
