/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5fee231de7dd
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObjectf03e2ce692,
  ApiSharedObjectf03e2ce692$inboundSchema,
} from "./api-shared-objectf03e2ce692.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject8e3feaa104 = {
  id: string;
  saleItemId: string | null;
  quantity: number;
  name: string | null;
  isCustom: boolean;
  warehouseId: string | null;
  product: ApiSharedObjectf03e2ce692 | null;
};

/** @internal */
export const ApiSharedObject8e3feaa104$inboundSchema: z.ZodMiniType<
  ApiSharedObject8e3feaa104,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    sale_item_id: types.nullable(types.string()),
    quantity: types.number(),
    name: types.nullable(types.string()),
    is_custom: types.boolean(),
    warehouse_id: types.nullable(types.string()),
    product: types.nullable(ApiSharedObjectf03e2ce692$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "sale_item_id": "saleItemId",
      "is_custom": "isCustom",
      "warehouse_id": "warehouseId",
    });
  }),
);

export function apiSharedObject8e3feaa104FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject8e3feaa104, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject8e3feaa104$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject8e3feaa104' from JSON`,
  );
}
