/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4ed6bbd3042c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiSharedObjectc2dbdba87b,
  ApiSharedObjectc2dbdba87b$Outbound,
  ApiSharedObjectc2dbdba87b$outboundSchema,
} from "./api-shared-objectc2dbdba87b.js";

export const ApiOrderPreparationUpdateRequestStatus = {
  InProgress: "in_progress",
} as const;
export type ApiOrderPreparationUpdateRequestStatus = ClosedEnum<
  typeof ApiOrderPreparationUpdateRequestStatus
>;

export type ApiOrderPreparationUpdateRequest = {
  status?: ApiOrderPreparationUpdateRequestStatus | undefined;
  preparationGroupId?: string | undefined;
  warehouseId?: string | undefined;
  items?: Array<ApiSharedObjectc2dbdba87b> | undefined;
};

/** @internal */
export const ApiOrderPreparationUpdateRequestStatus$outboundSchema:
  z.ZodMiniEnum<typeof ApiOrderPreparationUpdateRequestStatus> = z.enum(
    ApiOrderPreparationUpdateRequestStatus,
  );

/** @internal */
export type ApiOrderPreparationUpdateRequest$Outbound = {
  status?: string | undefined;
  preparation_group_id?: string | undefined;
  warehouse_id?: string | undefined;
  items?: Array<ApiSharedObjectc2dbdba87b$Outbound> | undefined;
};

/** @internal */
export const ApiOrderPreparationUpdateRequest$outboundSchema: z.ZodMiniType<
  ApiOrderPreparationUpdateRequest$Outbound,
  ApiOrderPreparationUpdateRequest
> = z.pipe(
  z.object({
    status: z.optional(ApiOrderPreparationUpdateRequestStatus$outboundSchema),
    preparationGroupId: z.optional(z.string()),
    warehouseId: z.optional(z.string()),
    items: z.optional(z.array(ApiSharedObjectc2dbdba87b$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      preparationGroupId: "preparation_group_id",
      warehouseId: "warehouse_id",
    });
  }),
);

export function apiOrderPreparationUpdateRequestToJSON(
  apiOrderPreparationUpdateRequest: ApiOrderPreparationUpdateRequest,
): string {
  return JSON.stringify(
    ApiOrderPreparationUpdateRequest$outboundSchema.parse(
      apiOrderPreparationUpdateRequest,
    ),
  );
}
