/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0d8a6417dde2
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnum1bb83a32a7 = {
  SaleCreated: "sale.created",
  SaleUpdated: "sale.updated",
  OrderCreated: "order.created",
  OrderUpdated: "order.updated",
  OrderCompleted: "order.completed",
  OrderCancelled: "order.cancelled",
  OrderPartiallyFulfilled: "order.partially_fulfilled",
  OrderFulfilled: "order.fulfilled",
  FulfillmentCreated: "fulfillment.created",
  BankAccountCreated: "bank_account.created",
  BankAccountUpdated: "bank_account.updated",
  BankAccountActivated: "bank_account.activated",
  BankAccountDeactivated: "bank_account.deactivated",
  WebhookEndpointDisabled: "webhook_endpoint.disabled",
} as const;
export type ApiSharedEnum1bb83a32a7 = OpenEnum<typeof ApiSharedEnum1bb83a32a7>;

/** @internal */
export const ApiSharedEnum1bb83a32a7$inboundSchema: z.ZodMiniType<
  ApiSharedEnum1bb83a32a7,
  unknown
> = openEnums.inboundSchema(ApiSharedEnum1bb83a32a7);
/** @internal */
export const ApiSharedEnum1bb83a32a7$outboundSchema: z.ZodMiniType<
  string,
  ApiSharedEnum1bb83a32a7
> = openEnums.outboundSchema(ApiSharedEnum1bb83a32a7);
