/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 237550f0ea83
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum4e8d9d097e,
  ApiSharedEnum4e8d9d097e$inboundSchema,
} from "./api-shared-enum4e8d9d097e.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject2787a7ea36 = {
  requestId?: string | undefined;
  effectiveScope?: ApiSharedEnum4e8d9d097e | undefined;
  data?: { [k: string]: any } | undefined;
};

/** @internal */
export const ApiSharedObject2787a7ea36$inboundSchema: z.ZodMiniType<
  ApiSharedObject2787a7ea36,
  unknown
> = z.pipe(
  z.object({
    request_id: types.optional(types.string()),
    effective_scope: types.optional(ApiSharedEnum4e8d9d097e$inboundSchema),
    data: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "effective_scope": "effectiveScope",
    });
  }),
);

export function apiSharedObject2787a7ea36FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject2787a7ea36, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject2787a7ea36$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject2787a7ea36' from JSON`,
  );
}
