/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eac5649e9a64
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ApiSharedEnum377ec234cb,
  ApiSharedEnum377ec234cb$outboundSchema,
} from "./api-shared-enum377ec234cb.js";
import {
  ApiSharedEnum73bb779813,
  ApiSharedEnum73bb779813$outboundSchema,
} from "./api-shared-enum73bb779813.js";

export type InstallmentPlan = {
  code: string;
  label: string;
};

export type ApiPaymentMethodMutationRequest = {
  name: string;
  type?: ApiSharedEnum377ec234cb | undefined;
  bankAccountId?: string | null | undefined;
  linkedAccountId?: string | null | undefined;
  feePercentage?: string | null | undefined;
  feeFixed?: number | null | undefined;
  requiresReference?: boolean | undefined;
  visibility?: ApiSharedEnum73bb779813 | undefined;
  installmentPlans?: Array<InstallmentPlan> | undefined;
  isActive?: boolean | undefined;
};

/** @internal */
export type InstallmentPlan$Outbound = {
  code: string;
  label: string;
};

/** @internal */
export const InstallmentPlan$outboundSchema: z.ZodMiniType<
  InstallmentPlan$Outbound,
  InstallmentPlan
> = z.object({
  code: z.string(),
  label: z.string(),
});

export function installmentPlanToJSON(
  installmentPlan: InstallmentPlan,
): string {
  return JSON.stringify(InstallmentPlan$outboundSchema.parse(installmentPlan));
}

/** @internal */
export type ApiPaymentMethodMutationRequest$Outbound = {
  name: string;
  type?: string | undefined;
  bank_account_id?: string | null | undefined;
  linked_account_id?: string | null | undefined;
  fee_percentage?: string | null | undefined;
  fee_fixed?: number | null | undefined;
  requires_reference?: boolean | undefined;
  visibility?: string | undefined;
  installment_plans?: Array<InstallmentPlan$Outbound> | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const ApiPaymentMethodMutationRequest$outboundSchema: z.ZodMiniType<
  ApiPaymentMethodMutationRequest$Outbound,
  ApiPaymentMethodMutationRequest
> = z.pipe(
  z.object({
    name: z.string(),
    type: z.optional(ApiSharedEnum377ec234cb$outboundSchema),
    bankAccountId: z.optional(z.nullable(z.string())),
    linkedAccountId: z.optional(z.nullable(z.string())),
    feePercentage: z.optional(z.nullable(z.string())),
    feeFixed: z.optional(z.nullable(z.int())),
    requiresReference: z.optional(z.boolean()),
    visibility: z.optional(ApiSharedEnum73bb779813$outboundSchema),
    installmentPlans: z.optional(
      z.array(z.lazy(() => InstallmentPlan$outboundSchema)),
    ),
    isActive: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      bankAccountId: "bank_account_id",
      linkedAccountId: "linked_account_id",
      feePercentage: "fee_percentage",
      feeFixed: "fee_fixed",
      requiresReference: "requires_reference",
      installmentPlans: "installment_plans",
      isActive: "is_active",
    });
  }),
);

export function apiPaymentMethodMutationRequestToJSON(
  apiPaymentMethodMutationRequest: ApiPaymentMethodMutationRequest,
): string {
  return JSON.stringify(
    ApiPaymentMethodMutationRequest$outboundSchema.parse(
      apiPaymentMethodMutationRequest,
    ),
  );
}
