/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a6b3c8b2d772
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject7034e0d593,
  ApiSharedObject7034e0d593$inboundSchema,
} from "./api-shared-object7034e0d593.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSupplierDetailResponse = {
  requestId: string;
  data: ApiSharedObject7034e0d593;
};

/** @internal */
export const ApiSupplierDetailResponse$inboundSchema: z.ZodMiniType<
  ApiSupplierDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: ApiSharedObject7034e0d593$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiSupplierDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSupplierDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierDetailResponse' from JSON`,
  );
}
