/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 938a44d7c654
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject16ba66a421,
  ApiSharedObject16ba66a421$inboundSchema,
} from "./api-shared-object16ba66a421.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiPriceListDetailResponse = {
  requestId: string;
  data: ApiSharedObject16ba66a421;
};

/** @internal */
export const ApiPriceListDetailResponse$inboundSchema: z.ZodMiniType<
  ApiPriceListDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: ApiSharedObject16ba66a421$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiPriceListDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiPriceListDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiPriceListDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiPriceListDetailResponse' from JSON`,
  );
}
