/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2259491a5731
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnumff49232140,
  ApiSharedEnumff49232140$inboundSchema,
} from "./api-shared-enumff49232140.js";
import {
  ApiSharedObject16c3799d74,
  ApiSharedObject16c3799d74$inboundSchema,
} from "./api-shared-object16c3799d74.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjecte9e792772e = {
  productId: string | null;
  productName: string | null;
  sku: string | null;
  warehouseId: string | null;
  name: string | null;
  productType: ApiSharedEnumff49232140 | null;
  quantity: number;
  unitPrice: number;
  unitCost: number | null;
  taxRateId: number | null;
  isExempt: boolean;
  discount: ApiSharedObject16c3799d74 | null;
  notes: string | null;
  accountId: string | null;
  costCenter1Id: string | null;
  costCenter2Id: string | null;
  costCenter3Id: string | null;
};

/** @internal */
export const ApiSharedObjecte9e792772e$inboundSchema: z.ZodMiniType<
  ApiSharedObjecte9e792772e,
  unknown
> = z.pipe(
  z.object({
    product_id: types.nullable(types.string()),
    product_name: types.nullable(types.string()),
    sku: types.nullable(types.string()),
    warehouse_id: types.nullable(types.string()),
    name: types.nullable(types.string()),
    product_type: types.nullable(ApiSharedEnumff49232140$inboundSchema),
    quantity: types.number(),
    unit_price: types.number(),
    unit_cost: types.nullable(types.number()),
    tax_rate_id: types.nullable(types.number()),
    is_exempt: types.boolean(),
    discount: types.nullable(ApiSharedObject16c3799d74$inboundSchema),
    notes: types.nullable(types.string()),
    account_id: types.nullable(types.string()),
    cost_center1_id: types.nullable(types.string()),
    cost_center2_id: types.nullable(types.string()),
    cost_center3_id: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "product_id": "productId",
      "product_name": "productName",
      "warehouse_id": "warehouseId",
      "product_type": "productType",
      "unit_price": "unitPrice",
      "unit_cost": "unitCost",
      "tax_rate_id": "taxRateId",
      "is_exempt": "isExempt",
      "account_id": "accountId",
      "cost_center1_id": "costCenter1Id",
      "cost_center2_id": "costCenter2Id",
      "cost_center3_id": "costCenter3Id",
    });
  }),
);

export function apiSharedObjecte9e792772eFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjecte9e792772e, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjecte9e792772e$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjecte9e792772e' from JSON`,
  );
}
