/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 35dee34add16
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum822a963f55,
  ApiSharedEnum822a963f55$inboundSchema,
} from "./api-shared-enum822a963f55.js";
import {
  ApiSharedObjecta2ee8aef0f,
  ApiSharedObjecta2ee8aef0f$inboundSchema,
} from "./api-shared-objecta2ee8aef0f.js";
import {
  ApiSharedObjectc87fbdcf3b,
  ApiSharedObjectc87fbdcf3b$inboundSchema,
} from "./api-shared-objectc87fbdcf3b.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjecte048f871c2 = {
  id: string;
  name: string | null;
  quantity: number;
  unitCost: number | null;
  subtotal: number | null;
  taxRateId: number | null;
  isExempt: boolean | null;
  total: number | null;
  discountPercentage: number | null;
  purchaseOrderItemId: string | null;
  vatCategory: ApiSharedEnum822a963f55 | null;
  product: ApiSharedObjectc87fbdcf3b | null;
  purchaseOrder: ApiSharedObjecta2ee8aef0f | null;
};

/** @internal */
export const ApiSharedObjecte048f871c2$inboundSchema: z.ZodMiniType<
  ApiSharedObjecte048f871c2,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.nullable(types.string()),
    quantity: types.number(),
    unit_cost: types.nullable(types.number()),
    subtotal: types.nullable(types.number()),
    tax_rate_id: types.nullable(types.number()),
    is_exempt: types.nullable(types.boolean()),
    total: types.nullable(types.number()),
    discount_percentage: types.nullable(types.number()),
    purchase_order_item_id: types.nullable(types.string()),
    vat_category: types.nullable(ApiSharedEnum822a963f55$inboundSchema),
    product: types.nullable(ApiSharedObjectc87fbdcf3b$inboundSchema),
    purchase_order: types.nullable(ApiSharedObjecta2ee8aef0f$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "unit_cost": "unitCost",
      "tax_rate_id": "taxRateId",
      "is_exempt": "isExempt",
      "discount_percentage": "discountPercentage",
      "purchase_order_item_id": "purchaseOrderItemId",
      "vat_category": "vatCategory",
      "purchase_order": "purchaseOrder",
    });
  }),
);

export function apiSharedObjecte048f871c2FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjecte048f871c2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjecte048f871c2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjecte048f871c2' from JSON`,
  );
}
