/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 475366b01bda
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ApiSharedObject24cbbd28ea,
  ApiSharedObject24cbbd28ea$Outbound,
  ApiSharedObject24cbbd28ea$outboundSchema,
} from "./api-shared-object24cbbd28ea.js";

export type ApiSharedObjectd498e17ec0 = {
  paymentMethodId: string;
  amount: number;
  reference?: string | undefined;
  cardBrand?: string | undefined;
  cardBatchNumber?: string | undefined;
  cardCouponNumber?: string | undefined;
  cardInstallmentPlanCode?: string | undefined;
  notes?: string | undefined;
  feeAmount?: number | undefined;
  feePercentageApplied?: string | undefined;
  feeFixedApplied?: number | undefined;
  netAmount?: number | undefined;
  checkId?: string | undefined;
  checkData?: ApiSharedObject24cbbd28ea | undefined;
  registerId?: string | undefined;
  safeId?: string | undefined;
};

/** @internal */
export type ApiSharedObjectd498e17ec0$Outbound = {
  payment_method_id: string;
  amount: number;
  reference?: string | undefined;
  card_brand?: string | undefined;
  card_batch_number?: string | undefined;
  card_coupon_number?: string | undefined;
  card_installment_plan_code?: string | undefined;
  notes?: string | undefined;
  fee_amount?: number | undefined;
  fee_percentage_applied?: string | undefined;
  fee_fixed_applied?: number | undefined;
  net_amount?: number | undefined;
  check_id?: string | undefined;
  check_data?: ApiSharedObject24cbbd28ea$Outbound | undefined;
  register_id?: string | undefined;
  safe_id?: string | undefined;
};

/** @internal */
export const ApiSharedObjectd498e17ec0$outboundSchema: z.ZodMiniType<
  ApiSharedObjectd498e17ec0$Outbound,
  ApiSharedObjectd498e17ec0
> = z.pipe(
  z.object({
    paymentMethodId: z.string(),
    amount: z.int(),
    reference: z.optional(z.string()),
    cardBrand: z.optional(z.string()),
    cardBatchNumber: z.optional(z.string()),
    cardCouponNumber: z.optional(z.string()),
    cardInstallmentPlanCode: z.optional(z.string()),
    notes: z.optional(z.string()),
    feeAmount: z.optional(z.int()),
    feePercentageApplied: z.optional(z.string()),
    feeFixedApplied: z.optional(z.int()),
    netAmount: z.optional(z.int()),
    checkId: z.optional(z.string()),
    checkData: z.optional(ApiSharedObject24cbbd28ea$outboundSchema),
    registerId: z.optional(z.string()),
    safeId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      paymentMethodId: "payment_method_id",
      cardBrand: "card_brand",
      cardBatchNumber: "card_batch_number",
      cardCouponNumber: "card_coupon_number",
      cardInstallmentPlanCode: "card_installment_plan_code",
      feeAmount: "fee_amount",
      feePercentageApplied: "fee_percentage_applied",
      feeFixedApplied: "fee_fixed_applied",
      netAmount: "net_amount",
      checkId: "check_id",
      checkData: "check_data",
      registerId: "register_id",
      safeId: "safe_id",
    });
  }),
);

export function apiSharedObjectd498e17ec0ToJSON(
  apiSharedObjectd498e17ec0: ApiSharedObjectd498e17ec0,
): string {
  return JSON.stringify(
    ApiSharedObjectd498e17ec0$outboundSchema.parse(apiSharedObjectd498e17ec0),
  );
}
