/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e04d24d7f97d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjecta8ecbd0557 = {
  id: string | null;
  name: string | null;
  email: string | null;
  phone: string | null;
  taxId: string | null;
  taxIdType: string | null;
  taxCategory: string | null;
  address: string | null;
  city: string | null;
  provinceId: string | null;
  postalCode: string | null;
  paymentTermId: string | null;
};

/** @internal */
export const ApiSharedObjecta8ecbd0557$inboundSchema: z.ZodMiniType<
  ApiSharedObjecta8ecbd0557,
  unknown
> = z.pipe(
  z.object({
    id: types.nullable(types.string()),
    name: types.nullable(types.string()),
    email: types.nullable(types.string()),
    phone: types.nullable(types.string()),
    tax_id: types.nullable(types.string()),
    tax_id_type: types.nullable(types.string()),
    tax_category: types.nullable(types.string()),
    address: types.nullable(types.string()),
    city: types.nullable(types.string()),
    province_id: types.nullable(types.string()),
    postal_code: types.nullable(types.string()),
    payment_term_id: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tax_id": "taxId",
      "tax_id_type": "taxIdType",
      "tax_category": "taxCategory",
      "province_id": "provinceId",
      "postal_code": "postalCode",
      "payment_term_id": "paymentTermId",
    });
  }),
);

export function apiSharedObjecta8ecbd0557FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjecta8ecbd0557, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjecta8ecbd0557$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjecta8ecbd0557' from JSON`,
  );
}
