/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9a7abf540ca1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnumf2073aa092,
  ApiSharedEnumf2073aa092$inboundSchema,
} from "./api-shared-enumf2073aa092.js";
import {
  ApiSharedObject8aeeceaf0f,
  ApiSharedObject8aeeceaf0f$inboundSchema,
} from "./api-shared-object8aeeceaf0f.js";
import {
  ApiSharedObjecta50ed243b8,
  ApiSharedObjecta50ed243b8$inboundSchema,
} from "./api-shared-objecta50ed243b8.js";
import {
  ApiSharedObjected3905a55b,
  ApiSharedObjected3905a55b$inboundSchema,
} from "./api-shared-objected3905a55b.js";
import {
  ApiSharedObjectfaafd59b8b,
  ApiSharedObjectfaafd59b8b$inboundSchema,
} from "./api-shared-objectfaafd59b8b.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjecteffe384a18 = {
  object: "purchase_order";
  id: string;
  orderNumber: number;
  formattedOrderNumber: string | null;
  status: ApiSharedEnumf2073aa092;
  orderDate: Date;
  expectedDate: Date | null;
  currency: string;
  supplier: ApiSharedObjectfaafd59b8b | null;
  warehouse: ApiSharedObject8aeeceaf0f | null;
  createdAt: Date;
  tags: Array<ApiSharedObjected3905a55b>;
  warehouseId: string | null;
  notes: string | null;
  items: Array<ApiSharedObjecta50ed243b8>;
};

/** @internal */
export const ApiSharedObjecteffe384a18$inboundSchema: z.ZodMiniType<
  ApiSharedObjecteffe384a18,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("purchase_order"),
    id: types.string(),
    order_number: types.number(),
    formatted_order_number: types.nullable(types.string()),
    status: ApiSharedEnumf2073aa092$inboundSchema,
    order_date: types.date(),
    expected_date: types.nullable(types.date()),
    currency: types.string(),
    supplier: types.nullable(ApiSharedObjectfaafd59b8b$inboundSchema),
    warehouse: types.nullable(ApiSharedObject8aeeceaf0f$inboundSchema),
    created_at: types.date(),
    tags: z.array(ApiSharedObjected3905a55b$inboundSchema),
    warehouse_id: types.nullable(types.string()),
    notes: types.nullable(types.string()),
    items: z.array(ApiSharedObjecta50ed243b8$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_number": "orderNumber",
      "formatted_order_number": "formattedOrderNumber",
      "order_date": "orderDate",
      "expected_date": "expectedDate",
      "created_at": "createdAt",
      "warehouse_id": "warehouseId",
    });
  }),
);

export function apiSharedObjecteffe384a18FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjecteffe384a18, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjecteffe384a18$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjecteffe384a18' from JSON`,
  );
}
