/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 54f583f8e7f4
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject5524465fb0 = {
  /**
   * Public filter field in snake_case.
   */
  field: string;
  input: string;
  /**
   * Verified entity ID or supported sentinel.
   */
  resolvedId: string;
  resolvedLabel: string;
};

/** @internal */
export const ApiSharedObject5524465fb0$inboundSchema: z.ZodMiniType<
  ApiSharedObject5524465fb0,
  unknown
> = z.pipe(
  z.object({
    field: types.string(),
    input: types.string(),
    resolved_id: types.string(),
    resolved_label: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "resolved_id": "resolvedId",
      "resolved_label": "resolvedLabel",
    });
  }),
);

export function apiSharedObject5524465fb0FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject5524465fb0, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject5524465fb0$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject5524465fb0' from JSON`,
  );
}
