/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f269efb6c1f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectdafaa4a9ee = {
  willReceiveProducts: boolean;
  willCreateReceipt: boolean;
  willIncreaseDirectStock: boolean;
  warehouseId: string | null;
  productLineCount: number;
  totalQuantity: number;
  purchaseOrderIds: Array<string>;
};

/** @internal */
export const ApiSharedObjectdafaa4a9ee$inboundSchema: z.ZodMiniType<
  ApiSharedObjectdafaa4a9ee,
  unknown
> = z.pipe(
  z.object({
    will_receive_products: types.boolean(),
    will_create_receipt: types.boolean(),
    will_increase_direct_stock: types.boolean(),
    warehouse_id: types.nullable(types.string()),
    product_line_count: types.number(),
    total_quantity: types.number(),
    purchase_order_ids: z.array(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "will_receive_products": "willReceiveProducts",
      "will_create_receipt": "willCreateReceipt",
      "will_increase_direct_stock": "willIncreaseDirectStock",
      "warehouse_id": "warehouseId",
      "product_line_count": "productLineCount",
      "total_quantity": "totalQuantity",
      "purchase_order_ids": "purchaseOrderIds",
    });
  }),
);

export function apiSharedObjectdafaa4a9eeFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectdafaa4a9ee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectdafaa4a9ee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectdafaa4a9ee' from JSON`,
  );
}
