/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4ad401a65c66
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * List-envelope discriminator.
 */
export const ApiSharedEnum8d46e1ec20 = {
  List: "list",
} as const;
/**
 * List-envelope discriminator.
 */
export type ApiSharedEnum8d46e1ec20 = ClosedEnum<
  typeof ApiSharedEnum8d46e1ec20
>;

/** @internal */
export const ApiSharedEnum8d46e1ec20$inboundSchema: z.ZodMiniEnum<
  typeof ApiSharedEnum8d46e1ec20
> = z.enum(ApiSharedEnum8d46e1ec20);
