/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9d3623ce20e1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnumb3cd05d84a,
  ApiSharedEnumb3cd05d84a$inboundSchema,
} from "./api-shared-enumb3cd05d84a.js";
import {
  ApiSharedEnumb8b65e480e,
  ApiSharedEnumb8b65e480e$inboundSchema,
} from "./api-shared-enumb8b65e480e.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectf2ec33bd59 = {
  origin: ApiSharedEnumb3cd05d84a;
  type: ApiSharedEnumb8b65e480e;
  sourcePriceListId: string | null;
};

/** @internal */
export const ApiSharedObjectf2ec33bd59$inboundSchema: z.ZodMiniType<
  ApiSharedObjectf2ec33bd59,
  unknown
> = z.pipe(
  z.object({
    origin: ApiSharedEnumb3cd05d84a$inboundSchema,
    type: ApiSharedEnumb8b65e480e$inboundSchema,
    source_price_list_id: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "source_price_list_id": "sourcePriceListId",
    });
  }),
);

export function apiSharedObjectf2ec33bd59FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectf2ec33bd59, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectf2ec33bd59$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectf2ec33bd59' from JSON`,
  );
}
