/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b563444a24bd
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnum3e321043c1 = {
  Bcra: "bcra",
  Actual: "actual",
  Manual: "manual",
} as const;
export type ApiSharedEnum3e321043c1 = OpenEnum<typeof ApiSharedEnum3e321043c1>;

/** @internal */
export const ApiSharedEnum3e321043c1$inboundSchema: z.ZodMiniType<
  ApiSharedEnum3e321043c1,
  unknown
> = openEnums.inboundSchema(ApiSharedEnum3e321043c1);
