/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 48b9783fd75f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ApiSharedObjectc2ed2476df = {
  creditPurchaseId: string;
  appliedAmount: number;
};

/** @internal */
export type ApiSharedObjectc2ed2476df$Outbound = {
  credit_purchase_id: string;
  applied_amount: number;
};

/** @internal */
export const ApiSharedObjectc2ed2476df$outboundSchema: z.ZodMiniType<
  ApiSharedObjectc2ed2476df$Outbound,
  ApiSharedObjectc2ed2476df
> = z.pipe(
  z.object({
    creditPurchaseId: z.string(),
    appliedAmount: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      creditPurchaseId: "credit_purchase_id",
      appliedAmount: "applied_amount",
    });
  }),
);

export function apiSharedObjectc2ed2476dfToJSON(
  apiSharedObjectc2ed2476df: ApiSharedObjectc2ed2476df,
): string {
  return JSON.stringify(
    ApiSharedObjectc2ed2476df$outboundSchema.parse(apiSharedObjectc2ed2476df),
  );
}
