/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 57f83b09484a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const ApiSupplierMutationRequestTaxIdType = {
  CuilCuit: "CUIL/CUIT",
  Dni: "DNI",
} as const;
export type ApiSupplierMutationRequestTaxIdType = ClosedEnum<
  typeof ApiSupplierMutationRequestTaxIdType
>;

export const ApiSupplierMutationRequestTaxCategory = {
  RegisteredVatTaxpayer: "registered_vat_taxpayer",
  FinalConsumer: "final_consumer",
  MonotributoTaxpayer: "monotributo_taxpayer",
  VatExempt: "vat_exempt",
  VatNotApplicable: "vat_not_applicable",
} as const;
export type ApiSupplierMutationRequestTaxCategory = ClosedEnum<
  typeof ApiSupplierMutationRequestTaxCategory
>;

export type ApiSupplierMutationRequest = {
  name: string;
  companyName?: string | null | undefined;
  description?: string | null | undefined;
  email?: string | null | undefined;
  phone?: string | null | undefined;
  taxId?: string | null | undefined;
  taxIdType?: ApiSupplierMutationRequestTaxIdType | null | undefined;
  taxCategory?: ApiSupplierMutationRequestTaxCategory | undefined;
  country?: string | undefined;
  province?: string | undefined;
  city?: string | null | undefined;
  address?: string | null | undefined;
  apartment?: string | null | undefined;
  postalCode?: string | null | undefined;
  paymentTermId?: string | null | undefined;
  isActive?: boolean | undefined;
};

/** @internal */
export const ApiSupplierMutationRequestTaxIdType$outboundSchema: z.ZodMiniEnum<
  typeof ApiSupplierMutationRequestTaxIdType
> = z.enum(ApiSupplierMutationRequestTaxIdType);

/** @internal */
export const ApiSupplierMutationRequestTaxCategory$outboundSchema:
  z.ZodMiniEnum<typeof ApiSupplierMutationRequestTaxCategory> = z.enum(
    ApiSupplierMutationRequestTaxCategory,
  );

/** @internal */
export type ApiSupplierMutationRequest$Outbound = {
  name: string;
  company_name?: string | null | undefined;
  description?: string | null | undefined;
  email?: string | null | undefined;
  phone?: string | null | undefined;
  tax_id?: string | null | undefined;
  tax_id_type?: string | null | undefined;
  tax_category?: string | undefined;
  country?: string | undefined;
  province?: string | undefined;
  city?: string | null | undefined;
  address?: string | null | undefined;
  apartment?: string | null | undefined;
  postal_code?: string | null | undefined;
  payment_term_id?: string | null | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const ApiSupplierMutationRequest$outboundSchema: z.ZodMiniType<
  ApiSupplierMutationRequest$Outbound,
  ApiSupplierMutationRequest
> = z.pipe(
  z.object({
    name: z.string(),
    companyName: z.optional(z.nullable(z.string())),
    description: z.optional(z.nullable(z.string())),
    email: z.optional(z.nullable(z.string())),
    phone: z.optional(z.nullable(z.string())),
    taxId: z.optional(z.nullable(z.string())),
    taxIdType: z.optional(
      z.nullable(ApiSupplierMutationRequestTaxIdType$outboundSchema),
    ),
    taxCategory: z.optional(
      ApiSupplierMutationRequestTaxCategory$outboundSchema,
    ),
    country: z.optional(z.string()),
    province: z.optional(z.string()),
    city: z.optional(z.nullable(z.string())),
    address: z.optional(z.nullable(z.string())),
    apartment: z.optional(z.nullable(z.string())),
    postalCode: z.optional(z.nullable(z.string())),
    paymentTermId: z.optional(z.nullable(z.string())),
    isActive: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      companyName: "company_name",
      taxId: "tax_id",
      taxIdType: "tax_id_type",
      taxCategory: "tax_category",
      postalCode: "postal_code",
      paymentTermId: "payment_term_id",
      isActive: "is_active",
    });
  }),
);

export function apiSupplierMutationRequestToJSON(
  apiSupplierMutationRequest: ApiSupplierMutationRequest,
): string {
  return JSON.stringify(
    ApiSupplierMutationRequest$outboundSchema.parse(apiSupplierMutationRequest),
  );
}
