/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cdf1bb60867f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import {
  ApiSharedEnum65e97ceeee,
  ApiSharedEnum65e97ceeee$inboundSchema,
} from "./api-shared-enum65e97ceeee.js";
import {
  ApiSharedEnumffb4886f2b,
  ApiSharedEnumffb4886f2b$inboundSchema,
} from "./api-shared-enumffb4886f2b.js";
import {
  ApiSharedObject2cdf35e652,
  ApiSharedObject2cdf35e652$inboundSchema,
} from "./api-shared-object2cdf35e652.js";
import {
  ApiSharedObject4faf4c3ad5,
  ApiSharedObject4faf4c3ad5$inboundSchema,
} from "./api-shared-object4faf4c3ad5.js";
import {
  ApiSharedObject63c2faf817,
  ApiSharedObject63c2faf817$inboundSchema,
} from "./api-shared-object63c2faf817.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectfabd7b2b2dExchangeRate = string | number;

export type ApiSharedObjectfabd7b2b2d = {
  id: string;
  type: "customer";
  status: ApiSharedEnum65e97ceeee;
  contactId: string | null;
  contactName: string | null;
  paymentNumber: number | null;
  formattedPaymentNumber: string | null;
  paymentDate: string;
  currency: ApiSharedEnumffb4886f2b;
  settlementCurrency?: ApiSharedEnumffb4886f2b | null | undefined;
  settlementTotalAmount?: number | null | undefined;
  exchangeRate?: string | number | null | undefined;
  totalAmount: number;
  balance: number;
  notes?: string | null | undefined;
  createdAt: Date;
  createdByName: string | null;
  splits?: Array<ApiSharedObject63c2faf817> | undefined;
  applications?: Array<ApiSharedObject2cdf35e652> | undefined;
  creditApplications?: Array<ApiSharedObject2cdf35e652> | undefined;
  journalLineApplications?: Array<ApiSharedObject2cdf35e652> | undefined;
  advanceApplications?: Array<ApiSharedObject2cdf35e652> | undefined;
  withholdings?: Array<ApiSharedObject4faf4c3ad5> | undefined;
};

/** @internal */
export const ApiSharedObjectfabd7b2b2dExchangeRate$inboundSchema: z.ZodMiniType<
  ApiSharedObjectfabd7b2b2dExchangeRate,
  unknown
> = smartUnion([types.string(), types.number()]);

export function apiSharedObjectfabd7b2b2dExchangeRateFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectfabd7b2b2dExchangeRate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSharedObjectfabd7b2b2dExchangeRate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectfabd7b2b2dExchangeRate' from JSON`,
  );
}

/** @internal */
export const ApiSharedObjectfabd7b2b2d$inboundSchema: z.ZodMiniType<
  ApiSharedObjectfabd7b2b2d,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    type: types.literal("customer"),
    status: ApiSharedEnum65e97ceeee$inboundSchema,
    contact_id: types.nullable(types.string()),
    contact_name: types.nullable(types.string()),
    payment_number: types.nullable(types.number()),
    formatted_payment_number: types.nullable(types.string()),
    payment_date: types.string(),
    currency: ApiSharedEnumffb4886f2b$inboundSchema,
    settlement_currency: z.optional(
      z.nullable(ApiSharedEnumffb4886f2b$inboundSchema),
    ),
    settlement_total_amount: z.optional(z.nullable(types.number())),
    exchange_rate: z.optional(
      z.nullable(smartUnion([types.string(), types.number()])),
    ),
    total_amount: types.number(),
    balance: types.number(),
    notes: z.optional(z.nullable(types.string())),
    created_at: types.date(),
    created_by_name: types.nullable(types.string()),
    splits: types.optional(z.array(ApiSharedObject63c2faf817$inboundSchema)),
    applications: types.optional(
      z.array(ApiSharedObject2cdf35e652$inboundSchema),
    ),
    credit_applications: types.optional(
      z.array(ApiSharedObject2cdf35e652$inboundSchema),
    ),
    journal_line_applications: types.optional(
      z.array(ApiSharedObject2cdf35e652$inboundSchema),
    ),
    advance_applications: types.optional(
      z.array(ApiSharedObject2cdf35e652$inboundSchema),
    ),
    withholdings: types.optional(
      z.array(ApiSharedObject4faf4c3ad5$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "contact_id": "contactId",
      "contact_name": "contactName",
      "payment_number": "paymentNumber",
      "formatted_payment_number": "formattedPaymentNumber",
      "payment_date": "paymentDate",
      "settlement_currency": "settlementCurrency",
      "settlement_total_amount": "settlementTotalAmount",
      "exchange_rate": "exchangeRate",
      "total_amount": "totalAmount",
      "created_at": "createdAt",
      "created_by_name": "createdByName",
      "credit_applications": "creditApplications",
      "journal_line_applications": "journalLineApplications",
      "advance_applications": "advanceApplications",
    });
  }),
);

export function apiSharedObjectfabd7b2b2dFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectfabd7b2b2d, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectfabd7b2b2d$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectfabd7b2b2d' from JSON`,
  );
}
