/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f6b2d1258298
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject5a978938b1 = {
  type: "fulfillment";
  fulfillmentId: string;
};

/** @internal */
export const ApiSharedObject5a978938b1$inboundSchema: z.ZodMiniType<
  ApiSharedObject5a978938b1,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("fulfillment"),
    fulfillment_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "fulfillment_id": "fulfillmentId",
    });
  }),
);

export function apiSharedObject5a978938b1FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject5a978938b1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject5a978938b1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject5a978938b1' from JSON`,
  );
}
