/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbe8cff81131
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObjecte94730814a,
  ApiSharedObjecte94730814a$inboundSchema,
} from "./api-shared-objecte94730814a.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiOrderDetailResponse = {
  requestId: string;
  data: ApiSharedObjecte94730814a;
};

/** @internal */
export const ApiOrderDetailResponse$inboundSchema: z.ZodMiniType<
  ApiOrderDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: ApiSharedObjecte94730814a$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiOrderDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiOrderDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiOrderDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiOrderDetailResponse' from JSON`,
  );
}
