/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aedd9e5b2d59
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject06b16aade1 = {
  type: "amount";
  value: number;
};

/** @internal */
export const ApiSharedObject06b16aade1$inboundSchema: z.ZodMiniType<
  ApiSharedObject06b16aade1,
  unknown
> = z.object({
  type: types.literal("amount"),
  value: types.number(),
});
/** @internal */
export type ApiSharedObject06b16aade1$Outbound = {
  type: "amount";
  value: number;
};

/** @internal */
export const ApiSharedObject06b16aade1$outboundSchema: z.ZodMiniType<
  ApiSharedObject06b16aade1$Outbound,
  ApiSharedObject06b16aade1
> = z.object({
  type: z.literal("amount"),
  value: z.int(),
});

export function apiSharedObject06b16aade1ToJSON(
  apiSharedObject06b16aade1: ApiSharedObject06b16aade1,
): string {
  return JSON.stringify(
    ApiSharedObject06b16aade1$outboundSchema.parse(apiSharedObject06b16aade1),
  );
}
export function apiSharedObject06b16aade1FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject06b16aade1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject06b16aade1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject06b16aade1' from JSON`,
  );
}
