/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 71422adf63bf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject56326f33c2 = {
  id: string;
  voucherType: string;
  invoiceStatus: string;
  invoiceDate: string;
  currency: string | null;
  total: number;
  formattedInvoiceNumber: string | null;
  originalSaleId: string | null;
  createdAt: Date;
};

/** @internal */
export const ApiSharedObject56326f33c2$inboundSchema: z.ZodMiniType<
  ApiSharedObject56326f33c2,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    voucher_type: types.string(),
    invoice_status: types.string(),
    invoice_date: types.string(),
    currency: types.nullable(types.string()),
    total: types.number(),
    formatted_invoice_number: types.nullable(types.string()),
    original_sale_id: types.nullable(types.string()),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "voucher_type": "voucherType",
      "invoice_status": "invoiceStatus",
      "invoice_date": "invoiceDate",
      "formatted_invoice_number": "formattedInvoiceNumber",
      "original_sale_id": "originalSaleId",
      "created_at": "createdAt",
    });
  }),
);

export function apiSharedObject56326f33c2FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject56326f33c2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject56326f33c2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject56326f33c2' from JSON`,
  );
}
