/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ac4d74ea4395
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum1ba2b57809,
  ApiSharedEnum1ba2b57809$inboundSchema,
} from "./api-shared-enum1ba2b57809.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Document availability. The URL requires bearer authentication and never contains a storage path or signed query string.
 */
export type ApiSharedObject9c9e4b0e0d = {
  status: ApiSharedEnum1ba2b57809;
  /**
   * Stable authenticated La Pyme API path. Present only when status is ready; follow redirects when downloading.
   */
  url: string | null;
};

/** @internal */
export const ApiSharedObject9c9e4b0e0d$inboundSchema: z.ZodMiniType<
  ApiSharedObject9c9e4b0e0d,
  unknown
> = z.object({
  status: ApiSharedEnum1ba2b57809$inboundSchema,
  url: types.nullable(types.string()),
});

export function apiSharedObject9c9e4b0e0dFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject9c9e4b0e0d, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject9c9e4b0e0d$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject9c9e4b0e0d' from JSON`,
  );
}
