/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1a9963f06253
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnumff49232140,
  ApiSharedEnumff49232140$inboundSchema,
} from "./api-shared-enumff49232140.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectf4b2e97eb9 = {
  id: string;
  name: string;
  sku: string | null;
  productType: ApiSharedEnumff49232140 | null;
  variantOptions: { [k: string]: string } | null;
  optionNames: Array<string> | null;
};

/** @internal */
export const ApiSharedObjectf4b2e97eb9$inboundSchema: z.ZodMiniType<
  ApiSharedObjectf4b2e97eb9,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    sku: types.nullable(types.string()),
    product_type: types.nullable(ApiSharedEnumff49232140$inboundSchema),
    variant_options: types.nullable(z.record(z.string(), types.string())),
    option_names: types.nullable(z.array(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "product_type": "productType",
      "variant_options": "variantOptions",
      "option_names": "optionNames",
    });
  }),
);

export function apiSharedObjectf4b2e97eb9FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectf4b2e97eb9, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectf4b2e97eb9$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectf4b2e97eb9' from JSON`,
  );
}
