/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f613d587e09d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ApiDeleteTreasuryMovementRequest = {
  updatedAt: Date;
};

/** @internal */
export type ApiDeleteTreasuryMovementRequest$Outbound = {
  updated_at: string;
};

/** @internal */
export const ApiDeleteTreasuryMovementRequest$outboundSchema: z.ZodMiniType<
  ApiDeleteTreasuryMovementRequest$Outbound,
  ApiDeleteTreasuryMovementRequest
> = z.pipe(
  z.object({
    updatedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
  }),
  z.transform((v) => {
    return remap$(v, {
      updatedAt: "updated_at",
    });
  }),
);

export function apiDeleteTreasuryMovementRequestToJSON(
  apiDeleteTreasuryMovementRequest: ApiDeleteTreasuryMovementRequest,
): string {
  return JSON.stringify(
    ApiDeleteTreasuryMovementRequest$outboundSchema.parse(
      apiDeleteTreasuryMovementRequest,
    ),
  );
}
