/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 575b82e324a1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum6cfb146157,
  ApiSharedEnum6cfb146157$inboundSchema,
} from "./api-shared-enum6cfb146157.js";
import {
  ApiSharedEnum9e7af09974,
  ApiSharedEnum9e7af09974$inboundSchema,
} from "./api-shared-enum9e7af09974.js";
import {
  ApiSharedEnumd34af90520,
  ApiSharedEnumd34af90520$inboundSchema,
} from "./api-shared-enumd34af90520.js";
import {
  ApiSharedEnumf0d69c3d87,
  ApiSharedEnumf0d69c3d87$inboundSchema,
} from "./api-shared-enumf0d69c3d87.js";
import {
  ApiSharedObject3c43192c61,
  ApiSharedObject3c43192c61$inboundSchema,
} from "./api-shared-object3c43192c61.js";
import {
  ApiSharedObjectc671832641,
  ApiSharedObjectc671832641$inboundSchema,
} from "./api-shared-objectc671832641.js";
import {
  ApiSharedObjectdafaa4a9ee,
  ApiSharedObjectdafaa4a9ee$inboundSchema,
} from "./api-shared-objectdafaa4a9ee.js";
import {
  ApiSharedObjectedd0c22535,
  ApiSharedObjectedd0c22535$inboundSchema,
} from "./api-shared-objectedd0c22535.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type NormalizedPurchase = {
  supplierId: string | null;
  voucherType: number;
  /**
   * Numero de comprobante del proveedor. Hasta 120 caracteres.
   */
  supplierInvoiceNumber: string | null;
  /**
   * Fecha del comprobante en formato YYYY-MM-DD.
   */
  invoiceDate: string | null;
  /**
   * Fecha contable de la compra en formato YYYY-MM-DD.
   */
  accountDate: string | null;
  /**
   * Fecha de vencimiento en formato YYYY-MM-DD.
   */
  dueDate: string | null;
  paymentTermId: ApiSharedEnumd34af90520 | null;
  /**
   * Rol del comprobante dentro del flujo de importacion.
   */
  importDocumentRole: ApiSharedEnum9e7af09974 | null;
  /**
   * ID de la factura comercial asociada al despacho aduanero.
   */
  importSourcePurchaseId: string | null;
  /**
   * Estado de nacionalizacion de la factura comercial de importacion.
   */
  importNationalizationStatus: ApiSharedEnumf0d69c3d87 | null;
  /**
   * Numero de despacho aduanero informado por el proveedor. Hasta 32 caracteres.
   */
  customsDispatchNumber: string | null;
  warehouseId: string | null;
  productsReceived: boolean;
  updateProductVariantCost: boolean;
  currency: ApiSharedEnum6cfb146157;
  exchangeRate: number;
  subtotal: number | null;
  taxAmount: number | null;
  total: number | null;
  discount: number | null;
  exemptAmount: number | null;
  nonTaxedAmount: number | null;
  baseAmount: number | null;
  vatPerceptionAmount: number | null;
  nationalTaxAmount: number | null;
  grossIncomeTaxAmount: number | null;
  municipalTaxAmount: number | null;
  internalTaxAmount: number | null;
  otherTaxAmount: number | null;
  notes: string | null;
  pdfPath: string | null;
  items: Array<ApiSharedObjectedd0c22535>;
};

export type ApiPurchaseTransactionSuccessResponseProjectedEffects = {
  inventory: ApiSharedObjectdafaa4a9ee;
  accounting: ApiSharedObject3c43192c61;
};

export type ApiPurchaseTransactionSuccessResponseData = {
  purchaseId: string;
  receiptCreated: boolean;
  idempotentReplay: boolean;
  normalizedPurchase: NormalizedPurchase;
  projectedEffects: ApiPurchaseTransactionSuccessResponseProjectedEffects;
};

export type ApiPurchaseTransactionSuccessResponse = {
  requestId: string;
  data: ApiPurchaseTransactionSuccessResponseData;
  warnings: Array<ApiSharedObjectc671832641>;
};

/** @internal */
export const NormalizedPurchase$inboundSchema: z.ZodMiniType<
  NormalizedPurchase,
  unknown
> = z.pipe(
  z.object({
    supplier_id: types.nullable(types.string()),
    voucher_type: types.number(),
    supplier_invoice_number: types.nullable(types.string()),
    invoice_date: types.nullable(types.string()),
    account_date: types.nullable(types.string()),
    due_date: types.nullable(types.string()),
    payment_term_id: types.nullable(ApiSharedEnumd34af90520$inboundSchema),
    import_document_role: types.nullable(ApiSharedEnum9e7af09974$inboundSchema),
    import_source_purchase_id: types.nullable(types.string()),
    import_nationalization_status: types.nullable(
      ApiSharedEnumf0d69c3d87$inboundSchema,
    ),
    customs_dispatch_number: types.nullable(types.string()),
    warehouse_id: types.nullable(types.string()),
    products_received: types.boolean(),
    update_product_variant_cost: types.boolean(),
    currency: ApiSharedEnum6cfb146157$inboundSchema,
    exchange_rate: types.number(),
    subtotal: types.nullable(types.number()),
    tax_amount: types.nullable(types.number()),
    total: types.nullable(types.number()),
    discount: types.nullable(types.number()),
    exempt_amount: types.nullable(types.number()),
    non_taxed_amount: types.nullable(types.number()),
    base_amount: types.nullable(types.number()),
    vat_perception_amount: types.nullable(types.number()),
    national_tax_amount: types.nullable(types.number()),
    gross_income_tax_amount: types.nullable(types.number()),
    municipal_tax_amount: types.nullable(types.number()),
    internal_tax_amount: types.nullable(types.number()),
    other_tax_amount: types.nullable(types.number()),
    notes: types.nullable(types.string()),
    pdf_path: types.nullable(types.string()),
    items: z.array(ApiSharedObjectedd0c22535$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "supplier_id": "supplierId",
      "voucher_type": "voucherType",
      "supplier_invoice_number": "supplierInvoiceNumber",
      "invoice_date": "invoiceDate",
      "account_date": "accountDate",
      "due_date": "dueDate",
      "payment_term_id": "paymentTermId",
      "import_document_role": "importDocumentRole",
      "import_source_purchase_id": "importSourcePurchaseId",
      "import_nationalization_status": "importNationalizationStatus",
      "customs_dispatch_number": "customsDispatchNumber",
      "warehouse_id": "warehouseId",
      "products_received": "productsReceived",
      "update_product_variant_cost": "updateProductVariantCost",
      "exchange_rate": "exchangeRate",
      "tax_amount": "taxAmount",
      "exempt_amount": "exemptAmount",
      "non_taxed_amount": "nonTaxedAmount",
      "base_amount": "baseAmount",
      "vat_perception_amount": "vatPerceptionAmount",
      "national_tax_amount": "nationalTaxAmount",
      "gross_income_tax_amount": "grossIncomeTaxAmount",
      "municipal_tax_amount": "municipalTaxAmount",
      "internal_tax_amount": "internalTaxAmount",
      "other_tax_amount": "otherTaxAmount",
      "pdf_path": "pdfPath",
    });
  }),
);

export function normalizedPurchaseFromJSON(
  jsonString: string,
): SafeParseResult<NormalizedPurchase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NormalizedPurchase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NormalizedPurchase' from JSON`,
  );
}

/** @internal */
export const ApiPurchaseTransactionSuccessResponseProjectedEffects$inboundSchema:
  z.ZodMiniType<
    ApiPurchaseTransactionSuccessResponseProjectedEffects,
    unknown
  > = z.object({
    inventory: ApiSharedObjectdafaa4a9ee$inboundSchema,
    accounting: ApiSharedObject3c43192c61$inboundSchema,
  });

export function apiPurchaseTransactionSuccessResponseProjectedEffectsFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiPurchaseTransactionSuccessResponseProjectedEffects,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiPurchaseTransactionSuccessResponseProjectedEffects$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiPurchaseTransactionSuccessResponseProjectedEffects' from JSON`,
  );
}

/** @internal */
export const ApiPurchaseTransactionSuccessResponseData$inboundSchema:
  z.ZodMiniType<ApiPurchaseTransactionSuccessResponseData, unknown> = z.pipe(
    z.object({
      purchase_id: types.string(),
      receipt_created: types.boolean(),
      idempotent_replay: types.boolean(),
      normalized_purchase: z.lazy(() => NormalizedPurchase$inboundSchema),
      projected_effects: z.lazy(() =>
        ApiPurchaseTransactionSuccessResponseProjectedEffects$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "purchase_id": "purchaseId",
        "receipt_created": "receiptCreated",
        "idempotent_replay": "idempotentReplay",
        "normalized_purchase": "normalizedPurchase",
        "projected_effects": "projectedEffects",
      });
    }),
  );

export function apiPurchaseTransactionSuccessResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiPurchaseTransactionSuccessResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiPurchaseTransactionSuccessResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiPurchaseTransactionSuccessResponseData' from JSON`,
  );
}

/** @internal */
export const ApiPurchaseTransactionSuccessResponse$inboundSchema: z.ZodMiniType<
  ApiPurchaseTransactionSuccessResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiPurchaseTransactionSuccessResponseData$inboundSchema),
    warnings: z.array(ApiSharedObjectc671832641$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiPurchaseTransactionSuccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiPurchaseTransactionSuccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiPurchaseTransactionSuccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiPurchaseTransactionSuccessResponse' from JSON`,
  );
}
