/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 060e0671e213
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnum1d20f1f7e9 = {
  Debit: "debit",
  Credit: "credit",
} as const;
export type ApiSharedEnum1d20f1f7e9 = OpenEnum<typeof ApiSharedEnum1d20f1f7e9>;

/** @internal */
export const ApiSharedEnum1d20f1f7e9$inboundSchema: z.ZodMiniType<
  ApiSharedEnum1d20f1f7e9,
  unknown
> = openEnums.inboundSchema(ApiSharedEnum1d20f1f7e9);
