/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 694a51b5f843
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnumcc76b6d63a,
  ApiSharedEnumcc76b6d63a$inboundSchema,
} from "./api-shared-enumcc76b6d63a.js";
import {
  ApiSharedObjectc0a969419d,
  ApiSharedObjectc0a969419d$inboundSchema,
} from "./api-shared-objectc0a969419d.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject061bc982d2 = {
  object: "order_preparation";
  id: string;
  preparedAt: Date;
  warehouseName: string;
  deliveryMethod: ApiSharedEnumcc76b6d63a;
  remitoDeliveryId: string | null;
  formattedRemitoNumber: string | null;
  lines: Array<ApiSharedObjectc0a969419d>;
};

/** @internal */
export const ApiSharedObject061bc982d2$inboundSchema: z.ZodMiniType<
  ApiSharedObject061bc982d2,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("order_preparation"),
    id: types.string(),
    prepared_at: types.date(),
    warehouse_name: types.string(),
    delivery_method: ApiSharedEnumcc76b6d63a$inboundSchema,
    remito_delivery_id: types.nullable(types.string()),
    formatted_remito_number: types.nullable(types.string()),
    lines: z.array(ApiSharedObjectc0a969419d$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "prepared_at": "preparedAt",
      "warehouse_name": "warehouseName",
      "delivery_method": "deliveryMethod",
      "remito_delivery_id": "remitoDeliveryId",
      "formatted_remito_number": "formattedRemitoNumber",
    });
  }),
);

export function apiSharedObject061bc982d2FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject061bc982d2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject061bc982d2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject061bc982d2' from JSON`,
  );
}
