/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dd8f595b6bf8
 */

import * as z from "zod/v4-mini";

export type Entry = {
  key: string;
  value: string | null;
};

export type ApiProductMetafieldPatchRequest = {
  entries: Array<Entry>;
};

/** @internal */
export type Entry$Outbound = {
  key: string;
  value: string | null;
};

/** @internal */
export const Entry$outboundSchema: z.ZodMiniType<Entry$Outbound, Entry> = z
  .object({
    key: z.string(),
    value: z.nullable(z.string()),
  });

export function entryToJSON(entry: Entry): string {
  return JSON.stringify(Entry$outboundSchema.parse(entry));
}

/** @internal */
export type ApiProductMetafieldPatchRequest$Outbound = {
  entries: Array<Entry$Outbound>;
};

/** @internal */
export const ApiProductMetafieldPatchRequest$outboundSchema: z.ZodMiniType<
  ApiProductMetafieldPatchRequest$Outbound,
  ApiProductMetafieldPatchRequest
> = z.object({
  entries: z.array(z.lazy(() => Entry$outboundSchema)),
});

export function apiProductMetafieldPatchRequestToJSON(
  apiProductMetafieldPatchRequest: ApiProductMetafieldPatchRequest,
): string {
  return JSON.stringify(
    ApiProductMetafieldPatchRequest$outboundSchema.parse(
      apiProductMetafieldPatchRequest,
    ),
  );
}
