/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: af35a8980705
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiPurchaseDetail,
  ApiPurchaseDetail$inboundSchema,
} from "./api-purchase-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiPurchaseDetailResponse = {
  requestId: string;
  data: ApiPurchaseDetail;
};

/** @internal */
export const ApiPurchaseDetailResponse$inboundSchema: z.ZodMiniType<
  ApiPurchaseDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: ApiPurchaseDetail$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiPurchaseDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiPurchaseDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiPurchaseDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiPurchaseDetailResponse' from JSON`,
  );
}
