/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ad0cb844af07
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObjectf86e1828bb,
  ApiSharedObjectf86e1828bb$inboundSchema,
} from "./api-shared-objectf86e1828bb.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiCategoryDetailResponse = {
  requestId: string;
  data: ApiSharedObjectf86e1828bb;
};

/** @internal */
export const ApiCategoryDetailResponse$inboundSchema: z.ZodMiniType<
  ApiCategoryDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: ApiSharedObjectf86e1828bb$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiCategoryDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiCategoryDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiCategoryDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiCategoryDetailResponse' from JSON`,
  );
}
