/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a95b4d8f673b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum1c9cda998e,
  ApiSharedEnum1c9cda998e$inboundSchema,
} from "./api-shared-enum1c9cda998e.js";
import {
  ApiSharedEnum4091526d90,
  ApiSharedEnum4091526d90$inboundSchema,
} from "./api-shared-enum4091526d90.js";
import {
  ApiSharedEnum4b017f6476,
  ApiSharedEnum4b017f6476$inboundSchema,
} from "./api-shared-enum4b017f6476.js";
import {
  ApiSharedEnum5f610d8b6a,
  ApiSharedEnum5f610d8b6a$inboundSchema,
} from "./api-shared-enum5f610d8b6a.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectd000e19b66 = {
  object: "webhook_endpoint";
  id: string;
  label: string;
  url: string;
  enabledEvents: Array<ApiSharedEnum4091526d90>;
  apiVersion: ApiSharedEnum5f610d8b6a;
  status: ApiSharedEnum1c9cda998e;
  ownerType: ApiSharedEnum4b017f6476;
  failureCount: number;
  lastSuccessAt: Date | null;
  lastFailureAt: Date | null;
  disabledAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const ApiSharedObjectd000e19b66$inboundSchema: z.ZodMiniType<
  ApiSharedObjectd000e19b66,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("webhook_endpoint"),
    id: types.string(),
    label: types.string(),
    url: types.string(),
    enabled_events: z.array(ApiSharedEnum4091526d90$inboundSchema),
    api_version: ApiSharedEnum5f610d8b6a$inboundSchema,
    status: ApiSharedEnum1c9cda998e$inboundSchema,
    owner_type: ApiSharedEnum4b017f6476$inboundSchema,
    failure_count: types.number(),
    last_success_at: types.nullable(types.date()),
    last_failure_at: types.nullable(types.date()),
    disabled_at: types.nullable(types.date()),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "enabled_events": "enabledEvents",
      "api_version": "apiVersion",
      "owner_type": "ownerType",
      "failure_count": "failureCount",
      "last_success_at": "lastSuccessAt",
      "last_failure_at": "lastFailureAt",
      "disabled_at": "disabledAt",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function apiSharedObjectd000e19b66FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectd000e19b66, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectd000e19b66$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectd000e19b66' from JSON`,
  );
}
