/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 178bf2fcd304
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiWarehouseDetailResponseData = {
  object: "warehouse";
  id: string;
  name: string;
  address: string | null;
  isDefault: boolean;
  isActive: boolean;
};

export type ApiWarehouseDetailResponse = {
  requestId: string;
  data: ApiWarehouseDetailResponseData;
};

/** @internal */
export const ApiWarehouseDetailResponseData$inboundSchema: z.ZodMiniType<
  ApiWarehouseDetailResponseData,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("warehouse"),
    id: types.string(),
    name: types.string(),
    address: types.nullable(types.string()),
    is_default: types.boolean(),
    is_active: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_default": "isDefault",
      "is_active": "isActive",
    });
  }),
);

export function apiWarehouseDetailResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiWarehouseDetailResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiWarehouseDetailResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiWarehouseDetailResponseData' from JSON`,
  );
}

/** @internal */
export const ApiWarehouseDetailResponse$inboundSchema: z.ZodMiniType<
  ApiWarehouseDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiWarehouseDetailResponseData$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiWarehouseDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiWarehouseDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiWarehouseDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiWarehouseDetailResponse' from JSON`,
  );
}
