/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9e58623cae9f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiSharedObject6dbe49c4ef,
  ApiSharedObject6dbe49c4ef$Outbound,
  ApiSharedObject6dbe49c4ef$outboundSchema,
} from "./api-shared-object6dbe49c4ef.js";

export const ApiProductMutationRequestVisibility = {
  Both: "both",
  Sales: "sales",
  Purchases: "purchases",
} as const;
export type ApiProductMutationRequestVisibility = ClosedEnum<
  typeof ApiProductMutationRequestVisibility
>;

export const ApiProductMutationRequestProductType = {
  Product: "product",
  Service: "service",
  Combo: "combo",
  Kit: "kit",
} as const;
export type ApiProductMutationRequestProductType = ClosedEnum<
  typeof ApiProductMutationRequestProductType
>;

export const ApiProductMutationRequestUnitOfMeasure = {
  Ten: "10",
  Eleven: "11",
  Twelve: "12",
  Thirteen: "13",
  Fourteen: "14",
  Fifteen: "15",
  Sixteen: "16",
  Seventeen: "17",
  Eighteen: "18",
  Nineteen: "19",
  Twenty: "20",
  TwentyOne: "21",
  TwentyTwo: "22",
  TwentyThree: "23",
  TwentyFour: "24",
  TwentyFive: "25",
  TwentySix: "26",
  TwentySeven: "27",
  TwentyEight: "28",
  TwentyNine: "29",
  Thirty: "30",
  ThirtyOne: "31",
  ThirtyTwo: "32",
  ThirtyThree: "33",
  ThirtyFour: "34",
  ThirtyFive: "35",
  ThirtySix: "36",
  ThirtySeven: "37",
  FortyOne: "41",
  FortySeven: "47",
  FortyEight: "48",
  FortyNine: "49",
  Fifty: "50",
  FiftyOne: "51",
  FiftyTwo: "52",
  FiftyThree: "53",
  FiftyFour: "54",
  FiftyFive: "55",
  SixtyOne: "61",
  SixtyTwo: "62",
  SixtyThree: "63",
  NinetySeven: "97",
  NinetyEight: "98",
  NinetyNine: "99",
  Zero: "00",
  One: "01",
  Two: "02",
  Three: "03",
  Four: "04",
  Five: "05",
  Six: "06",
  Seven: "07",
  Eight: "08",
  Nine: "09",
} as const;
export type ApiProductMutationRequestUnitOfMeasure = ClosedEnum<
  typeof ApiProductMutationRequestUnitOfMeasure
>;

export const ApiProductMutationRequestCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiProductMutationRequestCurrency = ClosedEnum<
  typeof ApiProductMutationRequestCurrency
>;

export type ApiProductMutationRequest = {
  name: string;
  description?: string | null | undefined;
  categoryId?: string | null | undefined;
  visibility?: ApiProductMutationRequestVisibility | undefined;
  imageUrl?: string | null | undefined;
  productType?: ApiProductMutationRequestProductType | undefined;
  sku: string;
  barcode?: string | null | undefined;
  unitOfMeasure?: ApiProductMutationRequestUnitOfMeasure | undefined;
  currency?: ApiProductMutationRequestCurrency | undefined;
  cost?: number | undefined;
  price?: number | undefined;
  promotionalPrice?: number | null | undefined;
  markupPercentage?: number | null | undefined;
  taxRateId?: number | undefined;
  isExempt?: boolean | undefined;
  defaultSupplierId?: string | null | undefined;
  defaultSalesAccountId?: string | null | undefined;
  defaultPurchaseAccountId?: string | null | undefined;
  warehouseStocks?: Array<ApiSharedObject6dbe49c4ef> | undefined;
  isActive?: boolean | undefined;
};

/** @internal */
export const ApiProductMutationRequestVisibility$outboundSchema: z.ZodMiniEnum<
  typeof ApiProductMutationRequestVisibility
> = z.enum(ApiProductMutationRequestVisibility);

/** @internal */
export const ApiProductMutationRequestProductType$outboundSchema: z.ZodMiniEnum<
  typeof ApiProductMutationRequestProductType
> = z.enum(ApiProductMutationRequestProductType);

/** @internal */
export const ApiProductMutationRequestUnitOfMeasure$outboundSchema:
  z.ZodMiniEnum<typeof ApiProductMutationRequestUnitOfMeasure> = z.enum(
    ApiProductMutationRequestUnitOfMeasure,
  );

/** @internal */
export const ApiProductMutationRequestCurrency$outboundSchema: z.ZodMiniEnum<
  typeof ApiProductMutationRequestCurrency
> = z.enum(ApiProductMutationRequestCurrency);

/** @internal */
export type ApiProductMutationRequest$Outbound = {
  name: string;
  description?: string | null | undefined;
  category_id?: string | null | undefined;
  visibility: string;
  image_url?: string | null | undefined;
  product_type: string;
  sku: string;
  barcode?: string | null | undefined;
  unit_of_measure: string;
  currency: string;
  cost: number;
  price?: number | undefined;
  promotional_price?: number | null | undefined;
  markup_percentage?: number | null | undefined;
  tax_rate_id: number;
  is_exempt: boolean;
  default_supplier_id?: string | null | undefined;
  default_sales_account_id?: string | null | undefined;
  default_purchase_account_id?: string | null | undefined;
  warehouse_stocks?: Array<ApiSharedObject6dbe49c4ef$Outbound> | undefined;
  is_active: boolean;
};

/** @internal */
export const ApiProductMutationRequest$outboundSchema: z.ZodMiniType<
  ApiProductMutationRequest$Outbound,
  ApiProductMutationRequest
> = z.pipe(
  z.object({
    name: z.string(),
    description: z.optional(z.nullable(z.string())),
    categoryId: z.optional(z.nullable(z.string())),
    visibility: z._default(
      ApiProductMutationRequestVisibility$outboundSchema,
      "both",
    ),
    imageUrl: z.optional(z.nullable(z.string())),
    productType: z._default(
      ApiProductMutationRequestProductType$outboundSchema,
      "product",
    ),
    sku: z.string(),
    barcode: z.optional(z.nullable(z.string())),
    unitOfMeasure: z._default(
      ApiProductMutationRequestUnitOfMeasure$outboundSchema,
      "07",
    ),
    currency: z._default(
      ApiProductMutationRequestCurrency$outboundSchema,
      "PES",
    ),
    cost: z._default(z.int(), 0),
    price: z.optional(z.int()),
    promotionalPrice: z.optional(z.nullable(z.int())),
    markupPercentage: z.optional(z.nullable(z.number())),
    taxRateId: z._default(z.int(), 5),
    isExempt: z._default(z.boolean(), false),
    defaultSupplierId: z.optional(z.nullable(z.string())),
    defaultSalesAccountId: z.optional(z.nullable(z.string())),
    defaultPurchaseAccountId: z.optional(z.nullable(z.string())),
    warehouseStocks: z.optional(
      z.array(ApiSharedObject6dbe49c4ef$outboundSchema),
    ),
    isActive: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      categoryId: "category_id",
      imageUrl: "image_url",
      productType: "product_type",
      unitOfMeasure: "unit_of_measure",
      promotionalPrice: "promotional_price",
      markupPercentage: "markup_percentage",
      taxRateId: "tax_rate_id",
      isExempt: "is_exempt",
      defaultSupplierId: "default_supplier_id",
      defaultSalesAccountId: "default_sales_account_id",
      defaultPurchaseAccountId: "default_purchase_account_id",
      warehouseStocks: "warehouse_stocks",
      isActive: "is_active",
    });
  }),
);

export function apiProductMutationRequestToJSON(
  apiProductMutationRequest: ApiProductMutationRequest,
): string {
  return JSON.stringify(
    ApiProductMutationRequest$outboundSchema.parse(apiProductMutationRequest),
  );
}
