/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e65b7913bf9f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum8d46e1ec20,
  ApiSharedEnum8d46e1ec20$inboundSchema,
} from "./api-shared-enum8d46e1ec20.js";
import {
  ApiSharedEnumfe93f70a59,
  ApiSharedEnumfe93f70a59$inboundSchema,
} from "./api-shared-enumfe93f70a59.js";
import {
  ApiSharedEnumff49232140,
  ApiSharedEnumff49232140$inboundSchema,
} from "./api-shared-enumff49232140.js";
import {
  ApiSharedObject8aeeceaf0f,
  ApiSharedObject8aeeceaf0f$inboundSchema,
} from "./api-shared-object8aeeceaf0f.js";
import {
  ApiSharedObjectee5eae48b0,
  ApiSharedObjectee5eae48b0$inboundSchema,
} from "./api-shared-objectee5eae48b0.js";
import {
  ApiSharedObjectfc277c542a,
  ApiSharedObjectfc277c542a$inboundSchema,
} from "./api-shared-objectfc277c542a.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiProductListResponseData = {
  id: string;
  name: string;
  description: string | null;
  category: ApiSharedObject8aeeceaf0f | null;
  sku: string;
  barcode: string | null;
  currency: string;
  cost: number;
  price: number;
  taxRate: ApiSharedObjectee5eae48b0;
  defaultSupplier: ApiSharedObject8aeeceaf0f | null;
  productType: ApiSharedEnumff49232140;
  isActive: boolean;
  organizationSlug: string;
  createdAt: Date;
  updatedAt: Date;
  effectivePrice?: number | undefined;
  priceSource?: ApiSharedEnumfe93f70a59 | undefined;
  appliedPriceList?: ApiSharedObjectfc277c542a | undefined;
  object: "product";
};

export type ApiProductListResponse = {
  requestId: string;
  data: Array<ApiProductListResponseData>;
  hasMore: boolean;
  nextCursor: string | null;
  /**
   * List-envelope discriminator.
   */
  object: ApiSharedEnum8d46e1ec20;
  /**
   * Requested list path.
   */
  url: string;
};

/** @internal */
export const ApiProductListResponseData$inboundSchema: z.ZodMiniType<
  ApiProductListResponseData,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    category: types.nullable(ApiSharedObject8aeeceaf0f$inboundSchema),
    sku: types.string(),
    barcode: types.nullable(types.string()),
    currency: types.string(),
    cost: types.number(),
    price: types.number(),
    tax_rate: ApiSharedObjectee5eae48b0$inboundSchema,
    default_supplier: types.nullable(ApiSharedObject8aeeceaf0f$inboundSchema),
    product_type: ApiSharedEnumff49232140$inboundSchema,
    is_active: types.boolean(),
    organization_slug: types.string(),
    created_at: types.date(),
    updated_at: types.date(),
    effective_price: types.optional(types.number()),
    price_source: types.optional(ApiSharedEnumfe93f70a59$inboundSchema),
    applied_price_list: types.optional(ApiSharedObjectfc277c542a$inboundSchema),
    object: types.literal("product"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tax_rate": "taxRate",
      "default_supplier": "defaultSupplier",
      "product_type": "productType",
      "is_active": "isActive",
      "organization_slug": "organizationSlug",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "effective_price": "effectivePrice",
      "price_source": "priceSource",
      "applied_price_list": "appliedPriceList",
    });
  }),
);

export function apiProductListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiProductListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiProductListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiProductListResponseData' from JSON`,
  );
}

/** @internal */
export const ApiProductListResponse$inboundSchema: z.ZodMiniType<
  ApiProductListResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.array(z.lazy(() => ApiProductListResponseData$inboundSchema)),
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    object: ApiSharedEnum8d46e1ec20$inboundSchema,
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function apiProductListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiProductListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiProductListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiProductListResponse' from JSON`,
  );
}
