/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 434918cf6596
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum2f67ddf0e8,
  ApiSharedEnum2f67ddf0e8$inboundSchema,
} from "./api-shared-enum2f67ddf0e8.js";
import {
  ApiSharedEnum4ac9200c4a,
  ApiSharedEnum4ac9200c4a$inboundSchema,
} from "./api-shared-enum4ac9200c4a.js";
import {
  ApiSharedEnumb49e56b125,
  ApiSharedEnumb49e56b125$inboundSchema,
} from "./api-shared-enumb49e56b125.js";
import {
  ApiSharedEnumffb4886f2b,
  ApiSharedEnumffb4886f2b$inboundSchema,
} from "./api-shared-enumffb4886f2b.js";
import {
  ApiSharedObject6e2450633e,
  ApiSharedObject6e2450633e$inboundSchema,
} from "./api-shared-object6e2450633e.js";
import {
  ApiSharedObject81e5b4b232,
  ApiSharedObject81e5b4b232$inboundSchema,
} from "./api-shared-object81e5b4b232.js";
import {
  ApiSharedObjectb74541d41a,
  ApiSharedObjectb74541d41a$inboundSchema,
} from "./api-shared-objectb74541d41a.js";
import {
  ApiSharedObjectc8647a846a,
  ApiSharedObjectc8647a846a$inboundSchema,
} from "./api-shared-objectc8647a846a.js";
import {
  ApiSharedObjectd4414f57ad,
  ApiSharedObjectd4414f57ad$inboundSchema,
} from "./api-shared-objectd4414f57ad.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject251954f6f7 = {
  object: "order";
  id: string;
  orderNumber: string;
  rawOrderNumber: number;
  orderDate: Date;
  customerId: string;
  customerName: string;
  customerTaxId: string | null;
  itemsCount: number;
  totalUnits: number;
  discountAmount: number;
  subtotal: number;
  taxAmount: number;
  total: number;
  currency: ApiSharedEnumffb4886f2b;
  orderStatus: ApiSharedEnum4ac9200c4a;
  preparationStatus: ApiSharedEnumb49e56b125;
  invoicingStatus: ApiSharedEnum2f67ddf0e8;
  notes: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdByName: string;
  createdBy: string;
  lineItems: Array<ApiSharedObjectb74541d41a>;
  activeWarehouses: Array<ApiSharedObject6e2450633e>;
  pendingPreparationWarehouseId: string | null;
  preparationGroups: Array<ApiSharedObjectc8647a846a>;
  preparations: Array<ApiSharedObject81e5b4b232>;
  invoices: Array<ApiSharedObjectd4414f57ad>;
};

/** @internal */
export const ApiSharedObject251954f6f7$inboundSchema: z.ZodMiniType<
  ApiSharedObject251954f6f7,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("order"),
    id: types.string(),
    order_number: types.string(),
    raw_order_number: types.number(),
    order_date: types.date(),
    customer_id: types.string(),
    customer_name: types.string(),
    customer_tax_id: types.nullable(types.string()),
    items_count: types.number(),
    total_units: types.number(),
    discount_amount: types.number(),
    subtotal: types.number(),
    tax_amount: types.number(),
    total: types.number(),
    currency: ApiSharedEnumffb4886f2b$inboundSchema,
    order_status: ApiSharedEnum4ac9200c4a$inboundSchema,
    preparation_status: ApiSharedEnumb49e56b125$inboundSchema,
    invoicing_status: ApiSharedEnum2f67ddf0e8$inboundSchema,
    notes: types.nullable(types.string()),
    created_at: types.date(),
    updated_at: types.date(),
    created_by_name: types.string(),
    created_by: types.string(),
    line_items: z.array(ApiSharedObjectb74541d41a$inboundSchema),
    active_warehouses: z.array(ApiSharedObject6e2450633e$inboundSchema),
    pending_preparation_warehouse_id: types.nullable(types.string()),
    preparation_groups: z.array(ApiSharedObjectc8647a846a$inboundSchema),
    preparations: z.array(ApiSharedObject81e5b4b232$inboundSchema),
    invoices: z.array(ApiSharedObjectd4414f57ad$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_number": "orderNumber",
      "raw_order_number": "rawOrderNumber",
      "order_date": "orderDate",
      "customer_id": "customerId",
      "customer_name": "customerName",
      "customer_tax_id": "customerTaxId",
      "items_count": "itemsCount",
      "total_units": "totalUnits",
      "discount_amount": "discountAmount",
      "tax_amount": "taxAmount",
      "order_status": "orderStatus",
      "preparation_status": "preparationStatus",
      "invoicing_status": "invoicingStatus",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "created_by_name": "createdByName",
      "created_by": "createdBy",
      "line_items": "lineItems",
      "active_warehouses": "activeWarehouses",
      "pending_preparation_warehouse_id": "pendingPreparationWarehouseId",
      "preparation_groups": "preparationGroups",
    });
  }),
);

export function apiSharedObject251954f6f7FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject251954f6f7, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject251954f6f7$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject251954f6f7' from JSON`,
  );
}
