/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6148494dd168
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject107feb8347,
  ApiSharedObject107feb8347$inboundSchema,
} from "./api-shared-object107feb8347.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiBankAccountDetailResponse = {
  requestId: string;
  data: ApiSharedObject107feb8347;
};

/** @internal */
export const ApiBankAccountDetailResponse$inboundSchema: z.ZodMiniType<
  ApiBankAccountDetailResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: ApiSharedObject107feb8347$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiBankAccountDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiBankAccountDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiBankAccountDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiBankAccountDetailResponse' from JSON`,
  );
}
