/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cf6edca28f50
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObjectc2334370b5,
  ApiSharedObjectc2334370b5$inboundSchema,
} from "./api-shared-objectc2334370b5.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject5138d6f7d8 = {
  id: string;
  productId: string;
  quantity: number;
  receivedQuantity: number;
  rejectedQuantity: number;
  product: ApiSharedObjectc2334370b5;
};

/** @internal */
export const ApiSharedObject5138d6f7d8$inboundSchema: z.ZodMiniType<
  ApiSharedObject5138d6f7d8,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    product_id: types.string(),
    quantity: types.number(),
    received_quantity: types.number(),
    rejected_quantity: types.number(),
    product: ApiSharedObjectc2334370b5$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "product_id": "productId",
      "received_quantity": "receivedQuantity",
      "rejected_quantity": "rejectedQuantity",
    });
  }),
);

export function apiSharedObject5138d6f7d8FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject5138d6f7d8, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject5138d6f7d8$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject5138d6f7d8' from JSON`,
  );
}
