/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 76d1f831f011
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ApiSupplierPaymentListResponseCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiSupplierPaymentListResponseCurrency = OpenEnum<
  typeof ApiSupplierPaymentListResponseCurrency
>;

export type ApiSupplierPaymentListResponsePaymentMethod = {
  id: string;
  name: string;
  icon: string | null;
};

export type ApiSupplierPaymentListResponseRelatedEntity = {
  id: string;
  name: string | null;
  number: string | null;
};

export type ApiSupplierPaymentListResponseCreatedBy = {
  id: string;
  name: string | null;
};

export type ApiSupplierPaymentListResponseData = {
  id: string;
  paymentDate: string;
  amount: number;
  balance: number;
  formattedPaymentNumber: string | null;
  currency: ApiSupplierPaymentListResponseCurrency;
  paymentMethod: ApiSupplierPaymentListResponsePaymentMethod | null;
  paymentMethodCount: number;
  relatedEntity: ApiSupplierPaymentListResponseRelatedEntity | null;
  createdBy: ApiSupplierPaymentListResponseCreatedBy | null;
  createdAt: Date;
  createdAtCursor: string;
  updatedAt: Date;
  purchaseCount?: number | undefined;
};

/**
 * List-envelope discriminator.
 */
export const ApiSupplierPaymentListResponseObject = {
  List: "list",
} as const;
/**
 * List-envelope discriminator.
 */
export type ApiSupplierPaymentListResponseObject = ClosedEnum<
  typeof ApiSupplierPaymentListResponseObject
>;

export type ApiSupplierPaymentListResponse = {
  requestId: string;
  data: Array<ApiSupplierPaymentListResponseData>;
  hasMore: boolean;
  nextCursor: string | null;
  /**
   * List-envelope discriminator.
   */
  object: ApiSupplierPaymentListResponseObject;
  /**
   * Requested list path.
   */
  url: string;
};

/** @internal */
export const ApiSupplierPaymentListResponseCurrency$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentListResponseCurrency, unknown> = openEnums
    .inboundSchema(ApiSupplierPaymentListResponseCurrency);

/** @internal */
export const ApiSupplierPaymentListResponsePaymentMethod$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentListResponsePaymentMethod, unknown> = z
    .object({
      id: types.string(),
      name: types.string(),
      icon: types.nullable(types.string()),
    });

export function apiSupplierPaymentListResponsePaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentListResponsePaymentMethod,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentListResponsePaymentMethod$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentListResponsePaymentMethod' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentListResponseRelatedEntity$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentListResponseRelatedEntity, unknown> = z
    .object({
      id: types.string(),
      name: types.nullable(types.string()),
      number: types.nullable(types.string()),
    });

export function apiSupplierPaymentListResponseRelatedEntityFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentListResponseRelatedEntity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentListResponseRelatedEntity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentListResponseRelatedEntity' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentListResponseCreatedBy$inboundSchema:
  z.ZodMiniType<ApiSupplierPaymentListResponseCreatedBy, unknown> = z.object({
    id: types.string(),
    name: types.nullable(types.string()),
  });

export function apiSupplierPaymentListResponseCreatedByFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiSupplierPaymentListResponseCreatedBy,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentListResponseCreatedBy$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiSupplierPaymentListResponseCreatedBy' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentListResponseData$inboundSchema: z.ZodMiniType<
  ApiSupplierPaymentListResponseData,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    payment_date: types.string(),
    amount: types.number(),
    balance: types.number(),
    formatted_payment_number: types.nullable(types.string()),
    currency: ApiSupplierPaymentListResponseCurrency$inboundSchema,
    payment_method: types.nullable(
      z.lazy(() => ApiSupplierPaymentListResponsePaymentMethod$inboundSchema),
    ),
    payment_method_count: types.number(),
    related_entity: types.nullable(
      z.lazy(() => ApiSupplierPaymentListResponseRelatedEntity$inboundSchema),
    ),
    created_by: types.nullable(
      z.lazy(() => ApiSupplierPaymentListResponseCreatedBy$inboundSchema),
    ),
    created_at: types.date(),
    created_at_cursor: types.string(),
    updated_at: types.date(),
    purchase_count: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_date": "paymentDate",
      "formatted_payment_number": "formattedPaymentNumber",
      "payment_method": "paymentMethod",
      "payment_method_count": "paymentMethodCount",
      "related_entity": "relatedEntity",
      "created_by": "createdBy",
      "created_at": "createdAt",
      "created_at_cursor": "createdAtCursor",
      "updated_at": "updatedAt",
      "purchase_count": "purchaseCount",
    });
  }),
);

export function apiSupplierPaymentListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierPaymentListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiSupplierPaymentListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierPaymentListResponseData' from JSON`,
  );
}

/** @internal */
export const ApiSupplierPaymentListResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof ApiSupplierPaymentListResponseObject
> = z.enum(ApiSupplierPaymentListResponseObject);

/** @internal */
export const ApiSupplierPaymentListResponse$inboundSchema: z.ZodMiniType<
  ApiSupplierPaymentListResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.array(
      z.lazy(() => ApiSupplierPaymentListResponseData$inboundSchema),
    ),
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
    object: ApiSupplierPaymentListResponseObject$inboundSchema,
    url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function apiSupplierPaymentListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierPaymentListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSupplierPaymentListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierPaymentListResponse' from JSON`,
  );
}
