/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4838b334916
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject05f64e43bb,
  ApiSharedObject05f64e43bb$inboundSchema,
} from "./api-shared-object05f64e43bb.js";
import {
  ApiSharedObject5a978938b1,
  ApiSharedObject5a978938b1$inboundSchema,
} from "./api-shared-object5a978938b1.js";
import {
  ApiSharedObject738aa6c207,
  ApiSharedObject738aa6c207$inboundSchema,
} from "./api-shared-object738aa6c207.js";
import {
  ApiSharedObjectc15d6ab2fa,
  ApiSharedObjectc15d6ab2fa$inboundSchema,
} from "./api-shared-objectc15d6ab2fa.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiDeliveryNoteListResponseOrigin =
  | ApiSharedObjectc15d6ab2fa
  | ApiSharedObject5a978938b1
  | ApiSharedObject05f64e43bb
  | discriminatedUnionTypes.Unknown<"type">;

export type ApiDeliveryNoteListResponseData = {
  object: "delivery_note";
  id: string;
  number: string | null;
  date: Date;
  customer: ApiSharedObject738aa6c207 | null;
  origin:
    | ApiSharedObjectc15d6ab2fa
    | ApiSharedObject5a978938b1
    | ApiSharedObject05f64e43bb
    | discriminatedUnionTypes.Unknown<"type">;
  createdAt: Date;
};

export type ApiDeliveryNoteListResponse = {
  requestId: string;
  object: "list";
  url: string;
  data: Array<ApiDeliveryNoteListResponseData>;
  hasMore: boolean;
  nextCursor: string | null;
};

/** @internal */
export const ApiDeliveryNoteListResponseOrigin$inboundSchema: z.ZodMiniType<
  ApiDeliveryNoteListResponseOrigin,
  unknown
> = discriminatedUnion("type", {
  sale: ApiSharedObjectc15d6ab2fa$inboundSchema,
  fulfillment: ApiSharedObject5a978938b1$inboundSchema,
  custom: ApiSharedObject05f64e43bb$inboundSchema,
});

export function apiDeliveryNoteListResponseOriginFromJSON(
  jsonString: string,
): SafeParseResult<ApiDeliveryNoteListResponseOrigin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiDeliveryNoteListResponseOrigin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiDeliveryNoteListResponseOrigin' from JSON`,
  );
}

/** @internal */
export const ApiDeliveryNoteListResponseData$inboundSchema: z.ZodMiniType<
  ApiDeliveryNoteListResponseData,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("delivery_note"),
    id: types.string(),
    number: types.nullable(types.string()),
    date: types.date(),
    customer: types.nullable(ApiSharedObject738aa6c207$inboundSchema),
    origin: discriminatedUnion("type", {
      sale: ApiSharedObjectc15d6ab2fa$inboundSchema,
      fulfillment: ApiSharedObject5a978938b1$inboundSchema,
      custom: ApiSharedObject05f64e43bb$inboundSchema,
    }),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function apiDeliveryNoteListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiDeliveryNoteListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiDeliveryNoteListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiDeliveryNoteListResponseData' from JSON`,
  );
}

/** @internal */
export const ApiDeliveryNoteListResponse$inboundSchema: z.ZodMiniType<
  ApiDeliveryNoteListResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    object: types.literal("list"),
    url: types.string(),
    data: z.array(z.lazy(() => ApiDeliveryNoteListResponseData$inboundSchema)),
    has_more: types.boolean(),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "has_more": "hasMore",
      "next_cursor": "nextCursor",
    });
  }),
);

export function apiDeliveryNoteListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiDeliveryNoteListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiDeliveryNoteListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiDeliveryNoteListResponse' from JSON`,
  );
}
