/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b65aa023abee
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnumfe93f70a59,
  ApiSharedEnumfe93f70a59$inboundSchema,
} from "./api-shared-enumfe93f70a59.js";
import {
  ApiSharedEnumff49232140,
  ApiSharedEnumff49232140$inboundSchema,
} from "./api-shared-enumff49232140.js";
import {
  ApiSharedObject0347948139,
  ApiSharedObject0347948139$inboundSchema,
} from "./api-shared-object0347948139.js";
import {
  ApiSharedObject8a94344083,
  ApiSharedObject8a94344083$inboundSchema,
} from "./api-shared-object8a94344083.js";
import {
  ApiSharedObject8aeeceaf0f,
  ApiSharedObject8aeeceaf0f$inboundSchema,
} from "./api-shared-object8aeeceaf0f.js";
import {
  ApiSharedObjecta9f7340006,
  ApiSharedObjecta9f7340006$inboundSchema,
} from "./api-shared-objecta9f7340006.js";
import {
  ApiSharedObjectc1ee297650,
  ApiSharedObjectc1ee297650$inboundSchema,
} from "./api-shared-objectc1ee297650.js";
import {
  ApiSharedObjectee5eae48b0,
  ApiSharedObjectee5eae48b0$inboundSchema,
} from "./api-shared-objectee5eae48b0.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject2ca3c1ad56 = {
  id: string;
  name: string;
  description: string | null;
  category: ApiSharedObject8aeeceaf0f | null;
  sku: string;
  barcode: string | null;
  /**
   * External product image URL reference. La Pyme displays it best effort and does not copy, ingest, or host the image.
   */
  imageUrl: string | null;
  currency: string;
  cost: number;
  price: number;
  taxRate: ApiSharedObjectee5eae48b0;
  defaultSupplier: ApiSharedObject8aeeceaf0f | null;
  productType: ApiSharedEnumff49232140;
  isActive: boolean;
  organizationSlug: string;
  createdAt: Date;
  updatedAt: Date;
  effectivePrice?: number | undefined;
  priceSource?: ApiSharedEnumfe93f70a59 | undefined;
  appliedPriceList?: ApiSharedObjectc1ee297650 | undefined;
  object: "product";
  tags: Array<ApiSharedObject8a94344083>;
  variantGroupId: string;
  variantOptions: { [k: string]: string } | null;
  isExempt: boolean;
  metafields: Array<ApiSharedObject0347948139>;
  stockSummary: ApiSharedObjecta9f7340006;
};

/** @internal */
export const ApiSharedObject2ca3c1ad56$inboundSchema: z.ZodMiniType<
  ApiSharedObject2ca3c1ad56,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    category: types.nullable(ApiSharedObject8aeeceaf0f$inboundSchema),
    sku: types.string(),
    barcode: types.nullable(types.string()),
    image_url: types.nullable(types.string()),
    currency: types.string(),
    cost: types.number(),
    price: types.number(),
    tax_rate: ApiSharedObjectee5eae48b0$inboundSchema,
    default_supplier: types.nullable(ApiSharedObject8aeeceaf0f$inboundSchema),
    product_type: ApiSharedEnumff49232140$inboundSchema,
    is_active: types.boolean(),
    organization_slug: types.string(),
    created_at: types.date(),
    updated_at: types.date(),
    effective_price: types.optional(types.number()),
    price_source: types.optional(ApiSharedEnumfe93f70a59$inboundSchema),
    applied_price_list: types.optional(ApiSharedObjectc1ee297650$inboundSchema),
    object: types.literal("product"),
    tags: z.array(ApiSharedObject8a94344083$inboundSchema),
    variant_group_id: types.string(),
    variant_options: types.nullable(z.record(z.string(), types.string())),
    is_exempt: types.boolean(),
    metafields: z.array(ApiSharedObject0347948139$inboundSchema),
    stock_summary: ApiSharedObjecta9f7340006$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
      "tax_rate": "taxRate",
      "default_supplier": "defaultSupplier",
      "product_type": "productType",
      "is_active": "isActive",
      "organization_slug": "organizationSlug",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "effective_price": "effectivePrice",
      "price_source": "priceSource",
      "applied_price_list": "appliedPriceList",
      "variant_group_id": "variantGroupId",
      "variant_options": "variantOptions",
      "is_exempt": "isExempt",
      "stock_summary": "stockSummary",
    });
  }),
);

export function apiSharedObject2ca3c1ad56FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject2ca3c1ad56, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject2ca3c1ad56$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject2ca3c1ad56' from JSON`,
  );
}
