/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2e3c1c4e95af
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject21f30ba9b5,
  ApiSharedObject21f30ba9b5$inboundSchema,
} from "./api-shared-object21f30ba9b5.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiWebhookEndpointResponse = {
  requestId: string;
  data: ApiSharedObject21f30ba9b5;
};

/** @internal */
export const ApiWebhookEndpointResponse$inboundSchema: z.ZodMiniType<
  ApiWebhookEndpointResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: ApiSharedObject21f30ba9b5$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiWebhookEndpointResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiWebhookEndpointResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiWebhookEndpointResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiWebhookEndpointResponse' from JSON`,
  );
}
