/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f15b3148b401
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject6e2450633e = {
  id: string;
  name: string;
  isDefault: boolean;
};

/** @internal */
export const ApiSharedObject6e2450633e$inboundSchema: z.ZodMiniType<
  ApiSharedObject6e2450633e,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    is_default: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_default": "isDefault",
    });
  }),
);

export function apiSharedObject6e2450633eFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject6e2450633e, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject6e2450633e$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject6e2450633e' from JSON`,
  );
}
