/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b7f8ac8e0c1c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnumffb4886f2b,
  ApiSharedEnumffb4886f2b$inboundSchema,
} from "./api-shared-enumffb4886f2b.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectc482130d79 = {
  willCreateJournalEntry: boolean;
  currency: ApiSharedEnumffb4886f2b;
  exchangeRate: number;
};

/** @internal */
export const ApiSharedObjectc482130d79$inboundSchema: z.ZodMiniType<
  ApiSharedObjectc482130d79,
  unknown
> = z.pipe(
  z.object({
    will_create_journal_entry: types.boolean(),
    currency: ApiSharedEnumffb4886f2b$inboundSchema,
    exchange_rate: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "will_create_journal_entry": "willCreateJournalEntry",
      "exchange_rate": "exchangeRate",
    });
  }),
);

export function apiSharedObjectc482130d79FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectc482130d79, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectc482130d79$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectc482130d79' from JSON`,
  );
}
