/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: df3a6fa38f09
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnuma7f3605118 = {
  Both: "both",
  Sales: "sales",
  Purchases: "purchases",
  System: "system",
} as const;
export type ApiSharedEnuma7f3605118 = OpenEnum<typeof ApiSharedEnuma7f3605118>;

/** @internal */
export const ApiSharedEnuma7f3605118$inboundSchema: z.ZodMiniType<
  ApiSharedEnuma7f3605118,
  unknown
> = openEnums.inboundSchema(ApiSharedEnuma7f3605118);
/** @internal */
export const ApiSharedEnuma7f3605118$outboundSchema: z.ZodMiniType<
  string,
  ApiSharedEnuma7f3605118
> = openEnums.outboundSchema(ApiSharedEnuma7f3605118);
