/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 785b8f1c76e1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObjecta3133edce3,
  ApiSharedObjecta3133edce3$inboundSchema,
} from "./api-shared-objecta3133edce3.js";
import {
  ApiSharedObjectf2ec33bd59,
  ApiSharedObjectf2ec33bd59$inboundSchema,
} from "./api-shared-objectf2ec33bd59.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObjectb990586284 = {
  object: "price_list_price";
  priceListId: string;
  productId: string;
  currency: "ARS";
  taxInclusive: boolean;
  taxRate: ApiSharedObjecta3133edce3;
  isExempt: boolean;
  calculation: ApiSharedObjectf2ec33bd59;
  status: "priced";
  unitPrice: number;
};

/** @internal */
export const ApiSharedObjectb990586284$inboundSchema: z.ZodMiniType<
  ApiSharedObjectb990586284,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("price_list_price"),
    price_list_id: types.string(),
    product_id: types.string(),
    currency: types.literal("ARS"),
    tax_inclusive: types.boolean(),
    tax_rate: ApiSharedObjecta3133edce3$inboundSchema,
    is_exempt: types.boolean(),
    calculation: ApiSharedObjectf2ec33bd59$inboundSchema,
    status: types.literal("priced"),
    unit_price: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "price_list_id": "priceListId",
      "product_id": "productId",
      "tax_inclusive": "taxInclusive",
      "tax_rate": "taxRate",
      "is_exempt": "isExempt",
      "unit_price": "unitPrice",
    });
  }),
);

export function apiSharedObjectb990586284FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObjectb990586284, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObjectb990586284$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObjectb990586284' from JSON`,
  );
}
