/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7b4d050f7fda
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnum07ee8fd91e = {
  Sales: "sales",
  Purchases: "purchases",
  Payments: "payments",
  Inventory: "inventory",
} as const;
export type ApiSharedEnum07ee8fd91e = OpenEnum<typeof ApiSharedEnum07ee8fd91e>;

/** @internal */
export const ApiSharedEnum07ee8fd91e$inboundSchema: z.ZodMiniType<
  ApiSharedEnum07ee8fd91e,
  unknown
> = openEnums.inboundSchema(ApiSharedEnum07ee8fd91e);
