/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3bfc3f6e217a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObject73a9297be0,
  ApiSharedObject73a9297be0$inboundSchema,
} from "./api-shared-object73a9297be0.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiPaymentMethodUpdateResponseData = {
  paymentMethod: ApiSharedObject73a9297be0;
};

export type ApiPaymentMethodUpdateResponse = {
  requestId: string;
  data: ApiPaymentMethodUpdateResponseData;
  warnings: Array<any>;
};

/** @internal */
export const ApiPaymentMethodUpdateResponseData$inboundSchema: z.ZodMiniType<
  ApiPaymentMethodUpdateResponseData,
  unknown
> = z.pipe(
  z.object({
    payment_method: ApiSharedObject73a9297be0$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_method": "paymentMethod",
    });
  }),
);

export function apiPaymentMethodUpdateResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiPaymentMethodUpdateResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiPaymentMethodUpdateResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiPaymentMethodUpdateResponseData' from JSON`,
  );
}

/** @internal */
export const ApiPaymentMethodUpdateResponse$inboundSchema: z.ZodMiniType<
  ApiPaymentMethodUpdateResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiPaymentMethodUpdateResponseData$inboundSchema),
    warnings: z.array(z.any()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiPaymentMethodUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiPaymentMethodUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiPaymentMethodUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiPaymentMethodUpdateResponse' from JSON`,
  );
}
