/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7f946c0ee986
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiSharedEnumffb4886f2b,
  ApiSharedEnumffb4886f2b$outboundSchema,
} from "./api-shared-enumffb4886f2b.js";
import {
  ApiSharedObject06b16aade1,
  ApiSharedObject06b16aade1$Outbound,
  ApiSharedObject06b16aade1$outboundSchema,
} from "./api-shared-object06b16aade1.js";

export const CurrencyChangeMode = {
  Keep: "keep",
  Convert: "convert",
} as const;
export type CurrencyChangeMode = ClosedEnum<typeof CurrencyChangeMode>;

export type DiscountPercentage = {
  type: "percentage";
  value: number;
};

export type ApiQuoteRequestDiscountUnion =
  | DiscountPercentage
  | ApiSharedObject06b16aade1;

export type ApiQuoteRequestItem = {
  productId: string;
  warehouseId?: string | null | undefined;
  quantity: number;
  unitPrice: number;
  discount?: DiscountPercentage | ApiSharedObject06b16aade1 | undefined;
};

export type Reservation = {
  enabled: boolean;
  reservedThroughDate?: Date | undefined;
};

export type ApiQuoteRequest = {
  customerId: string;
  currency?: ApiSharedEnumffb4886f2b | undefined;
  pricingArsPerUsdRate?: number | undefined;
  currencyChangeMode?: CurrencyChangeMode | undefined;
  priceListId?: string | null | undefined;
  salespersonMemberId?: string | null | undefined;
  items: Array<ApiQuoteRequestItem>;
  expiresAt?: Date | null | undefined;
  globalDiscountAmount?: number | undefined;
  notes?: string | null | undefined;
  reservation?: Reservation | undefined;
};

/** @internal */
export const CurrencyChangeMode$outboundSchema: z.ZodMiniEnum<
  typeof CurrencyChangeMode
> = z.enum(CurrencyChangeMode);

/** @internal */
export type DiscountPercentage$Outbound = {
  type: "percentage";
  value: number;
};

/** @internal */
export const DiscountPercentage$outboundSchema: z.ZodMiniType<
  DiscountPercentage$Outbound,
  DiscountPercentage
> = z.object({
  type: z.literal("percentage"),
  value: z.number(),
});

export function discountPercentageToJSON(
  discountPercentage: DiscountPercentage,
): string {
  return JSON.stringify(
    DiscountPercentage$outboundSchema.parse(discountPercentage),
  );
}

/** @internal */
export type ApiQuoteRequestDiscountUnion$Outbound =
  | DiscountPercentage$Outbound
  | ApiSharedObject06b16aade1$Outbound;

/** @internal */
export const ApiQuoteRequestDiscountUnion$outboundSchema: z.ZodMiniType<
  ApiQuoteRequestDiscountUnion$Outbound,
  ApiQuoteRequestDiscountUnion
> = z.union([
  z.lazy(() => DiscountPercentage$outboundSchema),
  ApiSharedObject06b16aade1$outboundSchema,
]);

export function apiQuoteRequestDiscountUnionToJSON(
  apiQuoteRequestDiscountUnion: ApiQuoteRequestDiscountUnion,
): string {
  return JSON.stringify(
    ApiQuoteRequestDiscountUnion$outboundSchema.parse(
      apiQuoteRequestDiscountUnion,
    ),
  );
}

/** @internal */
export type ApiQuoteRequestItem$Outbound = {
  product_id: string;
  warehouse_id?: string | null | undefined;
  quantity: number;
  unit_price: number;
  discount?:
    | DiscountPercentage$Outbound
    | ApiSharedObject06b16aade1$Outbound
    | undefined;
};

/** @internal */
export const ApiQuoteRequestItem$outboundSchema: z.ZodMiniType<
  ApiQuoteRequestItem$Outbound,
  ApiQuoteRequestItem
> = z.pipe(
  z.object({
    productId: z.string(),
    warehouseId: z.optional(z.nullable(z.string())),
    quantity: z.int(),
    unitPrice: z.int(),
    discount: z.optional(z.union([
      z.lazy(() => DiscountPercentage$outboundSchema),
      ApiSharedObject06b16aade1$outboundSchema,
    ])),
  }),
  z.transform((v) => {
    return remap$(v, {
      productId: "product_id",
      warehouseId: "warehouse_id",
      unitPrice: "unit_price",
    });
  }),
);

export function apiQuoteRequestItemToJSON(
  apiQuoteRequestItem: ApiQuoteRequestItem,
): string {
  return JSON.stringify(
    ApiQuoteRequestItem$outboundSchema.parse(apiQuoteRequestItem),
  );
}

/** @internal */
export type Reservation$Outbound = {
  enabled: boolean;
  reserved_through_date?: string | undefined;
};

/** @internal */
export const Reservation$outboundSchema: z.ZodMiniType<
  Reservation$Outbound,
  Reservation
> = z.pipe(
  z.object({
    enabled: z.boolean(),
    reservedThroughDate: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
  }),
  z.transform((v) => {
    return remap$(v, {
      reservedThroughDate: "reserved_through_date",
    });
  }),
);

export function reservationToJSON(reservation: Reservation): string {
  return JSON.stringify(Reservation$outboundSchema.parse(reservation));
}

/** @internal */
export type ApiQuoteRequest$Outbound = {
  customer_id: string;
  currency?: string | undefined;
  pricing_ars_per_usd_rate?: number | undefined;
  currency_change_mode?: string | undefined;
  price_list_id?: string | null | undefined;
  salesperson_member_id?: string | null | undefined;
  items: Array<ApiQuoteRequestItem$Outbound>;
  expires_at?: string | null | undefined;
  global_discount_amount?: number | undefined;
  notes?: string | null | undefined;
  reservation?: Reservation$Outbound | undefined;
};

/** @internal */
export const ApiQuoteRequest$outboundSchema: z.ZodMiniType<
  ApiQuoteRequest$Outbound,
  ApiQuoteRequest
> = z.pipe(
  z.object({
    customerId: z.string(),
    currency: z.optional(ApiSharedEnumffb4886f2b$outboundSchema),
    pricingArsPerUsdRate: z.optional(z.number()),
    currencyChangeMode: z.optional(CurrencyChangeMode$outboundSchema),
    priceListId: z.optional(z.nullable(z.string())),
    salespersonMemberId: z.optional(z.nullable(z.string())),
    items: z.array(z.lazy(() => ApiQuoteRequestItem$outboundSchema)),
    expiresAt: z.optional(z.nullable(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ))),
    globalDiscountAmount: z.optional(z.int()),
    notes: z.optional(z.nullable(z.string())),
    reservation: z.optional(z.lazy(() =>
      Reservation$outboundSchema
    )),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerId: "customer_id",
      pricingArsPerUsdRate: "pricing_ars_per_usd_rate",
      currencyChangeMode: "currency_change_mode",
      priceListId: "price_list_id",
      salespersonMemberId: "salesperson_member_id",
      expiresAt: "expires_at",
      globalDiscountAmount: "global_discount_amount",
    });
  }),
);

export function apiQuoteRequestToJSON(
  apiQuoteRequest: ApiQuoteRequest,
): string {
  return JSON.stringify(ApiQuoteRequest$outboundSchema.parse(apiQuoteRequest));
}
