/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3c948d47e13b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum19a9b49403,
  ApiSharedEnum19a9b49403$inboundSchema,
} from "./api-shared-enum19a9b49403.js";
import {
  ApiSharedEnumcc76b6d63a,
  ApiSharedEnumcc76b6d63a$inboundSchema,
} from "./api-shared-enumcc76b6d63a.js";
import {
  ApiSharedObject7d7d99f458,
  ApiSharedObject7d7d99f458$inboundSchema,
} from "./api-shared-object7d7d99f458.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject7f109ef840 = {
  object: "fulfillment_order";
  id: string;
  status: ApiSharedEnum19a9b49403;
  assignedWarehouseId: string;
  assignedWarehouseName: string | null;
  deliveryMethod: ApiSharedEnumcc76b6d63a;
  requestedAt: Date;
  startedAt: Date | null;
  closedAt: Date | null;
  cancelledAt: Date | null;
  notes: string | null;
  lines: Array<ApiSharedObject7d7d99f458>;
};

/** @internal */
export const ApiSharedObject7f109ef840$inboundSchema: z.ZodMiniType<
  ApiSharedObject7f109ef840,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("fulfillment_order"),
    id: types.string(),
    status: ApiSharedEnum19a9b49403$inboundSchema,
    assigned_warehouse_id: types.string(),
    assigned_warehouse_name: types.nullable(types.string()),
    delivery_method: ApiSharedEnumcc76b6d63a$inboundSchema,
    requested_at: types.date(),
    started_at: types.nullable(types.date()),
    closed_at: types.nullable(types.date()),
    cancelled_at: types.nullable(types.date()),
    notes: types.nullable(types.string()),
    lines: z.array(ApiSharedObject7d7d99f458$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "assigned_warehouse_id": "assignedWarehouseId",
      "assigned_warehouse_name": "assignedWarehouseName",
      "delivery_method": "deliveryMethod",
      "requested_at": "requestedAt",
      "started_at": "startedAt",
      "closed_at": "closedAt",
      "cancelled_at": "cancelledAt",
    });
  }),
);

export function apiSharedObject7f109ef840FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject7f109ef840, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject7f109ef840$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject7f109ef840' from JSON`,
  );
}
