/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d0da7c82ebc
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ApiSharedObjectac8b0c51cd,
  ApiSharedObjectac8b0c51cd$Outbound,
  ApiSharedObjectac8b0c51cd$outboundSchema,
} from "./api-shared-objectac8b0c51cd.js";

export type ApiSharedObject9e584e0f8a = {
  paymentMethodId: string;
  amount: number;
  reference?: string | undefined;
  cardBrand?: string | undefined;
  cardBatchNumber?: string | undefined;
  cardCouponNumber?: string | undefined;
  cardInstallmentPlanCode?: string | undefined;
  notes?: string | undefined;
  feeAmount?: number | undefined;
  feePercentageApplied?: string | undefined;
  feeFixedApplied?: number | undefined;
  netAmount?: number | undefined;
  checkId?: string | undefined;
  checkData?: ApiSharedObjectac8b0c51cd | undefined;
  registerId?: string | undefined;
  safeId?: string | undefined;
};

/** @internal */
export type ApiSharedObject9e584e0f8a$Outbound = {
  payment_method_id: string;
  amount: number;
  reference?: string | undefined;
  card_brand?: string | undefined;
  card_batch_number?: string | undefined;
  card_coupon_number?: string | undefined;
  card_installment_plan_code?: string | undefined;
  notes?: string | undefined;
  fee_amount?: number | undefined;
  fee_percentage_applied?: string | undefined;
  fee_fixed_applied?: number | undefined;
  net_amount?: number | undefined;
  check_id?: string | undefined;
  check_data?: ApiSharedObjectac8b0c51cd$Outbound | undefined;
  register_id?: string | undefined;
  safe_id?: string | undefined;
};

/** @internal */
export const ApiSharedObject9e584e0f8a$outboundSchema: z.ZodMiniType<
  ApiSharedObject9e584e0f8a$Outbound,
  ApiSharedObject9e584e0f8a
> = z.pipe(
  z.object({
    paymentMethodId: z.string(),
    amount: z.int(),
    reference: z.optional(z.string()),
    cardBrand: z.optional(z.string()),
    cardBatchNumber: z.optional(z.string()),
    cardCouponNumber: z.optional(z.string()),
    cardInstallmentPlanCode: z.optional(z.string()),
    notes: z.optional(z.string()),
    feeAmount: z.optional(z.int()),
    feePercentageApplied: z.optional(z.string()),
    feeFixedApplied: z.optional(z.int()),
    netAmount: z.optional(z.int()),
    checkId: z.optional(z.string()),
    checkData: z.optional(ApiSharedObjectac8b0c51cd$outboundSchema),
    registerId: z.optional(z.string()),
    safeId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      paymentMethodId: "payment_method_id",
      cardBrand: "card_brand",
      cardBatchNumber: "card_batch_number",
      cardCouponNumber: "card_coupon_number",
      cardInstallmentPlanCode: "card_installment_plan_code",
      feeAmount: "fee_amount",
      feePercentageApplied: "fee_percentage_applied",
      feeFixedApplied: "fee_fixed_applied",
      netAmount: "net_amount",
      checkId: "check_id",
      checkData: "check_data",
      registerId: "register_id",
      safeId: "safe_id",
    });
  }),
);

export function apiSharedObject9e584e0f8aToJSON(
  apiSharedObject9e584e0f8a: ApiSharedObject9e584e0f8a,
): string {
  return JSON.stringify(
    ApiSharedObject9e584e0f8a$outboundSchema.parse(apiSharedObject9e584e0f8a),
  );
}
