/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 895b76d6d307
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSupplierUpdateResponseSupplier = {
  object: "supplier";
  id: string;
  name: string;
  companyName: string | null;
  description: string | null;
  email: string | null;
  phone: string | null;
  taxId: string | null;
  taxIdType: string | null;
  taxCategory: string | null;
  paymentTermId: string | null;
  isActive: boolean | null;
  country: string | null;
  provinceId: string | null;
  city: string | null;
  address: string | null;
  apartment: string | null;
  postalCode: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type ApiSupplierUpdateResponseData = {
  supplier: ApiSupplierUpdateResponseSupplier;
};

export type ApiSupplierUpdateResponse = {
  requestId: string;
  data: ApiSupplierUpdateResponseData;
  warnings: Array<any>;
};

/** @internal */
export const ApiSupplierUpdateResponseSupplier$inboundSchema: z.ZodMiniType<
  ApiSupplierUpdateResponseSupplier,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("supplier"),
    id: types.string(),
    name: types.string(),
    company_name: types.nullable(types.string()),
    description: types.nullable(types.string()),
    email: types.nullable(types.string()),
    phone: types.nullable(types.string()),
    tax_id: types.nullable(types.string()),
    tax_id_type: types.nullable(types.string()),
    tax_category: types.nullable(types.string()),
    payment_term_id: types.nullable(types.string()),
    is_active: types.nullable(types.boolean()),
    country: types.nullable(types.string()),
    province_id: types.nullable(types.string()),
    city: types.nullable(types.string()),
    address: types.nullable(types.string()),
    apartment: types.nullable(types.string()),
    postal_code: types.nullable(types.string()),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "company_name": "companyName",
      "tax_id": "taxId",
      "tax_id_type": "taxIdType",
      "tax_category": "taxCategory",
      "payment_term_id": "paymentTermId",
      "is_active": "isActive",
      "province_id": "provinceId",
      "postal_code": "postalCode",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function apiSupplierUpdateResponseSupplierFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierUpdateResponseSupplier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSupplierUpdateResponseSupplier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierUpdateResponseSupplier' from JSON`,
  );
}

/** @internal */
export const ApiSupplierUpdateResponseData$inboundSchema: z.ZodMiniType<
  ApiSupplierUpdateResponseData,
  unknown
> = z.object({
  supplier: z.lazy(() => ApiSupplierUpdateResponseSupplier$inboundSchema),
});

export function apiSupplierUpdateResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierUpdateResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSupplierUpdateResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierUpdateResponseData' from JSON`,
  );
}

/** @internal */
export const ApiSupplierUpdateResponse$inboundSchema: z.ZodMiniType<
  ApiSupplierUpdateResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiSupplierUpdateResponseData$inboundSchema),
    warnings: z.array(z.any()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiSupplierUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiSupplierUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSupplierUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSupplierUpdateResponse' from JSON`,
  );
}
