/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c5354331f5d9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedObjectd371740910,
  ApiSharedObjectd371740910$inboundSchema,
} from "./api-shared-objectd371740910.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiProductCreateResponseData = {
  product: ApiSharedObjectd371740910;
  idempotentReplay: boolean;
};

export type ApiProductCreateResponse = {
  requestId: string;
  data: ApiProductCreateResponseData;
  warnings: Array<any>;
};

/** @internal */
export const ApiProductCreateResponseData$inboundSchema: z.ZodMiniType<
  ApiProductCreateResponseData,
  unknown
> = z.pipe(
  z.object({
    product: ApiSharedObjectd371740910$inboundSchema,
    idempotent_replay: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "idempotent_replay": "idempotentReplay",
    });
  }),
);

export function apiProductCreateResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ApiProductCreateResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiProductCreateResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiProductCreateResponseData' from JSON`,
  );
}

/** @internal */
export const ApiProductCreateResponse$inboundSchema: z.ZodMiniType<
  ApiProductCreateResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => ApiProductCreateResponseData$inboundSchema),
    warnings: z.array(z.any()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function apiProductCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiProductCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiProductCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiProductCreateResponse' from JSON`,
  );
}
