/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 07e66282d9bd
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const ApiPriceListMutationRequestAutomaticPricingMode = {
  BasePriceAdjustment: "base_price_adjustment",
  CostMarkup: "cost_markup",
} as const;
export type ApiPriceListMutationRequestAutomaticPricingMode = ClosedEnum<
  typeof ApiPriceListMutationRequestAutomaticPricingMode
>;

export type ApiPriceListMutationRequest = {
  name: string;
  isAutomatic?: boolean | undefined;
  automaticPricingMode?:
    | ApiPriceListMutationRequestAutomaticPricingMode
    | undefined;
  adjustmentPercentage?: number | null | undefined;
  defaultEconomicActivity?: string | null | undefined;
  taxInclusive?: boolean | undefined;
};

/** @internal */
export const ApiPriceListMutationRequestAutomaticPricingMode$outboundSchema:
  z.ZodMiniEnum<typeof ApiPriceListMutationRequestAutomaticPricingMode> = z
    .enum(ApiPriceListMutationRequestAutomaticPricingMode);

/** @internal */
export type ApiPriceListMutationRequest$Outbound = {
  name: string;
  is_automatic: boolean;
  automatic_pricing_mode: string;
  adjustment_percentage?: number | null | undefined;
  default_economic_activity?: string | null | undefined;
  tax_inclusive: boolean;
};

/** @internal */
export const ApiPriceListMutationRequest$outboundSchema: z.ZodMiniType<
  ApiPriceListMutationRequest$Outbound,
  ApiPriceListMutationRequest
> = z.pipe(
  z.object({
    name: z.string(),
    isAutomatic: z._default(z.boolean(), true),
    automaticPricingMode: z._default(
      ApiPriceListMutationRequestAutomaticPricingMode$outboundSchema,
      "base_price_adjustment",
    ),
    adjustmentPercentage: z.optional(z.nullable(z.number())),
    defaultEconomicActivity: z.optional(z.nullable(z.string())),
    taxInclusive: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      isAutomatic: "is_automatic",
      automaticPricingMode: "automatic_pricing_mode",
      adjustmentPercentage: "adjustment_percentage",
      defaultEconomicActivity: "default_economic_activity",
      taxInclusive: "tax_inclusive",
    });
  }),
);

export function apiPriceListMutationRequestToJSON(
  apiPriceListMutationRequest: ApiPriceListMutationRequest,
): string {
  return JSON.stringify(
    ApiPriceListMutationRequest$outboundSchema.parse(
      apiPriceListMutationRequest,
    ),
  );
}
