/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 15baf425d98f
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ApiSharedEnumf03e06f92c = {
  Rate: "rate",
  CarryingValue: "carrying_value",
  LegacyUnknown: "legacy_unknown",
} as const;
export type ApiSharedEnumf03e06f92c = OpenEnum<typeof ApiSharedEnumf03e06f92c>;

/** @internal */
export const ApiSharedEnumf03e06f92c$inboundSchema: z.ZodMiniType<
  ApiSharedEnumf03e06f92c,
  unknown
> = openEnums.inboundSchema(ApiSharedEnumf03e06f92c);
