/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7c6b372c1242
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum736f0d077b,
  ApiSharedEnum736f0d077b$inboundSchema,
} from "./api-shared-enum736f0d077b.js";
import {
  ApiSharedObject0afbf8c23c,
  ApiSharedObject0afbf8c23c$inboundSchema,
} from "./api-shared-object0afbf8c23c.js";
import {
  ApiSharedObject8aeeceaf0f,
  ApiSharedObject8aeeceaf0f$inboundSchema,
} from "./api-shared-object8aeeceaf0f.js";
import {
  ApiSharedObjected3905a55b,
  ApiSharedObjected3905a55b$inboundSchema,
} from "./api-shared-objected3905a55b.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject29aea9dac9 = {
  object: "stock_transfer";
  id: string;
  organizationId: string;
  sourceWarehouseId: string;
  targetWarehouseId: string;
  transferDate: Date;
  notes: string | null;
  status: ApiSharedEnum736f0d077b;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
  updatedBy: string | null;
  sourceWarehouse: ApiSharedObject8aeeceaf0f;
  targetWarehouse: ApiSharedObject8aeeceaf0f;
  items: Array<ApiSharedObject0afbf8c23c>;
  tags: Array<ApiSharedObjected3905a55b>;
};

/** @internal */
export const ApiSharedObject29aea9dac9$inboundSchema: z.ZodMiniType<
  ApiSharedObject29aea9dac9,
  unknown
> = z.pipe(
  z.object({
    object: types.literal("stock_transfer"),
    id: types.string(),
    organization_id: types.string(),
    source_warehouse_id: types.string(),
    target_warehouse_id: types.string(),
    transfer_date: types.date(),
    notes: types.nullable(types.string()),
    status: ApiSharedEnum736f0d077b$inboundSchema,
    created_at: types.date(),
    updated_at: types.date(),
    created_by: types.string(),
    updated_by: types.nullable(types.string()),
    source_warehouse: ApiSharedObject8aeeceaf0f$inboundSchema,
    target_warehouse: ApiSharedObject8aeeceaf0f$inboundSchema,
    items: z.array(ApiSharedObject0afbf8c23c$inboundSchema),
    tags: z.array(ApiSharedObjected3905a55b$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "organization_id": "organizationId",
      "source_warehouse_id": "sourceWarehouseId",
      "target_warehouse_id": "targetWarehouseId",
      "transfer_date": "transferDate",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "created_by": "createdBy",
      "updated_by": "updatedBy",
      "source_warehouse": "sourceWarehouse",
      "target_warehouse": "targetWarehouse",
    });
  }),
);

export function apiSharedObject29aea9dac9FromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject29aea9dac9, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject29aea9dac9$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject29aea9dac9' from JSON`,
  );
}
