/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4e6440eb5d8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const ApiProductUpdateRequestVisibility = {
  Both: "both",
  Sales: "sales",
  Purchases: "purchases",
} as const;
export type ApiProductUpdateRequestVisibility = ClosedEnum<
  typeof ApiProductUpdateRequestVisibility
>;

export const ApiProductUpdateRequestProductType = {
  Product: "product",
  Service: "service",
  Combo: "combo",
  Kit: "kit",
} as const;
export type ApiProductUpdateRequestProductType = ClosedEnum<
  typeof ApiProductUpdateRequestProductType
>;

export const ApiProductUpdateRequestUnitOfMeasure = {
  Ten: "10",
  Eleven: "11",
  Twelve: "12",
  Thirteen: "13",
  Fourteen: "14",
  Fifteen: "15",
  Sixteen: "16",
  Seventeen: "17",
  Eighteen: "18",
  Nineteen: "19",
  Twenty: "20",
  TwentyOne: "21",
  TwentyTwo: "22",
  TwentyThree: "23",
  TwentyFour: "24",
  TwentyFive: "25",
  TwentySix: "26",
  TwentySeven: "27",
  TwentyEight: "28",
  TwentyNine: "29",
  Thirty: "30",
  ThirtyOne: "31",
  ThirtyTwo: "32",
  ThirtyThree: "33",
  ThirtyFour: "34",
  ThirtyFive: "35",
  ThirtySix: "36",
  ThirtySeven: "37",
  FortyOne: "41",
  FortySeven: "47",
  FortyEight: "48",
  FortyNine: "49",
  Fifty: "50",
  FiftyOne: "51",
  FiftyTwo: "52",
  FiftyThree: "53",
  FiftyFour: "54",
  FiftyFive: "55",
  SixtyOne: "61",
  SixtyTwo: "62",
  SixtyThree: "63",
  NinetySeven: "97",
  NinetyEight: "98",
  NinetyNine: "99",
  Zero: "00",
  One: "01",
  Two: "02",
  Three: "03",
  Four: "04",
  Five: "05",
  Six: "06",
  Seven: "07",
  Eight: "08",
  Nine: "09",
} as const;
export type ApiProductUpdateRequestUnitOfMeasure = ClosedEnum<
  typeof ApiProductUpdateRequestUnitOfMeasure
>;

export const ApiProductUpdateRequestCurrency = {
  Pes: "PES",
  Dol: "DOL",
} as const;
export type ApiProductUpdateRequestCurrency = ClosedEnum<
  typeof ApiProductUpdateRequestCurrency
>;

export type ApiProductUpdateRequestWarehouseStock = {
  warehouseId: string;
  quantity: number;
};

export type ApiProductUpdateRequest = {
  name?: string | undefined;
  description?: string | null | undefined;
  categoryId?: string | null | undefined;
  visibility?: ApiProductUpdateRequestVisibility | undefined;
  imageUrl?: string | null | undefined;
  productType?: ApiProductUpdateRequestProductType | undefined;
  sku?: string | undefined;
  barcode?: string | null | undefined;
  unitOfMeasure?: ApiProductUpdateRequestUnitOfMeasure | undefined;
  currency?: ApiProductUpdateRequestCurrency | undefined;
  cost?: number | undefined;
  price?: number | undefined;
  promotionalPrice?: number | null | undefined;
  markupPercentage?: number | null | undefined;
  taxRateId?: number | undefined;
  isExempt?: boolean | undefined;
  defaultSupplierId?: string | null | undefined;
  defaultSalesAccountId?: string | null | undefined;
  defaultPurchaseAccountId?: string | null | undefined;
  warehouseStocks?: Array<ApiProductUpdateRequestWarehouseStock> | undefined;
  isActive?: boolean | undefined;
};

/** @internal */
export const ApiProductUpdateRequestVisibility$outboundSchema: z.ZodMiniEnum<
  typeof ApiProductUpdateRequestVisibility
> = z.enum(ApiProductUpdateRequestVisibility);

/** @internal */
export const ApiProductUpdateRequestProductType$outboundSchema: z.ZodMiniEnum<
  typeof ApiProductUpdateRequestProductType
> = z.enum(ApiProductUpdateRequestProductType);

/** @internal */
export const ApiProductUpdateRequestUnitOfMeasure$outboundSchema: z.ZodMiniEnum<
  typeof ApiProductUpdateRequestUnitOfMeasure
> = z.enum(ApiProductUpdateRequestUnitOfMeasure);

/** @internal */
export const ApiProductUpdateRequestCurrency$outboundSchema: z.ZodMiniEnum<
  typeof ApiProductUpdateRequestCurrency
> = z.enum(ApiProductUpdateRequestCurrency);

/** @internal */
export type ApiProductUpdateRequestWarehouseStock$Outbound = {
  warehouse_id: string;
  quantity: number;
};

/** @internal */
export const ApiProductUpdateRequestWarehouseStock$outboundSchema:
  z.ZodMiniType<
    ApiProductUpdateRequestWarehouseStock$Outbound,
    ApiProductUpdateRequestWarehouseStock
  > = z.pipe(
    z.object({
      warehouseId: z.string(),
      quantity: z.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        warehouseId: "warehouse_id",
      });
    }),
  );

export function apiProductUpdateRequestWarehouseStockToJSON(
  apiProductUpdateRequestWarehouseStock: ApiProductUpdateRequestWarehouseStock,
): string {
  return JSON.stringify(
    ApiProductUpdateRequestWarehouseStock$outboundSchema.parse(
      apiProductUpdateRequestWarehouseStock,
    ),
  );
}

/** @internal */
export type ApiProductUpdateRequest$Outbound = {
  name?: string | undefined;
  description?: string | null | undefined;
  category_id?: string | null | undefined;
  visibility?: string | undefined;
  image_url?: string | null | undefined;
  product_type?: string | undefined;
  sku?: string | undefined;
  barcode?: string | null | undefined;
  unit_of_measure?: string | undefined;
  currency?: string | undefined;
  cost?: number | undefined;
  price?: number | undefined;
  promotional_price?: number | null | undefined;
  markup_percentage?: number | null | undefined;
  tax_rate_id?: number | undefined;
  is_exempt?: boolean | undefined;
  default_supplier_id?: string | null | undefined;
  default_sales_account_id?: string | null | undefined;
  default_purchase_account_id?: string | null | undefined;
  warehouse_stocks?:
    | Array<ApiProductUpdateRequestWarehouseStock$Outbound>
    | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const ApiProductUpdateRequest$outboundSchema: z.ZodMiniType<
  ApiProductUpdateRequest$Outbound,
  ApiProductUpdateRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    description: z.optional(z.nullable(z.string())),
    categoryId: z.optional(z.nullable(z.string())),
    visibility: z.optional(ApiProductUpdateRequestVisibility$outboundSchema),
    imageUrl: z.optional(z.nullable(z.string())),
    productType: z.optional(ApiProductUpdateRequestProductType$outboundSchema),
    sku: z.optional(z.string()),
    barcode: z.optional(z.nullable(z.string())),
    unitOfMeasure: z.optional(
      ApiProductUpdateRequestUnitOfMeasure$outboundSchema,
    ),
    currency: z.optional(ApiProductUpdateRequestCurrency$outboundSchema),
    cost: z.optional(z.int()),
    price: z.optional(z.int()),
    promotionalPrice: z.optional(z.nullable(z.int())),
    markupPercentage: z.optional(z.nullable(z.number())),
    taxRateId: z.optional(z.int()),
    isExempt: z.optional(z.boolean()),
    defaultSupplierId: z.optional(z.nullable(z.string())),
    defaultSalesAccountId: z.optional(z.nullable(z.string())),
    defaultPurchaseAccountId: z.optional(z.nullable(z.string())),
    warehouseStocks: z.optional(
      z.array(
        z.lazy(() => ApiProductUpdateRequestWarehouseStock$outboundSchema),
      ),
    ),
    isActive: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      categoryId: "category_id",
      imageUrl: "image_url",
      productType: "product_type",
      unitOfMeasure: "unit_of_measure",
      promotionalPrice: "promotional_price",
      markupPercentage: "markup_percentage",
      taxRateId: "tax_rate_id",
      isExempt: "is_exempt",
      defaultSupplierId: "default_supplier_id",
      defaultSalesAccountId: "default_sales_account_id",
      defaultPurchaseAccountId: "default_purchase_account_id",
      warehouseStocks: "warehouse_stocks",
      isActive: "is_active",
    });
  }),
);

export function apiProductUpdateRequestToJSON(
  apiProductUpdateRequest: ApiProductUpdateRequest,
): string {
  return JSON.stringify(
    ApiProductUpdateRequest$outboundSchema.parse(apiProductUpdateRequest),
  );
}
