/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8d492f703922
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject7d023271be = {
  id?: string | undefined;
  saleId?: string | undefined;
  invoiceSaleId?: string | null | undefined;
  creditSaleId?: string | null | undefined;
  advancePaymentId?: string | undefined;
  journalLineId?: string | undefined;
  appliedAmount: number;
  formattedInvoiceNumber?: string | null | undefined;
  creditFormattedInvoiceNumber?: string | null | undefined;
  advanceFormattedPaymentNumber?: string | null | undefined;
};

/** @internal */
export const ApiSharedObject7d023271be$inboundSchema: z.ZodMiniType<
  ApiSharedObject7d023271be,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    sale_id: types.optional(types.string()),
    invoice_sale_id: z.optional(z.nullable(types.string())),
    credit_sale_id: z.optional(z.nullable(types.string())),
    advance_payment_id: types.optional(types.string()),
    journal_line_id: types.optional(types.string()),
    applied_amount: types.number(),
    formatted_invoice_number: z.optional(z.nullable(types.string())),
    credit_formatted_invoice_number: z.optional(z.nullable(types.string())),
    advance_formatted_payment_number: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "sale_id": "saleId",
      "invoice_sale_id": "invoiceSaleId",
      "credit_sale_id": "creditSaleId",
      "advance_payment_id": "advancePaymentId",
      "journal_line_id": "journalLineId",
      "applied_amount": "appliedAmount",
      "formatted_invoice_number": "formattedInvoiceNumber",
      "credit_formatted_invoice_number": "creditFormattedInvoiceNumber",
      "advance_formatted_payment_number": "advanceFormattedPaymentNumber",
    });
  }),
);

export function apiSharedObject7d023271beFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject7d023271be, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject7d023271be$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject7d023271be' from JSON`,
  );
}
