/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa1262912599
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ApiSharedEnum53162db3eb,
  ApiSharedEnum53162db3eb$inboundSchema,
} from "./api-shared-enum53162db3eb.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiSharedObject828d107a8b = {
  treasuryMovementId: string;
  balanceType: ApiSharedEnum53162db3eb;
  balanceId: string;
  amount: number;
  currency: "ARS";
};

/** @internal */
export const ApiSharedObject828d107a8b$inboundSchema: z.ZodMiniType<
  ApiSharedObject828d107a8b,
  unknown
> = z.pipe(
  z.object({
    treasury_movement_id: types.string(),
    balance_type: ApiSharedEnum53162db3eb$inboundSchema,
    balance_id: types.string(),
    amount: types.number(),
    currency: types.literal("ARS"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "treasury_movement_id": "treasuryMovementId",
      "balance_type": "balanceType",
      "balance_id": "balanceId",
    });
  }),
);

export function apiSharedObject828d107a8bFromJSON(
  jsonString: string,
): SafeParseResult<ApiSharedObject828d107a8b, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiSharedObject828d107a8b$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiSharedObject828d107a8b' from JSON`,
  );
}
