/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 64f5ce2621c9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AssistantReportResponseData = {
  summary: string;
  report: { [k: string]: any };
  chart: { [k: string]: any };
  reporting: { [k: string]: any };
  [additionalProperties: string]: unknown;
};

export type AssistantReportResponse = {
  requestId: string;
  data: AssistantReportResponseData;
};

/** @internal */
export const AssistantReportResponseData$inboundSchema: z.ZodMiniType<
  AssistantReportResponseData,
  unknown
> = z.catchall(
  z.object({
    summary: types.string(),
    report: z.record(z.string(), z.any()),
    chart: z.record(z.string(), z.any()),
    reporting: z.record(z.string(), z.any()),
  }),
  z.any(),
);

export function assistantReportResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<AssistantReportResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssistantReportResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssistantReportResponseData' from JSON`,
  );
}

/** @internal */
export const AssistantReportResponse$inboundSchema: z.ZodMiniType<
  AssistantReportResponse,
  unknown
> = z.pipe(
  z.object({
    request_id: types.string(),
    data: z.lazy(() => AssistantReportResponseData$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function assistantReportResponseFromJSON(
  jsonString: string,
): SafeParseResult<AssistantReportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssistantReportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssistantReportResponse' from JSON`,
  );
}
