/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 46cd60917601
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smart-union.js";
import {
  ApiSharedEnum5ff5ed4826,
  ApiSharedEnum5ff5ed4826$outboundSchema,
} from "./api-shared-enum5ff5ed4826.js";

/**
 * Obligatorio cuando se piden métricas históricas de inventario, métricas derivadas de ventas o métricas de movimientos.
 */
export type InventoryReportRequestPeriod = {
  /**
   * Period start date (YYYY-MM-DD)
   */
  startDate: Date;
  /**
   * Period end date (YYYY-MM-DD, inclusive)
   */
  endDate: Date;
};

export const InventoryReportRequestDimensionEnum = {
  Date: "date",
  Week: "week",
  WeekOfYear: "weekOfYear",
  Month: "month",
  MonthOfYear: "monthOfYear",
  DayOfWeek: "dayOfWeek",
  Year: "year",
  Quarter: "quarter",
  Product: "product",
  ProductName: "productName",
  Variant: "variant",
  VariantSku: "variantSku",
  Category: "category",
  Subcategory: "subcategory",
  DefaultSupplierName: "defaultSupplierName",
  ProductType: "productType",
  Currency: "currency",
  InventoryItemCost: "inventoryItemCost",
  Warehouse: "warehouse",
} as const;
export type InventoryReportRequestDimensionEnum = ClosedEnum<
  typeof InventoryReportRequestDimensionEnum
>;

export type InventoryReportRequestDimensionUnion =
  | InventoryReportRequestDimensionEnum
  | string;

export const InventoryReportRequestMeasure = {
  StockOnHand: "stockOnHand",
  StockAvailable: "stockAvailable",
  StockReserved: "stockReserved",
  StockIncoming: "stockIncoming",
  StockValueCost: "stockValueCost",
  StockValueRetail: "stockValueRetail",
  StartingInventoryUnits: "startingInventoryUnits",
  EndingInventoryUnits: "endingInventoryUnits",
  EndingInventoryValue: "endingInventoryValue",
  EndingInventoryRetailValue: "endingInventoryRetailValue",
  DaysInStock: "daysInStock",
  DaysOutOfStock: "daysOutOfStock",
  InventoryUnitsSold: "inventoryUnitsSold",
  InventoryUnitsSoldPerDay: "inventoryUnitsSoldPerDay",
  DaysOfInventoryRemaining: "daysOfInventoryRemaining",
  SellThroughRate: "sellThroughRate",
  InventoryUnitsNetChange: "inventoryUnitsNetChange",
  InventoryAdjustmentChange: "inventoryAdjustmentChange",
  InventoryAdjustmentCount: "inventoryAdjustmentCount",
  ReceivedQuantity: "receivedQuantity",
  TransferCount: "transferCount",
  TransferLineItemCount: "transferLineItemCount",
  UniqueItemsTransferred: "uniqueItemsTransferred",
} as const;
export type InventoryReportRequestMeasure = ClosedEnum<
  typeof InventoryReportRequestMeasure
>;

/**
 * Filtros por dimensión. Cada clave debe ser una dimensión filtrable para la fuente. También acepta product_metafield:<key> para campos personalizados select de producto y contact_metafield:<key> para campos personalizados select de contacto cuando la fuente lo soporta. El valor es un array de IDs o valores a incluir.
 */
export type InventoryReportRequestDimensionFilters = {
  product?: Array<string> | undefined;
  productName?: Array<string> | undefined;
  variantSku?: Array<string> | undefined;
  category?: Array<string> | undefined;
  subcategory?: Array<string> | undefined;
  defaultSupplierName?: Array<string> | undefined;
  productType?: Array<string> | undefined;
  currency?: Array<string> | undefined;
  warehouse?: Array<string> | undefined;
  productStatus?: Array<string> | undefined;
  warehouseStatus?: Array<string> | undefined;
  saleLineType?: Array<string> | undefined;
};

/**
 * Aplica solo cuando se usan métricas derivadas de ventas. `commercial` usa la fecha de venta; `fiscal` usa la fecha contable.
 */
export const InventoryReportRequestDateBasis = {
  Commercial: "commercial",
  Fiscal: "fiscal",
} as const;
/**
 * Aplica solo cuando se usan métricas derivadas de ventas. `commercial` usa la fecha de venta; `fiscal` usa la fecha contable.
 */
export type InventoryReportRequestDateBasis = ClosedEnum<
  typeof InventoryReportRequestDateBasis
>;

export type InventoryReportRequest = {
  source: "inventory";
  /**
   * Obligatorio cuando se piden métricas históricas de inventario, métricas derivadas de ventas o métricas de movimientos.
   */
  period?: InventoryReportRequestPeriod | undefined;
  /**
   * Dimensiones de agrupación. Máximo 12. Acepta product_metafield:<key> para campos personalizados select de producto.
   */
  dimensions?: Array<InventoryReportRequestDimensionEnum | string> | undefined;
  /**
   * Measures to calculate. Inventory analytics measures are period-based; use endingInventoryUnits for the inventory balance at the end of the requested period.
   */
  measures: Array<InventoryReportRequestMeasure>;
  /**
   * Filtros por dimensión. Cada clave debe ser una dimensión filtrable para la fuente. También acepta product_metafield:<key> para campos personalizados select de producto y contact_metafield:<key> para campos personalizados select de contacto cuando la fuente lo soporta. El valor es un array de IDs o valores a incluir.
   */
  dimensionFilters?: InventoryReportRequestDimensionFilters | undefined;
  /**
   * Si es true, la respuesta incluye totales agregados en el campo `totals`.
   */
  includeTotals?: boolean | undefined;
  /**
   * Currency used for all monetary measures in the report.
   */
  reportingCurrency?: ApiSharedEnum5ff5ed4826 | undefined;
  /**
   * Aplica solo cuando se usan métricas derivadas de ventas. `commercial` usa la fecha de venta; `fiscal` usa la fecha contable.
   */
  dateBasis?: InventoryReportRequestDateBasis | undefined;
};

/** @internal */
export type InventoryReportRequestPeriod$Outbound = {
  start_date: string;
  end_date: string;
};

/** @internal */
export const InventoryReportRequestPeriod$outboundSchema: z.ZodMiniType<
  InventoryReportRequestPeriod$Outbound,
  InventoryReportRequestPeriod
> = z.pipe(
  z.object({
    startDate: z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
    endDate: z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      startDate: "start_date",
      endDate: "end_date",
    });
  }),
);

export function inventoryReportRequestPeriodToJSON(
  inventoryReportRequestPeriod: InventoryReportRequestPeriod,
): string {
  return JSON.stringify(
    InventoryReportRequestPeriod$outboundSchema.parse(
      inventoryReportRequestPeriod,
    ),
  );
}

/** @internal */
export const InventoryReportRequestDimensionEnum$outboundSchema: z.ZodMiniEnum<
  typeof InventoryReportRequestDimensionEnum
> = z.enum(InventoryReportRequestDimensionEnum);

/** @internal */
export type InventoryReportRequestDimensionUnion$Outbound = string | string;

/** @internal */
export const InventoryReportRequestDimensionUnion$outboundSchema: z.ZodMiniType<
  InventoryReportRequestDimensionUnion$Outbound,
  InventoryReportRequestDimensionUnion
> = smartUnion([
  InventoryReportRequestDimensionEnum$outboundSchema,
  z.string(),
]);

export function inventoryReportRequestDimensionUnionToJSON(
  inventoryReportRequestDimensionUnion: InventoryReportRequestDimensionUnion,
): string {
  return JSON.stringify(
    InventoryReportRequestDimensionUnion$outboundSchema.parse(
      inventoryReportRequestDimensionUnion,
    ),
  );
}

/** @internal */
export const InventoryReportRequestMeasure$outboundSchema: z.ZodMiniEnum<
  typeof InventoryReportRequestMeasure
> = z.enum(InventoryReportRequestMeasure);

/** @internal */
export type InventoryReportRequestDimensionFilters$Outbound = {
  product?: Array<string> | undefined;
  product_name?: Array<string> | undefined;
  variant_sku?: Array<string> | undefined;
  category?: Array<string> | undefined;
  subcategory?: Array<string> | undefined;
  default_supplier_name?: Array<string> | undefined;
  product_type?: Array<string> | undefined;
  currency?: Array<string> | undefined;
  warehouse?: Array<string> | undefined;
  product_status?: Array<string> | undefined;
  warehouse_status?: Array<string> | undefined;
  sale_line_type?: Array<string> | undefined;
};

/** @internal */
export const InventoryReportRequestDimensionFilters$outboundSchema:
  z.ZodMiniType<
    InventoryReportRequestDimensionFilters$Outbound,
    InventoryReportRequestDimensionFilters
  > = z.pipe(
    z.object({
      product: z.optional(z.array(z.string())),
      productName: z.optional(z.array(z.string())),
      variantSku: z.optional(z.array(z.string())),
      category: z.optional(z.array(z.string())),
      subcategory: z.optional(z.array(z.string())),
      defaultSupplierName: z.optional(z.array(z.string())),
      productType: z.optional(z.array(z.string())),
      currency: z.optional(z.array(z.string())),
      warehouse: z.optional(z.array(z.string())),
      productStatus: z.optional(z.array(z.string())),
      warehouseStatus: z.optional(z.array(z.string())),
      saleLineType: z.optional(z.array(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        productName: "product_name",
        variantSku: "variant_sku",
        defaultSupplierName: "default_supplier_name",
        productType: "product_type",
        productStatus: "product_status",
        warehouseStatus: "warehouse_status",
        saleLineType: "sale_line_type",
      });
    }),
  );

export function inventoryReportRequestDimensionFiltersToJSON(
  inventoryReportRequestDimensionFilters:
    InventoryReportRequestDimensionFilters,
): string {
  return JSON.stringify(
    InventoryReportRequestDimensionFilters$outboundSchema.parse(
      inventoryReportRequestDimensionFilters,
    ),
  );
}

/** @internal */
export const InventoryReportRequestDateBasis$outboundSchema: z.ZodMiniEnum<
  typeof InventoryReportRequestDateBasis
> = z.enum(InventoryReportRequestDateBasis);

/** @internal */
export type InventoryReportRequest$Outbound = {
  source: "inventory";
  period?: InventoryReportRequestPeriod$Outbound | undefined;
  dimensions?: Array<string | string> | undefined;
  measures: Array<string>;
  dimension_filters?:
    | InventoryReportRequestDimensionFilters$Outbound
    | undefined;
  include_totals?: boolean | undefined;
  reporting_currency: string;
  date_basis: string;
};

/** @internal */
export const InventoryReportRequest$outboundSchema: z.ZodMiniType<
  InventoryReportRequest$Outbound,
  InventoryReportRequest
> = z.pipe(
  z.object({
    source: z.literal("inventory"),
    period: z.optional(
      z.lazy(() => InventoryReportRequestPeriod$outboundSchema),
    ),
    dimensions: z.optional(
      z.array(
        smartUnion([
          InventoryReportRequestDimensionEnum$outboundSchema,
          z.string(),
        ]),
      ),
    ),
    measures: z.array(InventoryReportRequestMeasure$outboundSchema),
    dimensionFilters: z.optional(
      z.lazy(() => InventoryReportRequestDimensionFilters$outboundSchema),
    ),
    includeTotals: z.optional(z.boolean()),
    reportingCurrency: z._default(
      ApiSharedEnum5ff5ed4826$outboundSchema,
      "PES",
    ),
    dateBasis: z._default(
      InventoryReportRequestDateBasis$outboundSchema,
      "commercial",
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      dimensionFilters: "dimension_filters",
      includeTotals: "include_totals",
      reportingCurrency: "reporting_currency",
      dateBasis: "date_basis",
    });
  }),
);

export function inventoryReportRequestToJSON(
  inventoryReportRequest: InventoryReportRequest,
): string {
  return JSON.stringify(
    InventoryReportRequest$outboundSchema.parse(inventoryReportRequest),
  );
}
