/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6620189e8354
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiSharedEnum71dd1d6676,
  ApiSharedEnum71dd1d6676$outboundSchema,
} from "./api-shared-enum71dd1d6676.js";

export const MarketplaceListingsReportRequestDimension = {
  MarketplaceListing: "marketplace_listing",
  MarketplaceAccount: "marketplace_account",
  MarketplaceSku: "marketplace_sku",
  MarketplaceListingType: "marketplace_listing_type",
  MarketplaceLogisticType: "marketplace_logistic_type",
  EstimateInputState: "estimate_input_state",
  EstimateQuoteState: "estimate_quote_state",
  EstimateQuoteDate: "estimate_quote_date",
  RecentUnitsCoverage: "recent_units_coverage",
  RecentUnitsCoverageStart: "recent_units_coverage_start",
  RecentUnitsAttribution: "recent_units_attribution",
} as const;
export type MarketplaceListingsReportRequestDimension = ClosedEnum<
  typeof MarketplaceListingsReportRequestDimension
>;

export const MarketplaceListingsReportRequestMeasure = {
  ListingCount: "listing_count",
  ListingPrice: "listing_price",
  ReferenceCost: "reference_cost",
  ListingFee: "listing_fee",
  ListingCommission: "listing_commission",
  ListingFixedFee: "listing_fixed_fee",
  ListingFinancing: "listing_financing",
  ListingShipping: "listing_shipping",
  ListingChannelSharePercent: "listing_channel_share_percent",
  ListingAdditionalCosts: "listing_additional_costs",
  EstimatedContribution: "estimated_contribution",
  EstimatedContributionPercent: "estimated_contribution_percent",
  RecentUnits: "recent_units",
} as const;
export type MarketplaceListingsReportRequestMeasure = ClosedEnum<
  typeof MarketplaceListingsReportRequestMeasure
>;

export const SortBy = {
  MarketplaceListing: "marketplace_listing",
  MarketplaceAccount: "marketplace_account",
  MarketplaceSku: "marketplace_sku",
  MarketplaceListingType: "marketplace_listing_type",
  MarketplaceLogisticType: "marketplace_logistic_type",
  EstimateInputState: "estimate_input_state",
  EstimateQuoteState: "estimate_quote_state",
  EstimateQuoteDate: "estimate_quote_date",
  RecentUnitsCoverage: "recent_units_coverage",
  RecentUnitsCoverageStart: "recent_units_coverage_start",
  RecentUnitsAttribution: "recent_units_attribution",
  ListingCount: "listing_count",
  ListingPrice: "listing_price",
  ReferenceCost: "reference_cost",
  ListingFee: "listing_fee",
  ListingCommission: "listing_commission",
  ListingFixedFee: "listing_fixed_fee",
  ListingFinancing: "listing_financing",
  ListingShipping: "listing_shipping",
  ListingChannelSharePercent: "listing_channel_share_percent",
  ListingAdditionalCosts: "listing_additional_costs",
  EstimatedContribution: "estimated_contribution",
  EstimatedContributionPercent: "estimated_contribution_percent",
  RecentUnits: "recent_units",
} as const;
export type SortBy = ClosedEnum<typeof SortBy>;

/**
 * Instantánea de publicaciones activas en ARS. Estima la contribución de una unidad, sin período ni comparación. Conservá fecha, vigencia, cobertura y atribución; los campos financieros requieren permiso vigente para ver costos.
 */
export type MarketplaceListingsReportRequest = {
  source: "marketplace_listings";
  responseMode?: "assistant" | undefined;
  dimensions?: Array<MarketplaceListingsReportRequestDimension> | undefined;
  measures: Array<MarketplaceListingsReportRequestMeasure>;
  reportingCurrency?: "ARS" | undefined;
  filters?: Array<{ [k: string]: any }> | undefined;
  resultFilters?: Array<{ [k: string]: any }> | undefined;
  dimensionFilters?: { [k: string]: Array<string> } | undefined;
  sortBy?: SortBy | undefined;
  sortDirection?: ApiSharedEnum71dd1d6676 | undefined;
  limit?: number | undefined;
  /**
   * Cursor opaco devuelto por la página anterior.
   */
  cursor?: string | undefined;
};

/** @internal */
export const MarketplaceListingsReportRequestDimension$outboundSchema:
  z.ZodMiniEnum<typeof MarketplaceListingsReportRequestDimension> = z.enum(
    MarketplaceListingsReportRequestDimension,
  );

/** @internal */
export const MarketplaceListingsReportRequestMeasure$outboundSchema:
  z.ZodMiniEnum<typeof MarketplaceListingsReportRequestMeasure> = z.enum(
    MarketplaceListingsReportRequestMeasure,
  );

/** @internal */
export const SortBy$outboundSchema: z.ZodMiniEnum<typeof SortBy> = z.enum(
  SortBy,
);

/** @internal */
export type MarketplaceListingsReportRequest$Outbound = {
  source: "marketplace_listings";
  response_mode?: "assistant" | undefined;
  dimensions?: Array<string> | undefined;
  measures: Array<string>;
  reporting_currency?: "ARS" | undefined;
  filters?: Array<{ [k: string]: any }> | undefined;
  result_filters?: Array<{ [k: string]: any }> | undefined;
  dimension_filters?: { [k: string]: Array<string> } | undefined;
  sort_by?: string | undefined;
  sort_direction?: string | undefined;
  limit?: number | undefined;
  cursor?: string | undefined;
};

/** @internal */
export const MarketplaceListingsReportRequest$outboundSchema: z.ZodMiniType<
  MarketplaceListingsReportRequest$Outbound,
  MarketplaceListingsReportRequest
> = z.pipe(
  z.object({
    source: z.literal("marketplace_listings"),
    responseMode: z.optional(z.literal("assistant")),
    dimensions: z.optional(
      z.array(MarketplaceListingsReportRequestDimension$outboundSchema),
    ),
    measures: z.array(MarketplaceListingsReportRequestMeasure$outboundSchema),
    reportingCurrency: z.optional(z.literal("ARS")),
    filters: z.optional(z.array(z.record(z.string(), z.any()))),
    resultFilters: z.optional(z.array(z.record(z.string(), z.any()))),
    dimensionFilters: z.optional(z.record(z.string(), z.array(z.string()))),
    sortBy: z.optional(SortBy$outboundSchema),
    sortDirection: z.optional(ApiSharedEnum71dd1d6676$outboundSchema),
    limit: z.optional(z.int()),
    cursor: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      responseMode: "response_mode",
      reportingCurrency: "reporting_currency",
      resultFilters: "result_filters",
      dimensionFilters: "dimension_filters",
      sortBy: "sort_by",
      sortDirection: "sort_direction",
    });
  }),
);

export function marketplaceListingsReportRequestToJSON(
  marketplaceListingsReportRequest: MarketplaceListingsReportRequest,
): string {
  return JSON.stringify(
    MarketplaceListingsReportRequest$outboundSchema.parse(
      marketplaceListingsReportRequest,
    ),
  );
}
