/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6620189e8354
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const MarketplaceListingsReportRequestDimension = {
  MarketplaceItemId: "marketplace_item_id",
  MarketplaceListing: "marketplace_listing",
  MarketplaceAccount: "marketplace_account",
  MarketplaceSku: "marketplace_sku",
  MarketplaceListingType: "marketplace_listing_type",
  MarketplaceLogisticType: "marketplace_logistic_type",
} as const;
export type MarketplaceListingsReportRequestDimension = ClosedEnum<
  typeof MarketplaceListingsReportRequestDimension
>;

export const MarketplaceListingsReportRequestMeasure = {
  ListingPrice: "listing_price",
  ReferenceCost: "reference_cost",
  ListingFee: "listing_fee",
  ListingCommission: "listing_commission",
  ListingFixedFee: "listing_fixed_fee",
  ListingFinancing: "listing_financing",
  ListingShipping: "listing_shipping",
  ListingChannelSharePercent: "listing_channel_share_percent",
  ListingAdditionalCosts: "listing_additional_costs",
  EstimatedContribution: "estimated_contribution",
  EstimatedContributionPercent: "estimated_contribution_percent",
  RecentUnits: "recent_units",
} as const;
export type MarketplaceListingsReportRequestMeasure = ClosedEnum<
  typeof MarketplaceListingsReportRequestMeasure
>;

/**
 * Instantánea de publicaciones activas en ARS, una fila por publicación. Estima la contribución de una unidad, sin período ni comparación. Requiere `marketplace_item_id` o `marketplace_listing`. Devuelve todas las publicaciones; para ordenar y paginar usá `response_mode=assistant`. Los campos financieros requieren permiso vigente para ver costos.
 */
export type MarketplaceListingsReportRequest = {
  source: "marketplace_listings";
  dimensions: Array<MarketplaceListingsReportRequestDimension>;
  measures: Array<MarketplaceListingsReportRequestMeasure>;
  reportingCurrency?: "ARS" | undefined;
  filters?: Array<{ [k: string]: any }> | undefined;
  resultFilters?: Array<{ [k: string]: any }> | undefined;
  dimensionFilters?: { [k: string]: Array<string> } | undefined;
};

/** @internal */
export const MarketplaceListingsReportRequestDimension$outboundSchema:
  z.ZodMiniEnum<typeof MarketplaceListingsReportRequestDimension> = z.enum(
    MarketplaceListingsReportRequestDimension,
  );

/** @internal */
export const MarketplaceListingsReportRequestMeasure$outboundSchema:
  z.ZodMiniEnum<typeof MarketplaceListingsReportRequestMeasure> = z.enum(
    MarketplaceListingsReportRequestMeasure,
  );

/** @internal */
export type MarketplaceListingsReportRequest$Outbound = {
  source: "marketplace_listings";
  dimensions: Array<string>;
  measures: Array<string>;
  reporting_currency?: "ARS" | undefined;
  filters?: Array<{ [k: string]: any }> | undefined;
  result_filters?: Array<{ [k: string]: any }> | undefined;
  dimension_filters?: { [k: string]: Array<string> } | undefined;
};

/** @internal */
export const MarketplaceListingsReportRequest$outboundSchema: z.ZodMiniType<
  MarketplaceListingsReportRequest$Outbound,
  MarketplaceListingsReportRequest
> = z.pipe(
  z.object({
    source: z.literal("marketplace_listings"),
    dimensions: z.array(
      MarketplaceListingsReportRequestDimension$outboundSchema,
    ),
    measures: z.array(MarketplaceListingsReportRequestMeasure$outboundSchema),
    reportingCurrency: z.optional(z.literal("ARS")),
    filters: z.optional(z.array(z.record(z.string(), z.any()))),
    resultFilters: z.optional(z.array(z.record(z.string(), z.any()))),
    dimensionFilters: z.optional(z.record(z.string(), z.array(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      reportingCurrency: "reporting_currency",
      resultFilters: "result_filters",
      dimensionFilters: "dimension_filters",
    });
  }),
);

export function marketplaceListingsReportRequestToJSON(
  marketplaceListingsReportRequest: MarketplaceListingsReportRequest,
): string {
  return JSON.stringify(
    MarketplaceListingsReportRequest$outboundSchema.parse(
      marketplaceListingsReportRequest,
    ),
  );
}
