/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eae7cfdb6635
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ReportPeriod,
  ReportPeriod$Outbound,
  ReportPeriod$outboundSchema,
} from "./report-period.js";

export const PaymentsReportRequestDimension = {
  Date: "date",
  Week: "week",
  WeekOfYear: "weekOfYear",
  Month: "month",
  MonthOfYear: "monthOfYear",
  DayOfWeek: "dayOfWeek",
  Year: "year",
  Quarter: "quarter",
  HourOfDay: "hourOfDay",
  PaymentContact: "paymentContact",
  PaymentContactName: "paymentContactName",
  PaymentContactTaxCategory: "paymentContactTaxCategory",
  PaymentContactProvince: "paymentContactProvince",
  PaymentContactCity: "paymentContactCity",
  PointOfSale: "pointOfSale",
  Register: "register",
  PosSession: "posSession",
  Safe: "safe",
  PaymentType: "paymentType",
  PaymentRecordStatus: "paymentRecordStatus",
  Currency: "currency",
  SettlementCurrency: "settlementCurrency",
  FormattedPaymentNumber: "formattedPaymentNumber",
  PaymentMethod: "paymentMethod",
  PaymentMethodType: "paymentMethodType",
} as const;
export type PaymentsReportRequestDimension = ClosedEnum<
  typeof PaymentsReportRequestDimension
>;

export const PaymentsReportRequestMeasure = {
  PaymentCollectedTotal: "paymentCollectedTotal",
  PaymentPaidTotal: "paymentPaidTotal",
  PaymentNetCashflow: "paymentNetCashflow",
  PaymentGrossMovement: "paymentGrossMovement",
  PaymentNetAmount: "paymentNetAmount",
  PaymentFeeAmount: "paymentFeeAmount",
  PaymentBalance: "paymentBalance",
  PaymentCount: "paymentCount",
  PaymentSplitCount: "paymentSplitCount",
  UniquePaymentContacts: "uniquePaymentContacts",
  AvgPaymentAmount: "avgPaymentAmount",
} as const;
export type PaymentsReportRequestMeasure = ClosedEnum<
  typeof PaymentsReportRequestMeasure
>;

/**
 * Filtros por dimensión. Cada clave debe ser una dimensión filtrable para la fuente. El valor es un array de IDs o valores a incluir.
 */
export type PaymentsReportRequestDimensionFilters = {
  paymentContact?: Array<string> | undefined;
  paymentContactName?: Array<string> | undefined;
  paymentContactTaxCategory?: Array<string> | undefined;
  paymentContactProvince?: Array<string> | undefined;
  paymentContactCity?: Array<string> | undefined;
  pointOfSale?: Array<string> | undefined;
  register?: Array<string> | undefined;
  posSession?: Array<string> | undefined;
  safe?: Array<string> | undefined;
  paymentType?: Array<string> | undefined;
  paymentRecordStatus?: Array<string> | undefined;
  currency?: Array<string> | undefined;
  settlementCurrency?: Array<string> | undefined;
  formattedPaymentNumber?: Array<string> | undefined;
  paymentMethod?: Array<string> | undefined;
  paymentMethodType?: Array<string> | undefined;
};

export type PaymentsReportRequest = {
  source: "payments";
  period: ReportPeriod;
  /**
   * Dimensiones de agrupación. Máximo 4.
   */
  dimensions?: Array<PaymentsReportRequestDimension> | undefined;
  /**
   * Medidas a calcular. Al menos una.
   */
  measures: Array<PaymentsReportRequestMeasure>;
  /**
   * Filtros por dimensión. Cada clave debe ser una dimensión filtrable para la fuente. El valor es un array de IDs o valores a incluir.
   */
  dimensionFilters?: PaymentsReportRequestDimensionFilters | undefined;
  /**
   * Si es true, la respuesta incluye totales agregados en el campo `totals`.
   */
  includeTotals?: boolean | undefined;
};

/** @internal */
export const PaymentsReportRequestDimension$outboundSchema: z.ZodMiniEnum<
  typeof PaymentsReportRequestDimension
> = z.enum(PaymentsReportRequestDimension);

/** @internal */
export const PaymentsReportRequestMeasure$outboundSchema: z.ZodMiniEnum<
  typeof PaymentsReportRequestMeasure
> = z.enum(PaymentsReportRequestMeasure);

/** @internal */
export type PaymentsReportRequestDimensionFilters$Outbound = {
  payment_contact?: Array<string> | undefined;
  payment_contact_name?: Array<string> | undefined;
  payment_contact_tax_category?: Array<string> | undefined;
  payment_contact_province?: Array<string> | undefined;
  payment_contact_city?: Array<string> | undefined;
  point_of_sale?: Array<string> | undefined;
  register?: Array<string> | undefined;
  pos_session?: Array<string> | undefined;
  safe?: Array<string> | undefined;
  payment_type?: Array<string> | undefined;
  payment_record_status?: Array<string> | undefined;
  currency?: Array<string> | undefined;
  settlement_currency?: Array<string> | undefined;
  formatted_payment_number?: Array<string> | undefined;
  payment_method?: Array<string> | undefined;
  payment_method_type?: Array<string> | undefined;
};

/** @internal */
export const PaymentsReportRequestDimensionFilters$outboundSchema:
  z.ZodMiniType<
    PaymentsReportRequestDimensionFilters$Outbound,
    PaymentsReportRequestDimensionFilters
  > = z.pipe(
    z.object({
      paymentContact: z.optional(z.array(z.string())),
      paymentContactName: z.optional(z.array(z.string())),
      paymentContactTaxCategory: z.optional(z.array(z.string())),
      paymentContactProvince: z.optional(z.array(z.string())),
      paymentContactCity: z.optional(z.array(z.string())),
      pointOfSale: z.optional(z.array(z.string())),
      register: z.optional(z.array(z.string())),
      posSession: z.optional(z.array(z.string())),
      safe: z.optional(z.array(z.string())),
      paymentType: z.optional(z.array(z.string())),
      paymentRecordStatus: z.optional(z.array(z.string())),
      currency: z.optional(z.array(z.string())),
      settlementCurrency: z.optional(z.array(z.string())),
      formattedPaymentNumber: z.optional(z.array(z.string())),
      paymentMethod: z.optional(z.array(z.string())),
      paymentMethodType: z.optional(z.array(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        paymentContact: "payment_contact",
        paymentContactName: "payment_contact_name",
        paymentContactTaxCategory: "payment_contact_tax_category",
        paymentContactProvince: "payment_contact_province",
        paymentContactCity: "payment_contact_city",
        pointOfSale: "point_of_sale",
        posSession: "pos_session",
        paymentType: "payment_type",
        paymentRecordStatus: "payment_record_status",
        settlementCurrency: "settlement_currency",
        formattedPaymentNumber: "formatted_payment_number",
        paymentMethod: "payment_method",
        paymentMethodType: "payment_method_type",
      });
    }),
  );

export function paymentsReportRequestDimensionFiltersToJSON(
  paymentsReportRequestDimensionFilters: PaymentsReportRequestDimensionFilters,
): string {
  return JSON.stringify(
    PaymentsReportRequestDimensionFilters$outboundSchema.parse(
      paymentsReportRequestDimensionFilters,
    ),
  );
}

/** @internal */
export type PaymentsReportRequest$Outbound = {
  source: "payments";
  period: ReportPeriod$Outbound;
  dimensions?: Array<string> | undefined;
  measures: Array<string>;
  dimension_filters?:
    | PaymentsReportRequestDimensionFilters$Outbound
    | undefined;
  include_totals?: boolean | undefined;
};

/** @internal */
export const PaymentsReportRequest$outboundSchema: z.ZodMiniType<
  PaymentsReportRequest$Outbound,
  PaymentsReportRequest
> = z.pipe(
  z.object({
    source: z.literal("payments"),
    period: ReportPeriod$outboundSchema,
    dimensions: z.optional(
      z.array(PaymentsReportRequestDimension$outboundSchema),
    ),
    measures: z.array(PaymentsReportRequestMeasure$outboundSchema),
    dimensionFilters: z.optional(
      z.lazy(() => PaymentsReportRequestDimensionFilters$outboundSchema),
    ),
    includeTotals: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      dimensionFilters: "dimension_filters",
      includeTotals: "include_totals",
    });
  }),
);

export function paymentsReportRequestToJSON(
  paymentsReportRequest: PaymentsReportRequest,
): string {
  return JSON.stringify(
    PaymentsReportRequest$outboundSchema.parse(paymentsReportRequest),
  );
}
