/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fbd43d686109
 */

import * as z from "zod/v4-mini";
import {
  InventoryReportRequest,
  InventoryReportRequest$Outbound,
  InventoryReportRequest$outboundSchema,
} from "./inventory-report-request.js";
import {
  PurchasesReportRequest,
  PurchasesReportRequest$Outbound,
  PurchasesReportRequest$outboundSchema,
} from "./purchases-report-request.js";
import {
  SalesReportRequest,
  SalesReportRequest$Outbound,
  SalesReportRequest$outboundSchema,
} from "./sales-report-request.js";

export type ReportRequest =
  | SalesReportRequest
  | PurchasesReportRequest
  | InventoryReportRequest;

/** @internal */
export type ReportRequest$Outbound =
  | SalesReportRequest$Outbound
  | PurchasesReportRequest$Outbound
  | InventoryReportRequest$Outbound;

/** @internal */
export const ReportRequest$outboundSchema: z.ZodMiniType<
  ReportRequest$Outbound,
  ReportRequest
> = z.union([
  SalesReportRequest$outboundSchema,
  PurchasesReportRequest$outboundSchema,
  InventoryReportRequest$outboundSchema,
]);

export function reportRequestToJSON(reportRequest: ReportRequest): string {
  return JSON.stringify(ReportRequest$outboundSchema.parse(reportRequest));
}
