/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ReportPeriod = {
  /**
   * Fecha de inicio del período (YYYY-MM-DD)
   */
  startDate: Date;
  /**
   * Fecha de fin del período (YYYY-MM-DD, inclusive)
   */
  endDate: Date;
};

/** @internal */
export type ReportPeriod$Outbound = {
  startDate: string;
  endDate: string;
};

/** @internal */
export const ReportPeriod$outboundSchema: z.ZodMiniType<
  ReportPeriod$Outbound,
  ReportPeriod
> = z.object({
  startDate: z.pipe(
    z.date(),
    z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
  ),
  endDate: z.pipe(
    z.date(),
    z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
  ),
});

export function reportPeriodToJSON(reportPeriod: ReportPeriod): string {
  return JSON.stringify(ReportPeriod$outboundSchema.parse(reportPeriod));
}
