/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type V2ProductListResponseCategory = {
  id: string;
  name: string;
};

export type V2ProductListResponseTaxRate = {
  id: number;
  value: number;
};

export type V2ProductListResponseDefaultSupplier = {
  id: string;
  name: string;
};

export const V2ProductListResponseProductType = {
  Product: "product",
  Service: "service",
  Combo: "combo",
} as const;
export type V2ProductListResponseProductType = OpenEnum<
  typeof V2ProductListResponseProductType
>;

export const V2ProductListResponsePriceSource = {
  Automatic: "automatic",
  ManualOverride: "manual_override",
  ManualFallback: "manual_fallback",
  Base: "base",
} as const;
export type V2ProductListResponsePriceSource = OpenEnum<
  typeof V2ProductListResponsePriceSource
>;

export const V2ProductListResponseAutomaticPricingMode = {
  BasePriceAdjustment: "base_price_adjustment",
  CostMarkup: "cost_markup",
} as const;
export type V2ProductListResponseAutomaticPricingMode = OpenEnum<
  typeof V2ProductListResponseAutomaticPricingMode
>;

export type V2ProductListResponseAppliedPriceList = {
  id: string;
  name: string;
  isAutomatic: boolean;
  automaticPricingMode: V2ProductListResponseAutomaticPricingMode;
  adjustmentPercentage: number | null;
  taxInclusive: boolean;
};

export type V2ProductListResponseData = {
  id: string;
  name: string;
  description: string | null;
  category: V2ProductListResponseCategory | null;
  sku: string;
  barcode: string | null;
  oemCode: string | null;
  currency: string;
  cost: number;
  price: number;
  taxRate: V2ProductListResponseTaxRate;
  stockMinimum: number;
  defaultSupplier: V2ProductListResponseDefaultSupplier | null;
  productType: V2ProductListResponseProductType;
  isActive: boolean;
  organizationSlug: string;
  createdAt: Date;
  updatedAt: Date;
  effectivePrice?: number | undefined;
  priceSource?: V2ProductListResponsePriceSource | undefined;
  appliedPriceList?: V2ProductListResponseAppliedPriceList | undefined;
};

export type V2ProductListResponsePagination = {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};

export type V2ProductListResponse = {
  requestId: string;
  success: true;
  data: Array<V2ProductListResponseData>;
  pagination: V2ProductListResponsePagination;
};

/** @internal */
export const V2ProductListResponseCategory$inboundSchema: z.ZodMiniType<
  V2ProductListResponseCategory,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function v2ProductListResponseCategoryFromJSON(
  jsonString: string,
): SafeParseResult<V2ProductListResponseCategory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ProductListResponseCategory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ProductListResponseCategory' from JSON`,
  );
}

/** @internal */
export const V2ProductListResponseTaxRate$inboundSchema: z.ZodMiniType<
  V2ProductListResponseTaxRate,
  unknown
> = z.object({
  id: types.number(),
  value: types.number(),
});

export function v2ProductListResponseTaxRateFromJSON(
  jsonString: string,
): SafeParseResult<V2ProductListResponseTaxRate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ProductListResponseTaxRate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ProductListResponseTaxRate' from JSON`,
  );
}

/** @internal */
export const V2ProductListResponseDefaultSupplier$inboundSchema: z.ZodMiniType<
  V2ProductListResponseDefaultSupplier,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function v2ProductListResponseDefaultSupplierFromJSON(
  jsonString: string,
): SafeParseResult<V2ProductListResponseDefaultSupplier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V2ProductListResponseDefaultSupplier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ProductListResponseDefaultSupplier' from JSON`,
  );
}

/** @internal */
export const V2ProductListResponseProductType$inboundSchema: z.ZodMiniType<
  V2ProductListResponseProductType,
  unknown
> = openEnums.inboundSchema(V2ProductListResponseProductType);

/** @internal */
export const V2ProductListResponsePriceSource$inboundSchema: z.ZodMiniType<
  V2ProductListResponsePriceSource,
  unknown
> = openEnums.inboundSchema(V2ProductListResponsePriceSource);

/** @internal */
export const V2ProductListResponseAutomaticPricingMode$inboundSchema:
  z.ZodMiniType<V2ProductListResponseAutomaticPricingMode, unknown> = openEnums
    .inboundSchema(V2ProductListResponseAutomaticPricingMode);

/** @internal */
export const V2ProductListResponseAppliedPriceList$inboundSchema: z.ZodMiniType<
  V2ProductListResponseAppliedPriceList,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  isAutomatic: types.boolean(),
  automaticPricingMode: V2ProductListResponseAutomaticPricingMode$inboundSchema,
  adjustmentPercentage: types.nullable(types.number()),
  taxInclusive: types.boolean(),
});

export function v2ProductListResponseAppliedPriceListFromJSON(
  jsonString: string,
): SafeParseResult<V2ProductListResponseAppliedPriceList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V2ProductListResponseAppliedPriceList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ProductListResponseAppliedPriceList' from JSON`,
  );
}

/** @internal */
export const V2ProductListResponseData$inboundSchema: z.ZodMiniType<
  V2ProductListResponseData,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  description: types.nullable(types.string()),
  category: types.nullable(
    z.lazy(() => V2ProductListResponseCategory$inboundSchema),
  ),
  sku: types.string(),
  barcode: types.nullable(types.string()),
  oemCode: types.nullable(types.string()),
  currency: types.string(),
  cost: types.number(),
  price: types.number(),
  taxRate: z.lazy(() => V2ProductListResponseTaxRate$inboundSchema),
  stockMinimum: types.number(),
  defaultSupplier: types.nullable(
    z.lazy(() => V2ProductListResponseDefaultSupplier$inboundSchema),
  ),
  productType: V2ProductListResponseProductType$inboundSchema,
  isActive: types.boolean(),
  organizationSlug: types.string(),
  createdAt: types.date(),
  updatedAt: types.date(),
  effectivePrice: types.optional(types.number()),
  priceSource: types.optional(V2ProductListResponsePriceSource$inboundSchema),
  appliedPriceList: types.optional(
    z.lazy(() => V2ProductListResponseAppliedPriceList$inboundSchema),
  ),
});

export function v2ProductListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<V2ProductListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ProductListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ProductListResponseData' from JSON`,
  );
}

/** @internal */
export const V2ProductListResponsePagination$inboundSchema: z.ZodMiniType<
  V2ProductListResponsePagination,
  unknown
> = z.object({
  page: types.number(),
  limit: types.number(),
  total: types.number(),
  totalPages: types.number(),
});

export function v2ProductListResponsePaginationFromJSON(
  jsonString: string,
): SafeParseResult<V2ProductListResponsePagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ProductListResponsePagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ProductListResponsePagination' from JSON`,
  );
}

/** @internal */
export const V2ProductListResponse$inboundSchema: z.ZodMiniType<
  V2ProductListResponse,
  unknown
> = z.object({
  requestId: types.string(),
  success: types.literal(true),
  data: z.array(z.lazy(() => V2ProductListResponseData$inboundSchema)),
  pagination: z.lazy(() => V2ProductListResponsePagination$inboundSchema),
});

export function v2ProductListResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2ProductListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ProductListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ProductListResponse' from JSON`,
  );
}
