/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a285a097d952
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type V2WarehouseListResponseData = {
  id: string;
  name: string;
  address: string | null;
  isDefault: boolean;
  isActive: boolean;
  pointsOfSaleCount: number;
  memberCount: number;
  registerCount: number;
};

export type V2WarehouseListResponsePagination = {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};

export type V2WarehouseListResponse = {
  requestId: string;
  success: true;
  data: Array<V2WarehouseListResponseData>;
  pagination: V2WarehouseListResponsePagination;
};

/** @internal */
export const V2WarehouseListResponseData$inboundSchema: z.ZodMiniType<
  V2WarehouseListResponseData,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  address: types.nullable(types.string()),
  isDefault: types.boolean(),
  isActive: types.boolean(),
  pointsOfSaleCount: types.number(),
  memberCount: types.number(),
  registerCount: types.number(),
});

export function v2WarehouseListResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<V2WarehouseListResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2WarehouseListResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2WarehouseListResponseData' from JSON`,
  );
}

/** @internal */
export const V2WarehouseListResponsePagination$inboundSchema: z.ZodMiniType<
  V2WarehouseListResponsePagination,
  unknown
> = z.object({
  page: types.number(),
  limit: types.number(),
  total: types.number(),
  totalPages: types.number(),
});

export function v2WarehouseListResponsePaginationFromJSON(
  jsonString: string,
): SafeParseResult<V2WarehouseListResponsePagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2WarehouseListResponsePagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2WarehouseListResponsePagination' from JSON`,
  );
}

/** @internal */
export const V2WarehouseListResponse$inboundSchema: z.ZodMiniType<
  V2WarehouseListResponse,
  unknown
> = z.object({
  requestId: types.string(),
  success: types.literal(true),
  data: z.array(z.lazy(() => V2WarehouseListResponseData$inboundSchema)),
  pagination: z.lazy(() => V2WarehouseListResponsePagination$inboundSchema),
});

export function v2WarehouseListResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2WarehouseListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2WarehouseListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2WarehouseListResponse' from JSON`,
  );
}
